{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[车臣语]]西里尔字母
|- lang="ce"
|style="padding-left:0.15em;text-align:right;"|[[А]]
|style="padding-right:0.15em;text-align:left;"|[[а]]
|style="padding-left:0.15em;text-align:right;"|[[Аь]]
|style="padding-right:0.15em;text-align:left;"|[[аь]]
|style="padding-left:0.15em;text-align:right;"|[[Б]]
|style="padding-right:0.15em;text-align:left;"|[[б]]
|style="padding-left:0.15em;text-align:right;"|[[В]]
|style="padding-right:0.15em;text-align:left;"|[[в]]
|style="padding-left:0.15em;text-align:right;"|[[Г]]
|style="padding-right:0.15em;text-align:left;"|[[г]]
|style="padding-left:0.15em;text-align:right;"|[[Гӏ|ГӀ]]
|style="padding-right:0.15em;text-align:left;"|[[гӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Д]]
|style="padding-right:0.15em;text-align:left;"|[[д]]
|style="padding-left:0.15em;text-align:right;"|[[Е]]
|style="padding-right:0.15em;text-align:left;"|[[е]]
|style="padding-left:0.15em;text-align:right;"|[[Ё]]
|style="padding-right:0.15em;text-align:left;"|[[ё]]
|style="padding-left:0.15em;text-align:right;"|[[Ж]]
|style="padding-right:0.15em;text-align:left;"|[[ж]]
|style="padding-left:0.15em;text-align:right;"|[[З]]
|style="padding-right:0.15em;text-align:left;"|[[з]]
|style="padding-left:0.15em;text-align:right;"|[[И]]
|style="padding-right:0.15em;text-align:left;"|[[и]]
|style="padding-left:0.15em;text-align:right;"|[[Й]]
|style="padding-right:0.15em;text-align:left;"|[[й]]
|style="padding-left:0.15em;text-align:right;"|[[К]]
|style="padding-right:0.15em;text-align:left;"|[[к]]
|style="padding-left:0.15em;text-align:right;"|[[Кх]]
|style="padding-right:0.15em;text-align:left;"|[[кх]]
|- lang="ce"
|style="padding-left:0.15em;text-align:right;"|[[Къ]]
|style="padding-right:0.15em;text-align:left;"|[[къ]]
|style="padding-left:0.15em;text-align:right;"|[[Кӏ|КӀ]]
|style="padding-right:0.15em;text-align:left;"|[[кӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Л]]
|style="padding-right:0.15em;text-align:left;"|[[л]]
|style="padding-left:0.15em;text-align:right;"|[[М]]
|style="padding-right:0.15em;text-align:left;"|[[м]]
|style="padding-left:0.15em;text-align:right;"|[[Н]]
|style="padding-right:0.15em;text-align:left;"|[[н]]
|style="padding-left:0.15em;text-align:right;"|[[О]]
|style="padding-right:0.15em;text-align:left;"|[[о]]
|style="padding-left:0.15em;text-align:right;"|[[Оь]]
|style="padding-right:0.15em;text-align:left;"|[[оь]]
|style="padding-left:0.15em;text-align:right;"|[[П]]
|style="padding-right:0.15em;text-align:left;"|[[п]]
|style="padding-left:0.15em;text-align:right;"|[[Пӏ|ПӀ]]
|style="padding-right:0.15em;text-align:left;"|[[пӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Р]]
|style="padding-right:0.15em;text-align:left;"|[[р]]
|style="padding-left:0.15em;text-align:right;"|[[С]]
|style="padding-right:0.15em;text-align:left;"|[[с]]
|style="padding-left:0.15em;text-align:right;"|[[Т]]
|style="padding-right:0.15em;text-align:left;"|[[т]]
|style="padding-left:0.15em;text-align:right;"|[[Тӏ|ТӀ]]
|style="padding-right:0.15em;text-align:left;"|[[тӏ]]
|style="padding-left:0.15em;text-align:right;"|[[У]]
|style="padding-right:0.15em;text-align:left;"|[[у]]
|style="padding-left:0.15em;text-align:right;"|[[Уь]]
|style="padding-right:0.15em;text-align:left;"|[[уь]]
|- lang="ce"
|style="padding-left:0.15em;text-align:right;"|[[Ф]]
|style="padding-right:0.15em;text-align:left;"|[[ф]]
|style="padding-left:0.15em;text-align:right;"|[[Х]]
|style="padding-right:0.15em;text-align:left;"|[[х]]
|style="padding-left:0.15em;text-align:right;"|[[Хь]]
|style="padding-right:0.15em;text-align:left;"|[[хь]]
|style="padding-left:0.15em;text-align:right;"|[[Хӏ|ХӀ]]
|style="padding-right:0.15em;text-align:left;"|[[хӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Ц]]
|style="padding-right:0.15em;text-align:left;"|[[ц]]
|style="padding-left:0.15em;text-align:right;"|[[Цӏ|ЦӀ]]
|style="padding-right:0.15em;text-align:left;"|[[цӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Ч]]
|style="padding-right:0.15em;text-align:left;"|[[ч]]
|style="padding-left:0.15em;text-align:right;"|[[Чӏ|ЧӀ]]
|style="padding-right:0.15em;text-align:left;"|[[чӏ]]
|style="padding-left:0.15em;text-align:right;"|[[Ш]]
|style="padding-right:0.15em;text-align:left;"|[[ш]]
|style="padding-left:0.15em;text-align:right;"|[[Щ]]
|style="padding-right:0.15em;text-align:left;"|[[щ]]
|style="padding-left:0.15em;text-align:right;"|[[Ъ]]
|style="padding-right:0.15em;text-align:left;"|[[ъ]]
|style="padding-left:0.15em;text-align:right;"|[[Ы]]
|style="padding-right:0.15em;text-align:left;"|[[ы]]
|style="padding-left:0.15em;text-align:right;"|[[Ь]]
|style="padding-right:0.15em;text-align:left;"|[[ь]]
|style="padding-left:0.15em;text-align:right;"|[[Э]]
|style="padding-right:0.15em;text-align:left;"|[[э]]
|style="padding-left:0.15em;text-align:right;"|[[Ю]]
|style="padding-right:0.15em;text-align:left;"|[[ю]]
|- lang="ce"
|style="padding-left:0.15em;text-align:right;"|[[Юь]]
|style="padding-right:0.15em;text-align:left;"|[[юь]]
|style="padding-left:0.15em;text-align:right;"|[[Я]]
|style="padding-right:0.15em;text-align:left;"|[[я]]
|style="padding-left:0.15em;text-align:right;"|[[Яь]]
|style="padding-right:0.15em;text-align:left;"|[[яь]]
|style="padding-left:0.15em;text-align:right;"|[[Ӏ]]
|style="padding-right:0.15em;text-align:left;"|[[ӏ]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/chechen.htm Omniglot - language, alphabet and pronunciation]
[[Category:西里尔字母模板|ce]]
</noinclude>