{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:both;width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[西班牙语]][[西班牙语字母|字母]]
|- lang="es"
|style="padding-right:0.15em;text-align:right;"|[[A]]
|style="padding-left:0.15em;text-align:left;"|[[a]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Á]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[á]])
|style="padding-right:0.15em;text-align:right;"|[[B]]
|style="padding-left:0.15em;text-align:left;"|[[b]]
|style="padding-right:0.15em;text-align:right;"|[[C]]
|style="padding-left:0.15em;text-align:left;"|[[c]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ch (二合字母)|Ch]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ch (二合字母)|ch]])
|style="padding-right:0.15em;text-align:right;"|[[D]]
|style="padding-left:0.15em;text-align:left;"|[[d]]
|style="padding-right:0.15em;text-align:right;"|[[E]]
|style="padding-left:0.15em;text-align:left;"|[[e]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[É]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[é]])
|style="padding-right:0.15em;text-align:right;"|[[F]]
|style="padding-left:0.15em;text-align:left;"|[[f]]
|style="padding-right:0.15em;text-align:right;"|[[G]]
|style="padding-left:0.15em;text-align:left;"|[[g]]
|style="padding-right:0.15em;text-align:right;"|[[H]]
|style="padding-left:0.15em;text-align:left;"|[[h]]
|style="padding-right:0.15em;text-align:right;"|[[I]]
|style="padding-left:0.15em;text-align:left;"|[[i]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Í]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[í]])
|style="padding-right:0.15em;text-align:right;"|[[J]]
|style="padding-left:0.15em;text-align:left;"|[[j]]
|style="padding-right:0.15em;text-align:right;"|[[K]]
|style="padding-left:0.15em;text-align:left;"|[[k]]
|- lang="es"
|style="padding-right:0.15em;text-align:right;"|[[L]]
|style="padding-left:0.15em;text-align:left;"|[[l]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ll]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ll]])
|style="padding-right:0.15em;text-align:right;"|[[M]]
|style="padding-left:0.15em;text-align:left;"|[[m]]
|style="padding-right:0.15em;text-align:right;"|[[N]]
|style="padding-left:0.15em;text-align:left;"|[[n]]
|style="padding-right:0.15em;text-align:right;"|[[Ñ]]
|style="padding-left:0.15em;text-align:left;"|[[ñ]]
|style="padding-right:0.15em;text-align:right;"|[[O]]
|style="padding-left:0.15em;text-align:left;"|[[o]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ó]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ó]])
|style="padding-right:0.15em;text-align:right;"|[[P]]
|style="padding-left:0.15em;text-align:left;"|[[p]]
|style="padding-right:0.15em;text-align:right;"|[[Q]]
|style="padding-left:0.15em;text-align:left;"|[[q]]
|style="padding-right:0.15em;text-align:right;"|[[R]]
|style="padding-left:0.15em;text-align:left;"|[[r]]
|style="padding-right:0.15em;text-align:right;"|[[S]]
|style="padding-left:0.15em;text-align:left;"|[[s]]
|style="padding-right:0.15em;text-align:right;"|[[T]]
|style="padding-left:0.15em;text-align:left;"|[[t]]
|style="padding-right:0.15em;text-align:right;"|[[U]]
|style="padding-left:0.15em;text-align:left;"|[[u]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ú]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ú]])
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ü]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ü]])
|- lang="es"
|style="padding-right:0.15em;text-align:right;"|[[V]]
|style="padding-left:0.15em;text-align:left;"|[[v]]
|style="padding-right:0.15em;text-align:right;"|[[W]]
|style="padding-left:0.15em;text-align:left;"|[[w]]
|style="padding-right:0.15em;text-align:right;"|[[X]]
|style="padding-left:0.15em;text-align:left;"|[[x]]
|style="padding-right:0.15em;text-align:right;"|[[Y]]
|style="padding-left:0.15em;text-align:left;"|[[y]]
|style="padding-right:0.15em;text-align:right;"|[[Z]]
|style="padding-left:0.15em;text-align:left;"|[[z]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/spanish.htm Omniglot - language, alphabet and pronunciation]
[[Category:拉丁字母模板|es]]
</noinclude>