{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[越南语]][[越南语字母|字母]]
|- lang="vi"
|style="padding-left:0.15em;text-align:right;"|[[A]]
|style="padding-right:0.15em;text-align:left;"|[[a]]
|style="padding-left:0.15em;text-align:right;"|[[Ă]]
|style="padding-right:0.15em;text-align:left;"|[[ă]]
|style="padding-left:0.15em;text-align:right;"|[[Â]]
|style="padding-right:0.15em;text-align:left;"|[[â]]
|style="padding-left:0.15em;text-align:right;"|[[B]]
|style="padding-right:0.15em;text-align:left;"|[[b]]
|style="padding-left:0.15em;text-align:right;"|[[C]]
|style="padding-right:0.15em;text-align:left;"|[[c]]
|style="padding-left:0.15em;text-align:right;"|[[D]]
|style="padding-right:0.15em;text-align:left;"|[[d]]
|style="padding-left:0.15em;text-align:right;"|[[Đ]]
|style="padding-right:0.15em;text-align:left;"|[[đ]]
|style="padding-left:0.15em;text-align:right;"|[[E]]
|style="padding-right:0.15em;text-align:left;"|[[e]]
|style="padding-left:0.15em;text-align:right;"|[[Ê]]
|style="padding-right:0.15em;text-align:left;"|[[ê]]
|style="padding-left:0.15em;text-align:right;"|[[G]]
|style="padding-right:0.15em;text-align:left;"|[[g]]
|style="padding-left:0.15em;text-align:right;"|[[H]]
|style="padding-right:0.15em;text-align:left;"|[[h]]
|style="padding-left:0.15em;text-align:right;"|[[I]]
|style="padding-right:0.15em;text-align:left;"|[[i]]
|style="padding-left:0.15em;text-align:right;"|[[K]]
|style="padding-right:0.15em;text-align:left;"|[[k]]
|style="padding-left:0.15em;text-align:right;"|[[L]]
|style="padding-right:0.15em;text-align:left;"|[[l]]
|style="padding-left:0.15em;text-align:right;"|[[M]]
|style="padding-right:0.15em;text-align:left;"|[[m]]
|- lang="vi"
|style="padding-left:0.15em;text-align:right;"|[[N]]
|style="padding-right:0.15em;text-align:left;"|[[n]]
|style="padding-left:0.15em;text-align:right;"|[[O]]
|style="padding-right:0.15em;text-align:left;"|[[o]]
|style="padding-left:0.15em;text-align:right;"|[[Ô]]
|style="padding-right:0.15em;text-align:left;"|[[ô]]
|style="padding-left:0.15em;text-align:right;"|[[Ơ]]
|style="padding-right:0.15em;text-align:left;"|[[ơ]]
|style="padding-left:0.15em;text-align:right;"|[[P]]
|style="padding-right:0.15em;text-align:left;"|[[p]]
|style="padding-left:0.15em;text-align:right;"|[[Q]]
|style="padding-right:0.15em;text-align:left;"|[[q]]
|style="padding-left:0.15em;text-align:right;"|[[R]]
|style="padding-right:0.15em;text-align:left;"|[[r]]
|style="padding-left:0.15em;text-align:right;"|[[S]]
|style="padding-right:0.15em;text-align:left;"|[[s]]
|style="padding-left:0.15em;text-align:right;"|[[T]]
|style="padding-right:0.15em;text-align:left;"|[[t]]
|style="padding-left:0.15em;text-align:right;"|[[U]]
|style="padding-right:0.15em;text-align:left;"|[[u]]
|style="padding-left:0.15em;text-align:right;"|[[Ư]]
|style="padding-right:0.15em;text-align:left;"|[[ư]]
|style="padding-left:0.15em;text-align:right;"|[[V]]
|style="padding-right:0.15em;text-align:left;"|[[v]]
|style="padding-left:0.15em;text-align:right;"|[[X]]
|style="padding-right:0.15em;text-align:left;"|[[x]]
|style="padding-left:0.15em;text-align:right;"|[[Y]]
|style="padding-right:0.15em;text-align:left;"|[[y]]
|&nbsp;
|&nbsp;
|}<noinclude>

== 外部链接 ==
* [http://www.omniglot.com/writing/vietnamese.htm Omniglot - language, alphabet and pronunciation]

[[Category:越南语|*]]
[[Category:拉丁字母模板|vi]]
</noinclude>