{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[奥克语]]字母
|- lang="oc"
|style="padding-left:0.15em;text-align:right;"|[[A]]
|style="padding-right:0.15em;text-align:left;"|[[a]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Á]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[á]])
|style="background-color:#efefef;padding-left:0.15em;text-align:right;"|([[À]]
|style="background-color:#efefef;padding-right:0.15em;text-align:left;"|[[à]])
|style="padding-left:0.15em;text-align:right;"|[[B]]
|style="padding-right:0.15em;text-align:left;"|[[b]]
|style="padding-left:0.15em;text-align:right;"|[[C]]
|style="padding-right:0.15em;text-align:left;"|[[c]]
|style="background-color:#efefef;padding-left:0.15em;text-align:right;"|([[Ç]]
|style="background-color:#efefef;padding-right:0.15em;text-align:left;"|[[ç]])
|style="padding-left:0.15em;text-align:right;"|[[D]]
|style="padding-right:0.15em;text-align:left;"|[[d]]
|style="padding-left:0.15em;text-align:right;"|[[E]]
|style="padding-right:0.15em;text-align:left;"|[[e]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[É]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[é]])
|style="background-color:#efefef;padding-left:0.15em;text-align:right;"|([[È]]
|style="background-color:#efefef;padding-right:0.15em;text-align:left;"|[[è]])
|style="padding-left:0.15em;text-align:right;"|[[F]]
|style="padding-right:0.15em;text-align:left;"|[[f]]
|style="padding-left:0.15em;text-align:right;"|[[G]]
|style="padding-right:0.15em;text-align:left;"|[[g]]
|style="padding-left:0.15em;text-align:right;"|[[H]]
|style="padding-right:0.15em;text-align:left;"|[[h]]
|style="padding-left:0.15em;text-align:right;"|[[I]]
|style="padding-right:0.15em;text-align:left;"|[[i]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Í]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[í]])
|- lang="oc"
|style="padding-left:0.15em;text-align:right;"|[[J]]
|style="padding-right:0.15em;text-align:left;"|[[j]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|[[K]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[k]]
|style="padding-left:0.15em;text-align:right;"|[[L]]
|style="padding-right:0.15em;text-align:left;"|[[l]]
|style="padding-left:0.15em;text-align:right;"|[[M]]
|style="padding-right:0.15em;text-align:left;"|[[m]]
|style="padding-left:0.15em;text-align:right;"|[[N]]
|style="padding-right:0.15em;text-align:left;"|[[n]]
|style="padding-left:0.15em;text-align:right;"|[[O]]
|style="padding-right:0.15em;text-align:left;"|[[o]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ó]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ó]])
|style="background-color:#efefef;padding-left:0.15em;text-align:right;"|([[Ò]]
|style="background-color:#efefef;padding-right:0.15em;text-align:left;"|[[ò]])
|style="padding-left:0.15em;text-align:right;"|[[P]]
|style="padding-right:0.15em;text-align:left;"|[[p]]
|style="padding-left:0.15em;text-align:right;"|[[Q]]
|style="padding-right:0.15em;text-align:left;"|[[q]]
|style="padding-left:0.15em;text-align:right;"|[[R]]
|style="padding-right:0.15em;text-align:left;"|[[r]]
|style="padding-left:0.15em;text-align:right;"|[[S]]
|style="padding-right:0.15em;text-align:left;"|[[s]]
|style="padding-left:0.15em;text-align:right;"|[[T]]
|style="padding-right:0.15em;text-align:left;"|[[t]]
|style="padding-left:0.15em;text-align:right;"|[[U]]
|style="padding-right:0.15em;text-align:left;"|[[u]]
|style="background-color:#efefef;padding-right:0.15em;text-align:right;"|([[Ú]]
|style="background-color:#efefef;padding-left:0.15em;text-align:left;"|[[ú]])
|- lang="oc"
|style="padding-left:0.15em;text-align:right;"|[[V]]
|style="padding-right:0.15em;text-align:left;"|[[v]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|[[W]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[w]]
|style="padding-left:0.15em;text-align:right;"|[[X]]
|style="padding-right:0.15em;text-align:left;"|[[x]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|[[Y]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[y]]
|style="padding-left:0.15em;text-align:right;"|[[Z]]
|style="padding-right:0.15em;text-align:left;"|[[z]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/occitan.htm Omniglot - language, alphabet and pronunciation]
[[Category:拉丁字母模板|oc]]
</noinclude>