{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[阿尔巴尼亚语]]字母
|- lang="sq"
|style="padding-left:0.15em;text-align:right;"|[[A]]
|style="padding-right:0.15em;text-align:left;"|[[a]]
|style="padding-left:0.15em;text-align:right;"|[[B]]
|style="padding-right:0.15em;text-align:left;"|[[b]]
|style="padding-left:0.15em;text-align:right;"|[[C]]
|style="padding-right:0.15em;text-align:left;"|[[c]]
|style="padding-left:0.15em;text-align:right;"|[[Ç]]
|style="padding-right:0.15em;text-align:left;"|[[ç]]
|style="padding-left:0.15em;text-align:right;"|[[D]]
|style="padding-right:0.15em;text-align:left;"|[[d]]
|style="padding-left:0.15em;text-align:right;"|[[Dh]]
|style="padding-right:0.15em;text-align:left;"|[[dh]]
|style="padding-left:0.15em;text-align:right;"|[[E]]
|style="padding-right:0.15em;text-align:left;"|[[e]]
|style="padding-left:0.15em;text-align:right;"|[[Ë]]
|style="padding-right:0.15em;text-align:left;"|[[ë]]
|style="padding-left:0.15em;text-align:right;"|[[F]]
|style="padding-right:0.15em;text-align:left;"|[[f]]
|style="padding-left:0.15em;text-align:right;"|[[G]]
|style="padding-right:0.15em;text-align:left;"|[[g]]
|style="padding-left:0.15em;text-align:right;"|[[Gj]]
|style="padding-right:0.15em;text-align:left;"|[[gj]]
|style="padding-left:0.15em;text-align:right;"|[[H]]
|style="padding-right:0.15em;text-align:left;"|[[h]]
|style="padding-left:0.15em;text-align:right;"|[[I]]
|style="padding-right:0.15em;text-align:left;"|[[i]]
|style="padding-left:0.15em;text-align:right;"|[[J]]
|style="padding-right:0.15em;text-align:left;"|[[j]]
|style="padding-left:0.15em;text-align:right;"|[[K]]
|style="padding-right:0.15em;text-align:left;"|[[k]]
|- lang="sq"
|style="padding-left:0.15em;text-align:right;"|[[L]]
|style="padding-right:0.15em;text-align:left;"|[[l]]
|style="padding-left:0.15em;text-align:right;"|[[Ll]]
|style="padding-right:0.15em;text-align:left;"|[[ll]]
|style="padding-left:0.15em;text-align:right;"|[[M]]
|style="padding-right:0.15em;text-align:left;"|[[m]]
|style="padding-left:0.15em;text-align:right;"|[[N]]
|style="padding-right:0.15em;text-align:left;"|[[n]]
|style="padding-left:0.15em;text-align:right;"|[[Nj]]
|style="padding-right:0.15em;text-align:left;"|[[nj]]
|style="padding-left:0.15em;text-align:right;"|[[O]]
|style="padding-right:0.15em;text-align:left;"|[[o]]
|style="padding-left:0.15em;text-align:right;"|[[P]]
|style="padding-right:0.15em;text-align:left;"|[[p]]
|style="padding-left:0.15em;text-align:right;"|[[Q]]
|style="padding-right:0.15em;text-align:left;"|[[q]]
|style="padding-left:0.15em;text-align:right;"|[[R]]
|style="padding-right:0.15em;text-align:left;"|[[r]]
|style="padding-left:0.15em;text-align:right;"|[[Rr]]
|style="padding-right:0.15em;text-align:left;"|[[rr]]
|style="padding-left:0.15em;text-align:right;"|[[S]]
|style="padding-right:0.15em;text-align:left;"|[[s]]
|style="padding-left:0.15em;text-align:right;"|[[Sh]]
|style="padding-right:0.15em;text-align:left;"|[[sh]]
|style="padding-left:0.15em;text-align:right;"|[[T]]
|style="padding-right:0.15em;text-align:left;"|[[t]]
|style="padding-left:0.15em;text-align:right;"|[[Th]]
|style="padding-right:0.15em;text-align:left;"|[[th]]
|style="padding-left:0.15em;text-align:right;"|[[U]]
|style="padding-right:0.15em;text-align:left;"|[[u]]
|- lang="sq"
|style="padding-left:0.15em;text-align:right;"|[[V]]
|style="padding-right:0.15em;text-align:left;"|[[v]]
|style="padding-left:0.15em;text-align:right;"|[[X]]
|style="padding-right:0.15em;text-align:left;"|[[x]]
|style="padding-left:0.15em;text-align:right;"|[[Xh]]
|style="padding-right:0.15em;text-align:left;"|[[xh]]
|style="padding-left:0.15em;text-align:right;"|[[Y]]
|style="padding-right:0.15em;text-align:left;"|[[y]]
|style="padding-left:0.15em;text-align:right;"|[[Z]]
|style="padding-right:0.15em;text-align:left;"|[[z]]
|style="padding-left:0.15em;text-align:right;"|[[Zh]]
|style="padding-right:0.15em;text-align:left;"|[[zh]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/albanian.htm Omniglot - language, alphabet and pronunciation]
[[Category:拉丁字母模板|sq]]
</noinclude>