{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[下索布语]]字母
|- lang="dsb"
|style="padding-left:0.15em;text-align:right;"|[[A]]
|style="padding-right:0.15em;text-align:left;"|[[a]]
|style="padding-left:0.15em;text-align:right;"|[[B]]
|style="padding-right:0.15em;text-align:left;"|[[b]]
|style="padding-left:0.15em;text-align:right;"|[[C]]
|style="padding-right:0.15em;text-align:left;"|[[c]]
|style="padding-left:0.15em;text-align:right;"|[[Č]]
|style="padding-right:0.15em;text-align:left;"|[[č]]
|style="padding-left:0.15em;text-align:right;"|[[Ć]]
|style="padding-right:0.15em;text-align:left;"|[[ć]]
|style="padding-left:0.15em;text-align:right;"|[[D]]
|style="padding-right:0.15em;text-align:left;"|[[d]]
|style="padding-left:0.15em;text-align:right;"|[[Dź]]
|style="padding-right:0.15em;text-align:left;"|[[dź]]
|style="padding-left:0.15em;text-align:right;"|[[E]]
|style="padding-right:0.15em;text-align:left;"|[[e]]
|style="padding-left:0.15em;text-align:right;"|[[Ě]]
|style="padding-right:0.15em;text-align:left;"|[[ě]]
|style="padding-left:0.15em;text-align:right;"|[[F]]
|style="padding-right:0.15em;text-align:left;"|[[f]]
|style="padding-left:0.15em;text-align:right;"|[[G]]
|style="padding-right:0.15em;text-align:left;"|[[g]]
|style="padding-left:0.15em;text-align:right;"|[[H]]
|style="padding-right:0.15em;text-align:left;"|[[h]]
|style="padding-left:0.15em;text-align:right;"|[[Ch (二合字母)|Ch]]
|style="padding-right:0.15em;text-align:left;"|[[ch (二合字母)|ch]]
|style="padding-left:0.15em;text-align:right;"|[[I]]
|style="padding-right:0.15em;text-align:left;"|[[i]]
|style="padding-left:0.15em;text-align:right;"|[[J]]
|style="padding-right:0.15em;text-align:left;"|[[j]]
|- lang="dsb"
|style="padding-left:0.15em;text-align:right;"|[[K]]
|style="padding-right:0.15em;text-align:left;"|[[k]]
|style="padding-left:0.15em;text-align:right;"|[[Ł]]
|style="padding-right:0.15em;text-align:left;"|[[ł]]
|style="padding-left:0.15em;text-align:right;"|[[L]]
|style="padding-right:0.15em;text-align:left;"|[[l]]
|style="padding-left:0.15em;text-align:right;"|[[M]]
|style="padding-right:0.15em;text-align:left;"|[[m]]
|style="padding-left:0.15em;text-align:right;"|[[N]]
|style="padding-right:0.15em;text-align:left;"|[[n]]
|style="padding-left:0.15em;text-align:right;"|[[Ń]]
|style="padding-right:0.15em;text-align:left;"|[[ń]]
|style="padding-left:0.15em;text-align:right;"|[[O]]
|style="padding-right:0.15em;text-align:left;"|[[o]]
|style="padding-left:0.15em;text-align:right;"|[[Ó]]
|style="padding-right:0.15em;text-align:left;"|[[ó]]
|style="padding-left:0.15em;text-align:right;"|[[P]]
|style="padding-right:0.15em;text-align:left;"|[[p]]
|style="padding-left:0.15em;text-align:right;"|[[R]]
|style="padding-right:0.15em;text-align:left;"|[[r]]
|style="padding-left:0.15em;text-align:right;"|[[Ŕ]]
|style="padding-right:0.15em;text-align:left;"|[[ŕ]]
|style="padding-left:0.15em;text-align:right;"|[[S]]
|style="padding-right:0.15em;text-align:left;"|[[s]]
|style="padding-left:0.15em;text-align:right;"|[[Š]]
|style="padding-right:0.15em;text-align:left;"|[[š]]
|style="padding-left:0.15em;text-align:right;"|[[Ś]]
|style="padding-right:0.15em;text-align:left;"|[[ś]]
|style="padding-left:0.15em;text-align:right;"|[[T]]
|style="padding-right:0.15em;text-align:left;"|[[t]]
|- lang="dsb"
|style="padding-left:0.15em;text-align:right;"|[[U]]
|style="padding-right:0.15em;text-align:left;"|[[u]]
|style="padding-left:0.15em;text-align:right;"|[[W]]
|style="padding-right:0.15em;text-align:left;"|[[w]]
|style="padding-left:0.15em;text-align:right;"|[[Y]]
|style="padding-right:0.15em;text-align:left;"|[[y]]
|style="padding-left:0.15em;text-align:right;"|[[Z]]
|style="padding-right:0.15em;text-align:left;"|[[z]]
|style="padding-left:0.15em;text-align:right;"|[[Ž]]
|style="padding-right:0.15em;text-align:left;"|[[ž]]
|style="padding-left:0.15em;text-align:right;"|[[Ź]]
|style="padding-right:0.15em;text-align:left;"|[[ź]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/sorbian.htm Omniglot - language, alphabet and pronunciation]
[[Category:拉丁字母模板|dsb]]
</noinclude>