{| style="margin:0.2em auto;padding:0;border:1px solid #ced8df;clear:{{{clear|both}}};width:{{{width|36em}}};"
! colspan="30" style="background:#efefef;"|[[柯尔克孜语]]（吉尔吉斯语）西里尔字母
|- lang="ky"
|style="padding-left:0.15em;text-align:right;"|[[А]]
|style="padding-right:0.15em;text-align:left;"|[[а]]
|style="padding-left:0.15em;text-align:right;"|[[Б]]
|style="padding-right:0.15em;text-align:left;"|[[б]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[В]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[в]])
|style="padding-left:0.15em;text-align:right;"|[[Г]]
|style="padding-right:0.15em;text-align:left;"|[[г]]
|style="padding-left:0.15em;text-align:right;"|[[Д]]
|style="padding-right:0.15em;text-align:left;"|[[д]]
|style="padding-left:0.15em;text-align:right;"|[[Е]]
|style="padding-right:0.15em;text-align:left;"|[[е]]
|style="padding-left:0.15em;text-align:right;"|[[Ё]]
|style="padding-right:0.15em;text-align:left;"|[[ё]]
|style="padding-left:0.15em;text-align:right;"|[[Ж]]
|style="padding-right:0.15em;text-align:left;"|[[ж]]
|style="padding-left:0.15em;text-align:right;"|[[З]]
|style="padding-right:0.15em;text-align:left;"|[[з]]
|style="padding-left:0.15em;text-align:right;"|[[И]]
|style="padding-right:0.15em;text-align:left;"|[[и]]
|style="padding-left:0.15em;text-align:right;"|[[Й]]
|style="padding-right:0.15em;text-align:left;"|[[й]]
|style="padding-left:0.15em;text-align:right;"|[[К]]
|style="padding-right:0.15em;text-align:left;"|[[к]]
|style="padding-left:0.15em;text-align:right;"|[[Л]]
|style="padding-right:0.15em;text-align:left;"|[[л]]
|style="padding-left:0.15em;text-align:right;"|[[М]]
|style="padding-right:0.15em;text-align:left;"|[[м]]
|style="padding-left:0.15em;text-align:right;"|[[Н]]
|style="padding-right:0.15em;text-align:left;"|[[н]]
|-lang="ky"
|style="padding-left:0.15em;text-align:right;"|[[Ң]]
|style="padding-right:0.15em;text-align:left;"|[[ң]]
|style="padding-left:0.15em;text-align:right;"|[[О]]
|style="padding-right:0.15em;text-align:left;"|[[о]]
|style="padding-left:0.15em;text-align:right;"|[[Ө]]
|style="padding-right:0.15em;text-align:left;"|[[ө]]
|style="padding-left:0.15em;text-align:right;"|[[П]]
|style="padding-right:0.15em;text-align:left;"|[[п]]
|style="padding-left:0.15em;text-align:right;"|[[Р]]
|style="padding-right:0.15em;text-align:left;"|[[р]]
|style="padding-left:0.15em;text-align:right;"|[[С]]
|style="padding-right:0.15em;text-align:left;"|[[с]]
|style="padding-left:0.15em;text-align:right;"|[[Т]]
|style="padding-right:0.15em;text-align:left;"|[[т]]
|style="padding-left:0.15em;text-align:right;"|[[У]]
|style="padding-right:0.15em;text-align:left;"|[[у]]
|style="padding-left:0.15em;text-align:right;"|[[Ү]]
|style="padding-right:0.15em;text-align:left;"|[[ү]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[Ф]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[ф]])
|style="padding-left:0.15em;text-align:right;"|[[Х]]
|style="padding-right:0.15em;text-align:left;"|[[х]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[Ц]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[ц]])
|style="padding-left:0.15em;text-align:right;"|[[Ч]]
|style="padding-right:0.15em;text-align:left;"|[[ч]]
|style="padding-left:0.15em;text-align:right;"|[[Ш]]
|style="padding-right:0.15em;text-align:left;"|[[ш]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[Щ]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[щ]])
|-lang="ky"
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[Ъ]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[ъ]])
|style="padding-left:0.15em;text-align:right;"|[[Ы]]
|style="padding-right:0.15em;text-align:left;"|[[ы]]
|style="background-color:#dee8ff;padding-left:0.15em;text-align:right;"|([[Ь]]
|style="background-color:#dee8ff;padding-right:0.15em;text-align:left;"|[[ь]])
|style="padding-left:0.15em;text-align:right;"|[[Э]]
|style="padding-right:0.15em;text-align:left;"|[[э]]
|style="padding-left:0.15em;text-align:right;"|[[Ю]]
|style="padding-right:0.15em;text-align:left;"|[[ю]]
|style="padding-left:0.15em;text-align:right;"|[[Я]]
|style="padding-right:0.15em;text-align:left;"|[[я]]
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|&nbsp;
|}<noinclude>
==外部链接==
*[http://www.omniglot.com/writing/kirghiz.htm Omniglot - language, alphabet and pronunciation]
[[Category:西里尔字母模板|ky]]
</noinclude>