{| style="border:0; margin:auto; width:100%; border-collapse:collapse;"
|-
! style="background:#efefef; border:0" colspan="26" |以{{{1|{{PAGENAME}}}}}为首的两个大写字母的缩写
|- style="text-align:center;"
|style="border:0"|[[{{{1|{{PAGENAME}}}}}a]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}b]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}c]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}d]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}e]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}f]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}g]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}h]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}i]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}j]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}k]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}l]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}m]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}n]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}o]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}p]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}q]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}r]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}s]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}t]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}u]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}v]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}w]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}x]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}y]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}z]]
|- style="text-align:center"
|style="border:0"|[[{{{1|{{PAGENAME}}}}}A]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}B]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}C]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}D]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}E]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}F]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}G]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}H]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}I]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}J]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}K]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}L]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}M]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}N]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}O]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}P]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}Q]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}R]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}S]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}T]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}U]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}V]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}W]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}X]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}Y]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}Z]]
|-
! style="background:#efefef; border:0" colspan="26" |以{{{1|{{PAGENAME}}}}}为首的字母+数字的缩写
|- style="text-align:center;"
|-style="text-align:center"
|style="border:0"|&nbsp;||style="border:0"|&nbsp;
|style="border:0"|[[{{{1|{{PAGENAME}}}}}0]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}1]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}2]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}3]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}4]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}5]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}6]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}7]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}8]]||style="border:0"|[[{{{1|{{PAGENAME}}}}}9]]
|style="border:0"|&nbsp;||style="border:0"|&nbsp;
|style="border:0"|[[0{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[1{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[2{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[3{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[4{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[5{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[6{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[7{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[8{{{1|{{PAGENAME}}}}}]]||style="border:0"|[[9{{{1|{{PAGENAME}}}}}]]
|style="border:0"|&nbsp;||style="border:0"|&nbsp;
|}<noinclude>
[[Category:拉丁字母模板|{{PAGENAME}}]]
</noinclude>