<includeonly>{{#if:{{{Formula|}}}{{{化學式|}}}{{{化学式|}}}{{{MolarMass|}}}{{{摩爾質量|}}}{{{摩尔质量|}}}{{{MolarMassOther|}}}{{{ExactMass|}}}{{{Appearance|}}}{{{外觀|}}}{{{外观|}}}{{{Odor|}}}{{{Odour|}}}{{{氣味|}}}{{{气味|}}}{{{Density|}}}{{{密度|}}}{{{DensitySolid|}}}{{{DensityLiquid|}}}{{{DensityGas|}}}{{{MeltingPt|}}}{{{熔點|}}}{{{熔点|}}}{{{MeltingPtC|}}}{{{MeltingPtCL|}}}{{{MeltingPtF|}}}{{{MeltingPtFL|}}}{{{MeltingPtK|}}}{{{MeltingPtKL|}}}{{{BoilingPt|}}}{{{沸點|}}}{{{沸点|}}}{{{BoilingPtC|}}}{{{BoilingPtF|}}}{{{BoilingPtK|}}}{{{BoilingPtCL|}}}{{{BoilingPtFL|}}}{{{BoilingPtKL|}}}{{{SublimationConditions|}}}{{{升華條件|}}}{{{升华条件|}}}{{{SublimationEnthalpy|}}}{{{升華熱|}}}{{{升华热|}}}{{{CriticalPt|}}}{{{臨界點|}}}{{{临界点|}}}{{{Ksp|}}}{{{SolubilityProduct|}}}{{{SolubilityProductAs|}}}{{{Solubility|}}}{{{溶解度|}}}{{{Solvent|}}}{{{溶劑|}}}{{{溶剂|}}}{{{Solubility1|}}}{{{Solubility2|}}}{{{Solubility3|}}}{{{Solubility4|}}}{{{Solubility5|}}}{{{SolubleOther|}}}{{{SolOther|}}}{{{溶解度其他|}}}{{{溶解度其它|}}}{{{LogP|}}}{{{VaporPressure|}}}{{{蒸氣壓|}}}{{{蒸气压|}}}{{{CriticalRelativeHumidity|}}}{{{HenryConstant|}}}{{{亨利常數|}}}{{{亨利常数|}}}{{{AtmosphericOHRateConstant|}}}{{{pKa|}}}{{{pKb|}}}{{{pI|}}}{{{IsoelectricPt|}}}{{{等電點|}}}{{{等电点|}}}{{{ThermalConductivity|}}}{{{LambdaMax|}}}{{{最大吸收波長|}}}{{{最大吸收波长|}}}{{{Absorbance|}}}{{{吸光度|}}}{{{BandGap|}}}{{{能隙|}}}{{{带隙|}}}{{{禁带|}}}{{{ElectronMobility|}}}{{{電子遷移率|}}}{{{电子迁移率|}}}{{{SpecRotation|}}}{{{RefractIndex|}}}{{{Viscosity|}}}{{{黏度|}}}{{{粘度|}}}{{{MagSus|}}}{{{SpecificSurfaceArea|}}}{{{PoreVolume|}}}{{{AveragePoreSize|}}}{{{Dipole|}}}{{{OrbitalHybridisation|}}}{{{H|}}}{{{He|}}}{{{Li|}}}{{{Be|}}}{{{B|}}}{{{C|}}}{{{N|}}}{{{O|}}}{{{F|}}}{{{Ne|}}}{{{Na|}}}{{{Mg|}}}{{{Al|}}}{{{Si|}}}{{{P|}}}{{{S|}}}{{{Cl|}}}{{{Ar|}}}{{{K|}}}{{{Ca|}}}{{{Sc|}}}{{{Ti|}}}{{{V|}}}{{{Cr|}}}{{{Mn|}}}{{{Fe|}}}{{{Co|}}}{{{Ni|}}}{{{Cu|}}}{{{Zn|}}}{{{Ga|}}}{{{Ge|}}}{{{As|}}}{{{Se|}}}{{{Br|}}}{{{Kr|}}}{{{Rb|}}}{{{Sr|}}}{{{Y|}}}{{{Zr|}}}{{{Nb|}}}{{{Mo|}}}{{{Tc|}}}{{{Ru|}}}{{{Rh|}}}{{{Pd|}}}{{{Ag|}}}{{{Cd|}}}{{{In|}}}{{{Sn|}}}{{{Sb|}}}{{{Te|}}}{{{I|}}}{{{Xe|}}}{{{Cs|}}}{{{Ba|}}}{{{La|}}}{{{Ce|}}}{{{Pr|}}}{{{Nd|}}}{{{Pm|}}}{{{Sm|}}}{{{Eu|}}}{{{Gd|}}}{{{Tb|}}}{{{Dy|}}}{{{Ho|}}}{{{Er|}}}{{{Tm|}}}{{{Yb|}}}{{{Lu|}}}{{{Hf|}}}{{{Ta|}}}{{{W|}}}{{{Re|}}}{{{Os|}}}{{{Ir|}}}{{{Pt|}}}{{{Au|}}}{{{Hg|}}}{{{Tl|}}}{{{Pb|}}}{{{Bi|}}}{{{Po|}}}{{{At|}}}{{{Rn|}}}{{{Fr|}}}{{{Ra|}}}{{{Ac|}}}{{{Th|}}}{{{Pa|}}}{{{U|}}}{{{Np|}}}{{{Pu|}}}{{{Am|}}}{{{Cm|}}}{{{Bk|}}}{{{Cf|}}}{{{Es|}}}{{{Fm|}}}{{{Md|}}}{{{No|}}}{{{Lr|}}}{{{Rf|}}}{{{Db|}}}{{{Sg|}}}{{{Bh|}}}{{{Hs|}}}{{{Mt|}}}{{{Ds|}}}{{{Rg|}}}{{{Cn|}}}{{{Uut|}}}{{{Uuq|}}}{{{Uup|}}}{{{Uuh|}}}{{{Uus|}}}{{{Uuo|}}}|! {{Chembox header}} {{!}} 性质{{{Reference|{{{參考|{{{参考|}}}}}}}}}
{{!}}-
{{#if:{{{H|}}}{{{He|}}}{{{Li|}}}{{{Be|}}}{{{B|}}}{{{C|}}}{{{N|}}}{{{O|}}}{{{F|}}}{{{Ne|}}}{{{Na|}}}{{{Mg|}}}{{{Al|}}}{{{Si|}}}{{{P|}}}{{{S|}}}{{{Cl|}}}{{{Ar|}}}{{{K|}}}{{{Ca|}}}{{{Sc|}}}{{{Ti|}}}{{{V|}}}{{{Cr|}}}{{{Mn|}}}{{{Fe|}}}{{{Co|}}}{{{Ni|}}}{{{Cu|}}}{{{Zn|}}}{{{Ga|}}}{{{Ge|}}}{{{As|}}}{{{Se|}}}{{{Br|}}}{{{Kr|}}}{{{Rb|}}}{{{Sr|}}}{{{Y|}}}{{{Zr|}}}{{{Nb|}}}{{{Mo|}}}{{{Tc|}}}{{{Ru|}}}{{{Rh|}}}{{{Pd|}}}{{{Ag|}}}{{{Cd|}}}{{{In|}}}{{{Sn|}}}{{{Sb|}}}{{{Te|}}}{{{I|}}}{{{Xe|}}}{{{Cs|}}}{{{Ba|}}}{{{La|}}}{{{Ce|}}}{{{Pr|}}}{{{Nd|}}}{{{Pm|}}}{{{Sm|}}}{{{Eu|}}}{{{Gd|}}}{{{Tb|}}}{{{Dy|}}}{{{Ho|}}}{{{Er|}}}{{{Tm|}}}{{{Yb|}}}{{{Lu|}}}{{{Hf|}}}{{{Ta|}}}{{{W|}}}{{{Re|}}}{{{Os|}}}{{{Ir|}}}{{{Pt|}}}{{{Au|}}}{{{Hg|}}}{{{Tl|}}}{{{Pb|}}}{{{Bi|}}}{{{Po|}}}{{{At|}}}{{{Rn|}}}{{{Fr|}}}{{{Ra|}}}{{{Ac|}}}{{{Th|}}}{{{Pa|}}}{{{U|}}}{{{Np|}}}{{{Pu|}}}{{{Am|}}}{{{Cm|}}}{{{Bk|}}}{{{Cf|}}}{{{Es|}}}{{{Fm|}}}{{{Md|}}}{{{No|}}}{{{Lr|}}}{{{Rf|}}}{{{Db|}}}{{{Sg|}}}{{{Bh|}}}{{{Hs|}}}{{{Mt|}}}{{{Ds|}}}{{{Rg|}}}{{{Cn|}}}{{{Uut|}}}{{{Uuq|}}}{{{Uup|}}}{{{Uuh|}}}{{{Uus|}}}{{{Uuo|}}}|{{Chembox Elements|H={{{H|0}}}|He={{{He|0}}}|Li={{{Li|0}}}|Be={{{Be|0}}}|B={{{B|0}}}|C={{{C|0}}}|N={{{N|0}}}|O={{{O|0}}}|F={{{F|0}}}|Ne={{{Ne|0}}}|Na={{{Na|0}}}|Mg={{{Mg|0}}}|Al={{{Al|0}}}|Si={{{Si|0}}}|P={{{P|0}}}|S={{{S|0}}}|Cl={{{Cl|0}}}|Ar={{{Ar|0}}}|K={{{K|0}}}|Ca={{{Ca|0}}}|Sc={{{Sc|0}}}|Ti={{{Ti|0}}}|V={{{V|0}}}|Cr={{{Cr|0}}}|Mn={{{Mn|0}}}|Fe={{{Fe|0}}}|Co={{{Co|0}}}|Ni={{{Ni|0}}}|Cu={{{Cu|0}}}|Zn={{{Zn|0}}}|Ga={{{Ga|0}}}|Ge={{{Ge|0}}}|As={{{As|0}}}|Se={{{Se|0}}}|Br={{{Br|0}}}|Kr={{{Kr|0}}}|Rb={{{Rb|0}}}|Sr={{{Sr|0}}}|Y={{{Y|0}}}|Zr={{{Zr|0}}}|Nb={{{Nb|0}}}|Mo={{{Mo|0}}}|Tc={{{Tc|0}}}|Ru={{{Ru|0}}}|Rh={{{Rh|0}}}|Pd={{{Pd|0}}}|Ag={{{Ag|0}}}|Cd={{{Cd|0}}}|In={{{In|0}}}|Sn={{{Sn|0}}}|Sb={{{Sb|0}}}|Te={{{Te|0}}}|I={{{I|0}}}|Xe={{{Xe|0}}}|Cs={{{Cs|0}}}|Ba={{{Ba|0}}}|La={{{La|0}}}|Ce={{{Ce|0}}}|Pr={{{Pr|0}}}|Nd={{{Nd|0}}}|Pm={{{Pm|0}}}|Sm={{{Sm|0}}}|Eu={{{Eu|0}}}|Gd={{{Gd|0}}}|Tb={{{Tb|0}}}|Dy={{{Dy|0}}}|Ho={{{Ho|0}}}|Er={{{Er|0}}}|Tm={{{Tm|0}}}|Yb={{{Yb|0}}}|Lu={{{Lu|0}}}|Hf={{{Hf|0}}}|Ta={{{Ta|0}}}|W={{{W|0}}}|Re={{{Re|0}}}|Os={{{Os|0}}}|Ir={{{Ir|0}}}|Pt={{{Pt|0}}}|Au={{{Au|0}}}|Hg={{{Hg|0}}}|Tl={{{Tl|0}}}|Pb={{{Pb|0}}}|Bi={{{Bi|0}}}|Po={{{Po|0}}}|At={{{At|0}}}|Rn={{{Rn|0}}}|Fr={{{Fr|0}}}|Ra={{{Ra|0}}}|Ac={{{Ac|0}}}|Th={{{Th|0}}}|Pa={{{Pa|0}}}|U={{{U|0}}}|Np={{{Np|0}}}|Pu={{{Pu|0}}}|Am={{{Am|0}}}|Cm={{{Cm|0}}}|Bk={{{Bk|0}}}|Cf={{{Cf|0}}}|Es={{{Es|0}}}|Fm={{{Fm|0}}}|Md={{{Md|0}}}|No={{{No|0}}}|Lr={{{Lr|0}}}|Rf={{{Rf|0}}}|Db={{{Db|0}}}|Sg={{{Sg|0}}}|Bh={{{Bh|0}}}|Hs={{{Hs|0}}}|Mt={{{Mt|0}}}|Ds={{{Ds|0}}}|Rg={{{Rg|0}}}|Cn={{{Cn|0}}}|Uut={{{Uut|0}}}|Uuq={{{Uuq|0}}}|Uup={{{Uup|0}}}|Uuh={{{Uuh|0}}}|Uus={{{Uus|0}}}|Uuo={{{Uuo|0}}}|MassRound={{{MassRound|2}}}|Note={{{MolarMass_notes|}}} }} |
{{Chembox entry|par_name={{#if:{{{Formula|}}}{{{化學式|}}}{{{化学式|}}}|Formula }}|par_value={{#if:{{{Formula|}}}{{{化學式|}}}{{{化学式|}}}|<span xml:lang="en" lang="en">{{{Formula|{{{化學式|{{{化学式}}}}}}}}}</span> }} }}
{{Chembox entry|par_name={{#if:{{{MolarMass|}}}{{{摩爾質量|}}}{{{摩尔质量|}}}|MolarMass }}        |par_value={{#if:{{{MolarMass|{{{摩爾質量|{{{摩尔质量|}}}}}}}}}|{{{MolarMass|{{{摩爾質量|{{{摩尔质量}}}}}}}}} }} | par_value2={{#if:{{{MolarMass_notes|}}}|{{{MolarMass_notes}}} }}  }} }}
{{Chembox entry|par_name={{#if:{{{ExactMass|}}}|ExactMass }}|par_value={{#if:{{{ExactMass|}}}|{{{ExactMass}}} }}|par_value2={{#if:{{{ExactMass_notes|}}}|[[{{{ExactMass_notes}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{MolarMassOther|}}}|MolarMassOther }}|par_value={{#if:{{{MolarMassOther|}}}|{{{MolarMassOther}}} }} }}
{{Chembox entry|par_name={{#if:{{{Appearance|}}}{{{外觀|}}}{{{外观|}}}|Appearance }}|par_value={{#if:{{{Appearance|}}}{{{外觀|}}}{{{外观|}}}|{{{Appearance|{{{外觀|{{{外观}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{Odor|}}}{{{Odour|}}}{{{氣味|}}}{{{气味|}}}|Odor }}|par_value={{#if:{{{Odor|}}}{{{Odour|}}}{{{氣味|}}}{{{气味|}}}|{{{Odor|{{{Odour|{{{氣味|{{{气味}}}}}}}}} }}} }} }}
{{Chembox entry|par_name={{#if:{{{Density|}}}{{{密度|}}}|Density }}|par_value={{#if:{{{Density|}}}{{{密度|}}}|{{{Density|{{{密度}}}}}} }}|par_value3={{#if:{{{Density_notes|}}}|{{{Density_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{DensitySolid|}}}|Density }}|par_value={{#if:{{{DensitySolid|}}}|{{{DensitySolid}}} }}|par_value2 = <span xml:lang="en" lang="en">g·cm<sup>-3</sup></span>|par_value3={{#if:{{{Density_notes|}}}|{{{Density_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{DensityLiquid|}}}|Density }}|par_value={{#if:{{{DensityLiquid|}}}|{{{DensityLiquid}}} }}|par_value2 = <span xml:lang="en" lang="en">g·mL<sup>-1</sup></span>|par_value3={{#if:{{{Density_notes|}}}|{{{Density_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{DensityGas|}}}|Density }}|par_value={{#if:{{{DensityGas|}}}|{{{DensityGas}}} }}|par_value2 = <span xml:lang="en" lang="en">kg·m<sup>-3</sup></span>|par_value3={{#if:{{{Density_notes|}}}|{{{Density_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{MeltingPt|}}}{{{熔點|}}}{{{熔点|}}}{{{MeltingPtC|}}}{{{MeltingPtF|}}}{{{MeltingPtK|}}}{{{MeltingPtCL|}}}{{{MeltingPtFL|}}}{{{MeltingPtKL|}}}|MeltingPt }} |par_value={{#if:{{{MeltingPt|}}}{{{熔點|}}}{{{熔点|}}}|{{{MeltingPt|{{{熔點|{{{熔点}}}}}}}}} }} |par_value1={{#if:{{{MeltingPtC|}}}{{{MeltingPtCL|}}}|{{{MeltingPtC|{{{MeltingPtCL|}}}}}} }} |par_value2={{#if:{{{MeltingPtF|}}}{{{MeltingPtFL|}}}|{{{MeltingPtF|{{{MeltingPtFL|}}}}}} }} |par_value3={{#if:{{{MeltingPtK|}}}{{{MeltingPtKL|}}}|{{{MeltingPtK|{{{MeltingPtKL|}}}}}} }} |par_value4={{#if:{{{MeltingPtCH|}}}|{{{MeltingPtCH}}} }} |par_value5={{#if:{{{MeltingPtFH|}}}|{{{MeltingPtFH}}} }} |par_value6={{#if:{{{MeltingPtKH|}}}|{{{MeltingPtKH}}} }} | par_label={{#if:{{{Melting_notes|}}}|{{{Melting_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{BoilingPt|}}}{{{沸點|}}}{{{沸点|}}}{{{BoilingPtC|}}}{{{BoilingPtF|}}}{{{BoilingPtK|}}}{{{BoilingPtCL|}}}{{{BoilingPtFL|}}}{{{BoilingPtKL|}}}|BoilingPt }} |par_value={{#if:{{{BoilingPt|}}}{{{沸點|}}}{{{沸点|}}}|{{{BoilingPt|{{{沸點|{{{沸点}}}}}}}}} }} |par_value1={{#if:{{{BoilingPtC|}}}{{{BoilingPtCL|}}}|{{{BoilingPtC|{{{BoilingPtCL|}}}}}} }} |par_value2={{#if:{{{BoilingPtF|}}}{{{BoilingPtFL|}}}|{{{BoilingPtF|{{{BoilingPtFL|}}}}}} }} |par_value3={{#if:{{{BoilingPtK|}}}{{{BoilingPtKL|}}}|{{{BoilingPtK|{{{BoilingPtKL|}}}}}} }} |par_value4={{#if:{{{BoilingPtCH|}}}|{{{BoilingPtCH}}} }} |par_value5={{#if:{{{BoilingPtFH|}}}|{{{BoilingPtFH}}} }} |par_value6={{#if:{{{BoilingPtKH|}}}|{{{BoilingPtKH}}} }} | par_label={{#if:{{{Boiling_notes|}}}|{{{Boiling_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{SublimationConditions|}}}{{{升華條件|}}}{{{升华条件|}}}|SublimationConditions }}|par_value={{#if:{{{SublimationConditions|}}}{{{升華條件|}}}{{{升华条件|}}}|{{{SublimationConditions|{{{升華條件|{{{升华条件}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{SublimationEnthalpy|}}}{{{升華熱|}}}{{{升华热|}}}|SublimationEnthalpy}}|par_value={{#if:{{{SublimationEnthalpy|}}}{{{升華熱|}}}{{{升华热|}}}|{{{SublimationEnthalpy|{{{升華熱|{{{升华热}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{SublimationConditions|}}}|SublimationConditions }}            |par_value={{#if:{{{SublimationConditions|}}}|{{{SublimationConditions}}} }} }}
{{Chembox entry|par_name={{#if:{{{CriticalPt|}}}{{{臨界點|}}}{{{临界点|}}}|CriticalPt }} |par_value={{#if:{{{CriticalPt|}}}{{{臨界點|}}}{{{临界点|}}}|{{{CriticalPt|{{{臨界點|{{{临界点}}}}}}}}} }}|par_value2={{#if:{{{CriticalPt_notes|}}}|{{{CriticalPt_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{Solubility|}}}|Solubility }} |par_value={{#if:{{{Solubility|}}}|{{{Solubility}}} }}|par_label=[[水]] }}
{{Chembox entry|par_name={{#if:{{{Ksp|}}}{{{SolubilityProduct|}}}|SolubilityProduct }}  |par_value={{#if:{{{Ksp|}}}{{{SolubilityProduct|}}}|{{{Ksp|{{{SolubilityProduct}}}}}} }}|par_label={{#if:{{{SolubilityProductAs|}}}|{{{SolubilityProductAs}}} }} }}
{{Chembox entry|par_name={{#if:{{{SolubleOther|}}}{{{溶解度|}}}|Solubility }}  |par_value={{#if:{{{SolubleOther|}}}{{{溶解度|}}}|{{{SolubleOther|{{{溶解度}}}}}} }}|par_label={{#if:{{{Solvent|}}}{{{溶劑|}}}{{{溶剂|}}}|{{{Solvent|{{{溶劑|{{{溶剂}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{Solubility1|}}}|Solubility }}  |par_value={{#if:{{{Solubility1|}}}|{{{Solubility1}}} }}|par_label={{#if:{{{Solvent1|}}}|[[{{{Solvent1}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{Solubility2|}}}|Solubility }}  |par_value={{#if:{{{Solubility2|}}}|{{{Solubility2}}} }}|par_label={{#if:{{{Solvent2|}}}|[[{{{Solvent2}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{Solubility3|}}}|Solubility }}  |par_value={{#if:{{{Solubility3|}}}|{{{Solubility3}}} }}|par_label={{#if:{{{Solvent3|}}}|[[{{{Solvent3}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{Solubility4|}}}|Solubility }}  |par_value={{#if:{{{Solubility4|}}}|{{{Solubility4}}} }}|par_label={{#if:{{{Solvent4}}}|[[{{{Solvent4}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{Solubility5|}}}|Solubility }}  |par_value={{#if:{{{Solubility5|}}}|{{{Solubility5}}} }}|par_label={{#if:{{{Solvent5|}}}|[[{{{Solvent5}}}]] }} }}
{{Chembox entry|par_name={{#if:{{{SolOther|}}}{{{溶解度其他|}}}{{{溶解度其它|}}}|Solubility }} |par_value={{#if:{{{SolOther|}}}{{{溶解度其他|}}}{{{溶解度其它|}}}|{{{SolOther|{{{溶解度其他|{{{溶解度其它|}}}}}}}}} }}|par_label = 其他 }}
{{Chembox entry|par_name={{#if:{{{LogP|}}}|LogP }}|par_value={{#if:{{{LogP|}}}|{{{LogP}}} }}|par_value2={{#if:{{{LogP_notes|}}}|{{{LogP_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{VaporPressure|}}}{{{蒸氣壓|}}}{{{蒸气压|}}}|VaporPressure }}|par_value={{#if:{{{VaporPressure|}}}{{{蒸氣壓|}}}{{{蒸气压|}}}|{{{VaporPressure|{{{蒸氣壓|{{{蒸气压}}}}}}}}} }}|par_value2={{#if:{{{VaporPressure_notes|}}}|{{{VaporPressure_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{HenryConstant|}}}{{{亨利常數|}}}{{{亨利常数|}}}|HenryConstant }}|par_value={{#if:{{{HenryConstant|}}}{{{亨利常數|}}}{{{亨利常数|}}}|{{{HenryConstant|{{{亨利常數|{{{亨利常数}}}}}}}}} }}|par_value2={{#if:{{{HenryConstant_notes|}}}|{{{HenryConstant_notes}}} }}|par_label={{#if:{{{HenryConstant_label|}}}|{{{HenryConstant_label}}} }} }}
{{Chembox entry|par_name={{#if:{{{AtmosphericOHRateConstant|}}}|AtmosphericOHRateConstant }}|par_value={{#if:{{{AtmosphericOHRateConstant|}}}|{{{AtmosphericOHRateConstant}}} }} }}
{{Chembox entry|par_name={{#if:{{{pKa|}}}{{{pKa1|}}}|pKa }}|par_value={{#if:{{{pKa|}}}|<span xml:lang="en" lang="en">{{{pKa}}}</span> }}
|par_value1={{#if:{{{pKa1|}}}|<span xml:lang="en" lang="en">{{{pKa1}}}</span> }} |par_value2={{#if:{{{pKa2|}}}|<span xml:lang="en" lang="en">{{{pKa2}}}</span> }} |par_value3={{#if:{{{pKa3|}}}|<span xml:lang="en" lang="en">{{{pKa3}}}</span> }} |par_value4={{#if:{{{pKa4|}}}|<span xml:lang="en" lang="en">{{{pKa4}}}</span> }} |par_value5={{#if:{{{pKa5|}}}|<span xml:lang="en" lang="en">{{{pKa5}}}</span> }} |par_value6={{#if:{{{pKa6|}}}|<span xml:lang="en" lang="en">{{{pKa6}}}</span> }} }}
{{Chembox entry|par_name={{#if:{{{pKb|}}}{{{pKb1|}}}|pKb }}|par_value={{#if:{{{pKb|}}}|<span xml:lang="en" lang="en">{{{pKb}}}</span> }}
|par_value1={{#if:{{{pKb1|}}}|<span xml:lang="en" lang="en">{{{pKb1}}}</span> }} |par_value2={{#if:{{{pKb2|}}}|<span xml:lang="en" lang="en">{{{pKb2}}}</span> }} |par_value3={{#if:{{{pKb3|}}}|<span xml:lang="en" lang="en">{{{pKb3}}}</span> }} |par_value4={{#if:{{{pKb4|}}}|<span xml:lang="en" lang="en">{{{pKb4}}}</span> }} |par_value5={{#if:{{{pKb5|}}}|<span xml:lang="en" lang="en">{{{pKb5}}}</span> }} |par_value6={{#if:{{{pKb6|}}}|<span xml:lang="en" lang="en">{{{pKb6}}}</span> }} }}
{{Chembox entry|par_name={{#if:{{{pI|}}}{{{IsoelectricPt|}}}{{{等電點|}}}{{{等电点|}}}|pI }}|par_value={{#if:{{{pI|}}}{{{IsoelectricPt|}}}{{{等電點|}}}{{{等电点|}}}|{{{pI|{{{IsoelectricPt|{{{等電點|{{{等电点}}}}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{LambdaMax|}}}{{{最大吸收波長|}}}{{{最大吸收波长|}}}|LambdaMax }} |par_value={{#if:{{{LambdaMax|}}}{{{最大吸收波長|}}}{{{最大吸收波长|}}}|{{{LambdaMax|{{{最大吸收波長|{{{最大吸收波长}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{Absorbance|}}}{{{吸光度|}}}|Absorbance }}|par_value={{#if:{{{Absorbance|}}}{{{吸光度|}}}|{{{Absorbance|{{{吸光度}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{BandGap|}}}{{{能隙|}}}{{{带隙|}}}{{{禁带|}}}|BandGap }}        |par_value={{#if:{{{BandGap|}}}{{{能隙|}}}{{{带隙|}}}{{{禁带|}}}|{{{BandGap|{{{能隙|{{{带隙|{{{禁带}}}}}}}}}}}} }}|par_value2={{#if:{{{BandGap_notes|}}}|{{{BandGap_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{ElectronMobility|}}}{{{電子遷移率|}}}{{{电子迁移率|}}}|ElectronMobility }}|par_value={{#if:{{{ElectronMobility|}}}{{{電子遷移率|}}}{{{电子迁移率|}}}|{{{ElectronMobility|{{{電子遷移率|{{{电子迁移率}}}}}}}}} }} }}
{{Chembox entry|par_name={{#if:{{{SpecRotation|}}}|SpecRotation }}|par_value={{#if:{{{SpecRotation|}}}|{{{SpecRotation}}} }}|par_value1={{{SpecRotation_notes|}}}|par_value2={{{SpecRotation_t|}}}|par_value3={{{SpecRotation_l|}}} }}
{{Chembox entry|par_name={{#if:{{{MagSus|}}}|MagSus }}|par_value={{#if:{{{MagSus|}}}|{{{MagSus}}} }} }}
{{Chembox entry|par_name={{#if:{{{ThermalConductivity|}}}|ThermalConductivity }}|par_value={{#if:{{{ThermalConductivity|}}}|{{{ThermalConductivity}}} }} }}
{{Chembox entry|par_name={{#if:{{{RefractIndex|}}}|RefractIndex }}|par_value={{#if:{{{RefractIndex|}}}|{{{RefractIndex}}} }}|par_value1={{#if:{{{RefractIndex_notes|}}}|{{{RefractIndex_notes}}} }} |par_value2={{#if:{{{RefractIndex_t|}}}|{{{RefractIndex_t}}} }}|par_value3={{#if:{{{RefractIndex_l|}}}|{{{RefractIndex_l}}} }} }}
{{Chembox entry|par_name={{#if:{{{Viscosity|}}}{{{黏度|}}}{{{粘度|}}}|Viscosity }}|par_value={{#if:{{{Viscosity|}}}{{{黏度|}}}{{{粘度|}}}|{{{Viscosity|{{{黏度|{{{粘度}}}}}}}}} }}|par_value2={{#if:{{{Viscosity_notes|}}}|{{{Viscosity_notes}}} }} }}
{{Chembox entry|par_name={{#if:{{{CriticalRelativeHumidity|}}}|CriticalRelativeHumidity }}|par_value={{#if:{{{CriticalRelativeHumidity|}}}|{{{CriticalRelativeHumidity}}} }} }}
{{Chembox entry|par_name={{#if:{{{SpecificSurfaceArea|}}}|SpecificSurfaceArea }}|par_value={{#if:{{{SpecificSurfaceArea|}}}|{{{SpecificSurfaceArea}}} }} }}
{{Chembox entry|par_name={{#if:{{{PoreVolume|}}}|PoreVolume }}|par_value={{#if:{{{PoreVolume|}}}|{{{PoreVolume}}} }} }}
{{Chembox entry|par_name={{#if:{{{AveragePoreSize|}}}|AveragePoreSize }}|par_value={{#if:{{{AveragePoreSize|}}}|{{{AveragePoreSize}}} }} }}
{{Chembox entry|par_name={{#if:{{{Dipole|}}}|Dipole }}|par_value={{#if:{{{Dipole|}}}|{{{Dipole}}} }} }} 
{{Chembox entry|par_name={{#if:{{{OrbitalHybridisation|}}}|OrbitalHybridisation }}|par_value={{#if:{{{OrbitalHybridisation|}}}|{{{OrbitalHybridisation}}} }} }} 
}}</includeonly>
<noinclude>{{Documentation}}</noinclude>