<includeonly>=={{</includeonly><includeonly>
subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}
| fame | 知名度 | 關注度 | 关注度 = 30天后仍掛有{{tl|notability}}模板的條目
| substub | 小小作品 = 到期篩選的小小作品
| substub-1 | 1月小小作品= 1月份小小作品
| substub-2 | 2月小小作品= 2月份小小作品
| substub-3 | 3月小小作品= 3月份小小作品
| substub-4 | 4月小小作品= 4月份小小作品
| substub-5 | 5月小小作品= 5月份小小作品
| substub-6 | 6月小小作品= 6月份小小作品
| substub-7 | 7月小小作品= 7月份小小作品
| substub-8 | 8月小小作品= 8月份小小作品
| substub-9 | 9月小小作品= 9月份小小作品
| substub-10 | 10月小小作品= 10月份小小作品
| substub-11 | 11月小小作品= 11月份小小作品
| substub-12 | 12月小小作品= 12月份小小作品
| #default=
}}==
{{</includeonly><includeonly>subst:#if:消除多余斷行|
{{</includeonly><includeonly>
subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}
| fame | 知名度 | 关注度 | 關注度 = <span style="font-size:smaller;">(已掛[[template:notability|關注度模板]]30天)</span>}}
{{</includeonly><includeonly>subst:#ifeq:{{</includeonly><includeonly>subst:#time:Y/m/d}}|{{</includeonly><includeonly>subst:#time:Y/m/d|{{</includeonly><includeonly>subst:#titleparts:{{</includeonly><includeonly>subst:FULLPAGENAME}}||-3}}}}||{{red|　　'''錯誤警告：提交日期不在当天！'''}}请删除本提交，并重新提交{{NewAfdLink}}。}}
{{</includeonly><includeonly>subst:#if:{{{DRarticles|}}}|===[[{{{DRarticles}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{DRarticles}}}}}}}}}
{{{C0|}}}
{{</includeonly><includeonly>subst:#if:{{{1|}}}|===[[{{{1}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{1}}}}}}}}}
{{{C1|}}}
{{</includeonly><includeonly>subst:#if:{{{2|}}}|===[[{{{2}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{2}}}}}}}}}
{{{C2|}}}
{{</includeonly><includeonly>subst:#if:{{{3|}}}|===[[{{{3}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{3}}}}}}}}}
{{{C3|}}}
{{</includeonly><includeonly>subst:#if:{{{4|}}}|===[[{{{4}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{4}}}}}}}}}
{{{C4|}}}
{{</includeonly><includeonly>subst:#if:{{{5|}}}|===[[{{{5}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{5}}}}}}}}}
{{{C5|}}}
{{</includeonly><includeonly>subst:#if:{{{6|}}}|===[[{{{6}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{6}}}}}}}}}
{{{C6|}}}
{{</includeonly><includeonly>subst:#if:{{{7|}}}|===[[{{{7}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{7}}}}}}}}}
{{{C7|}}}
{{</includeonly><includeonly>subst:#if:{{{8|}}}|===[[{{{8}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{8}}}}}}}}}
{{{C8|}}}
{{</includeonly><includeonly>subst:#if:{{{9|}}}|===[[{{{9}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{9}}}}}}}}}
{{{C9|}}}
{{</includeonly><includeonly>subst:#if:{{{10|}}}|===[[{{{10}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{10}}}}}}}}}
{{{C10|}}}
{{</includeonly><includeonly>subst:#if:{{{11|}}}|===[[{{{11}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{11}}}}}}}}}
{{{C11|}}}
{{</includeonly><includeonly>subst:#if:{{{12|}}}|===[[{{{12}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{12}}}}}}}}}
{{{C12|}}}
{{</includeonly><includeonly>subst:#if:{{{13|}}}|===[[{{{13}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{13}}}}}}}}}
{{{C13|}}}
{{</includeonly><includeonly>subst:#if:{{{14|}}}|===[[{{{14}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{14}}}}}}}}}
{{{C14|}}}
{{</includeonly><includeonly>subst:#if:{{{15|}}}|===[[{{{15}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{15}}}}}}}}}
{{{C15|}}}
{{</includeonly><includeonly>subst:#if:{{{16|}}}|===[[{{{16}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{16}}}}}}}}}
{{{C16|}}}
{{</includeonly><includeonly>subst:#if:{{{17|}}}|===[[{{{17}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{17}}}}}}}}}
{{{C17|}}}
{{</includeonly><includeonly>subst:#if:{{{18|}}}|===[[{{{18}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{18}}}}}}}}}
{{{C18|}}}
{{</includeonly><includeonly>subst:#if:{{{19|}}}|===[[{{{19}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{19}}}}}}}}}
{{{C19|}}}
{{</includeonly><includeonly>subst:#if:{{{20|}}}|===[[{{{20}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{20}}}}}}}}}
{{{C20|}}}
{{</includeonly><includeonly>subst:#if:{{{21|}}}|===[[{{{21}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{21}}}}}}}}}
{{{C21|}}}
{{</includeonly><includeonly>subst:#if:{{{22|}}}|===[[{{{22}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{22}}}}}}}}}
{{{C22|}}}
{{</includeonly><includeonly>subst:#if:{{{23|}}}|===[[{{{23}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{23}}}}}}}}}
{{{C23|}}}
{{</includeonly><includeonly>subst:#if:{{{24|}}}|===[[{{{24}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{24}}}}}}}}}
{{{C24|}}}
{{</includeonly><includeonly>subst:#if:{{{25|}}}|===[[{{{25}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{25}}}}}}}}}
{{{C25|}}}
{{</includeonly><includeonly>subst:#if:{{{26|}}}|===[[{{{26}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{26}}}}}}}}}
{{{C26|}}}
{{</includeonly><includeonly>subst:#if:{{{27|}}}|===[[{{{27}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{27}}}}}}}}}
{{{C27|}}}
{{</includeonly><includeonly>subst:#if:{{{28|}}}|===[[{{{28}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{28}}}}}}}}}
{{{C28|}}}
{{</includeonly><includeonly>subst:#if:{{{29|}}}|===[[{{{29}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{29}}}}}}}}}
{{{C29|}}}
{{</includeonly><includeonly>subst:#if:{{{30|}}}|===[[{{{30}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{30}}}}}}}}}
{{{C30|}}}
{{</includeonly><includeonly>subst:#if:{{{31|}}}|===[[{{{31}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{31}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{32|}}}|===[[{{{32}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{32}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{33|}}}|===[[{{{33}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{33}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{34|}}}|===[[{{{34}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{34}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{35|}}}|===[[{{{35}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{35}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{36|}}}|===[[{{{36}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{36}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{37|}}}|===[[{{{37}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{37}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{38|}}}|===[[{{{38}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{38}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{39|}}}|===[[{{{39}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{39}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{40|}}}|===[[{{{40}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{40}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{41|}}}|===[[{{{41}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{41}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{42|}}}|===[[{{{42}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{42}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{43|}}}|===[[{{{43}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{43}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{44|}}}|===[[{{{44}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{44}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{45|}}}|===[[{{{45}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{45}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{46|}}}|===[[{{{46}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{46}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{47|}}}|===[[{{{47}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{47}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{48|}}}|===[[{{{48}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{48}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{49|}}}|===[[{{{49}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{49}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{50|}}}|===[[{{{50}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{50}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{51|}}}|===[[{{{51}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{51}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{52|}}}|===[[{{{52}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{52}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{53|}}}|===[[{{{53}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{53}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{54|}}}|===[[{{{54}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{54}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{55|}}}|===[[{{{55}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{55}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{56|}}}|===[[{{{56}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{56}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{57|}}}|===[[{{{57}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{57}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{58|}}}|===[[{{{58}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{58}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{59|}}}|===[[{{{59}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{59}}}}}}}}}
{{</includeonly><includeonly>subst:#if:{{{60|}}}|===[[{{{60}}}]]===
{{</includeonly><includeonly>subst:#switch:{{</includeonly><includeonly>subst:LC:{{{Type|d}}}}}|fame|知名度|關注度|关注度={{Findsources|{{{60}}}}}}}}}
}}
----
:'''{{删除}}理據：关注度模板已悬挂30日，经Google检索缺乏[[WP:N]]要求的可靠来源报导，且未有人在条目内补充可靠来源。'''--{{{sign|}}}
:<center><small>帮助：[[WP:N|关注度相关指引]]{{.w}}[[WP:NFAQ|常见问题与误区]]{{.w}}[[WP:DP|删除方针]]</small></center>
*{{补充}}：其他仍然存在但已挂模板30天的未提删条目还有：{{subst:#if:{{{RV1|}}}|[[{{{RV1}}}]]（已改写）、}}{{subst:#if:{{{RV2|}}}|[[{{{RV2}}}]]（已改写）、}}{{subst:#if:{{{RV3|}}}|、[[{{{RV3}}}]]（已改写）、}}{{subst:#if:{{{N1|}}}|[[{{{N1}}}]]}}{{subst:#if:{{{N2|}}}|、[[{{{N2}}}]]}}{{subst:#if:{{{N3|}}}|、[[{{{N3}}}]]}}{{subst:#if:{{{N4|}}}|、[[{{{N4}}}]]}}{{subst:#if:{{{N5|}}}|、[[{{{N5}}}]]}}{{subst:#if:{{{N6|}}}|、[[{{{N6}}}]]}}{{subst:#if:{{{N7|}}}|、[[{{{N7}}}]]}}{{subst:#if:{{{N8|}}}|、[[{{{N8}}}]]}}{{subst:#if:{{{N9|}}}|、[[{{{N9}}}]]}}{{subst:#if:{{{N10|}}}|、[[{{{N10}}}]]}}{{subst:#if:{{{N11|}}}|、[[{{{N11}}}]]}}{{subst:#if:{{{N12|}}}|、[[{{{N12}}}]]}}{{subst:#if:{{{N13|}}}|、[[{{{N13}}}]]}}{{subst:#if:{{{N14|}}}|、[[{{{N14}}}]]}}{{subst:#if:{{{N15|}}}|、[[{{{N15}}}]]}}。如有自动确认用户以上编者认定该条目不符合[[WP:N]]所述要求，可自行提删。{{subst:#if:{{{DP1|}}}|此外[[{{{DP1}}}]]已于'''[[WP:页面存废讨论/记录/{{{year}}}/{{{DP1date}}}#{{{DP1}}}|{{{DP1date}}}提删]]'''，}}{{subst:#if:{{{DP2|}}}|[[{{{DP2}}}]]已于'''[[WP:页面存废讨论/记录/{{{year}}}/{{{DP2date}}}#{{{DP2}}}|{{{DP2date}}}提删]]'''，}}{{subst:#if:{{{DP3|}}}|[[{{{DP3}}}]]已于'''[[WP:页面存废讨论/记录/{{{year}}}/{{{DP3date}}}#{{{DP3}}}|{{{DP3date}}}提删]]'''，}}{{subst:#if:{{{DP4|}}}|[[{{{DP4}}}]]已于'''[[WP:页面存废讨论/记录/{{{year}}}/{{{DP4date}}}#{{{DP4}}}|{{{DP4date}}}提删]]'''，}}{{subst:#if:{{{DP1|}}}|欢迎各位编者前往讨论。}}--{{{sign|}}}</includeonly><noinclude>
本模板用于关注度到期条目的提删。另有一个改进版本[[Template:DRItem/fame/2]]。{{doc}}
[[Category:预定义模板|{{PAGENAME}}]]
</noinclude>