{{#switch:{{{1}}}|
<!--Season 1-->
 Emissary = [[使者 (DS9)|使者]]|
 Past Prologue = [[往事再临 (DS9)|往事再临]]|
 A Man Alone = [[A Man Alone (DS9)|A Man Alone]]|
 Babel = [[Babel (DS9)|Babel]]|
 Captive Pursuit = [[Captive Pursuit (DS9)|Captive Pursuit]]|
 Q-Less = [[Q-Less (DS9)|Q-Less]]|
 Dax = [[Dax (DS9)|Dax]]|
 The Passenger = [[The Passenger (DS9)|The Passenger]]|
 Move Along Home = [[Move Along Home (DS9)|Move Along Home]]|
 The Nagus = [[The Nagus (DS9)|The Nagus]]|
 Vortex = [[Vortex (DS9)|Vortex]]|
 Battle Lines = [[Battle Lines (DS9)|Battle Lines]]|
 The Storyteller = [[The Storyteller (DS9)|The Storyteller]]|
 Progress = [[Progress (DS9)|Progress]]|
 If Wishes Were Horses = [[If Wishes Were Horses (DS9)|If Wishes Were Horses]]|
 The Forsaken = [[The Forsaken (DS9)|The Forsaken]]|
 Dramatis Personae = [[Dramatis Personae (DS9)|Dramatis Personae]]|
 Duet = [[Duet (DS9)|Duet]]|
 In the Hands of the Prophets = [[In the Hands of the Prophets (DS9)|In the Hands of the Prophets]]|
<!--Season 2-->
| The Homecoming = [[The Homecoming (DS9)|The Homecoming]]
| The Circle = [[The Circle (DS9)|The Circle]]
| The Siege = [[The Siege (DS9)|The Siege]]
| Invasive Procedures = [[Invasive Procedures (DS9)|Invasive Procedures]]
| Cardassians = [[Cardassians (DS9)|Cardassians]]
| Melora = [[Melora (DS9)|Melora]]
| Rules of Acquisition = [[Rules of Acquisition (DS9)|Rules of Acquisition]]
| Necessary Evil = [[Necessary Evil (DS9)|Necessary Evil]]
| Second Sight = [[Second Sight (DS9)|Second Sight]]
| Sanctuary = [[Sanctuary (DS9)|Sanctuary]]
| Rivals = [[Rivals (DS9)|Rivals]]
| The Alternate = [[The Alternate (DS9)|The Alternate]]
| Armageddon Game = [[Armageddon Game (DS9)|Armageddon Game]]
| Whispers = [[Whispers (DS9)|Whispers]]
| Paradise = [[Paradise (DS9)|Paradise]]
| Shadowplay = [[Shadowplay (DS9)|Shadowplay]]
| Playing God = [[Playing God (DS9)|Playing God]]
| Profit and Loss = [[Profit and Loss (DS9)|Profit and Loss]]
| Blood Oath = [[Blood Oath (DS9)|Blood Oath]]
| The Maquis, Part I = [[The Maquis, Part I (DS9)|The Maquis, Part I]]
| The Maquis, Part II = [[The Maquis, Part II (DS9)|The Maquis, Part II]]
| The Wire = [[The Wire (DS9)|The Wire]]
| Crossover = [[交叉路口 (DS9)|交叉路口]]
| The Collaborator = [[The Collaborator (DS9)|The Collaborator]]
| Tribunal = [[Tribunal (DS9)|Tribunal]]
| The Jem'Hadar = [[The Jem'Hadar (DS9)|The Jem'Hadar]]
<!--Season 3-->
 The Search = [[:en:The Search (DS9 episode)|The Search]]|
 The House of Quark = [[The House of Quark (DS9)|The House of Quark]]|
 Equilibrium = [[Equilibrium (DS9)|Equilibrium]]|
 Second Skin = [[Second Skin (DS9)|Second Skin]]|
 The Abandoned = [[The Abandoned (DS9)|The Abandoned]]|
 Civil Defense = [[Civil Defense (DS9)|Civil Defense]]|
 Meridian = [[Meridian (DS9)|Meridian]]|
 Defiant = [[Defiant (DS9)|Defiant]]|
 Fascination = [[Fascination (DS9)|Fascination]]|
 Past Tense, Part I = [[Past Tense, Part I (DS9)|Past Tense, Part I]]|
 Past Tense, Part II = [[Past Tense, Part II (DS9)|Past Tense, Part II]]|
 Life Support = [[Life Support (DS9)|Life Support]]|
 Heart of Stone = [[Heart of Stone (DS9)|Heart of Stone]]|
 Destiny = [[Destiny (DS9)|Destiny]]|
 Prophet Motive = [[Prophet Motive (DS9)|Prophet Motive]]|
 Visionary = [[Visionary (DS9)|Visionary]]|
 Distant Voices = [[Distant Voices (DS9)|Distant Voices]]|
 Through the Looking Glass = [[Through the Looking Glass (DS9)|Through the Looking Glass]]|
 Improbable Cause = [[Improbable Cause (DS9)|Improbable Cause]]|
 The Die is Cast = [[The Die is Cast (DS9)|The Die is Cast]]|
 Explorers = [[Explorers (DS9)|Explorers]]|
 Family Business = [[Family Business (DS9)|Family Business]]|
 Shakaar = [[Shakaar (DS9)|Shakaar]]|
 Facets = [[Facets (DS9)|Facets]]|
 The Adversary = [[The Adversary (DS9)|The Adversary]]|
<!--Season 4-->
 The Way of the Warrior = [[The Way of the Warrior (DS9)|The Way of the Warrior]]|
 The Visitor = [[The Visitor (DS9)|The Visitor]]|
 Hippocratic Oath = [[Hippocratic Oath (DS9)|Hippocratic Oath]]|
 Indiscretion = [[Indiscretion (DS9)|Indiscretion]]|
 Rejoined = [[Rejoined (DS9)|Rejoined]]|
 Starship Down = [[Starship Down (DS9)|Starship Down]]|
 Little Green Men = [[Little Green Men (DS9)|Little Green Men]]|
 The Sword of Kahless = [[The Sword of Kahless (DS9)|The Sword of Kahless]]|
 Our Man Bashir = [[Our Man Bashir (DS9)|Our Man Bashir]]|
 Homefront = [[Homefront (DS9)|Homefront]]|
 Paradise Lost = [[Paradise Lost (DS9)|Paradise Lost]]|
 Crossfire = [[Crossfire (DS9)|Crossfire]]|
 Return to Grace = [[Return to Grace (DS9)|Return to Grace]]|
 Sons of Mogh = [[Sons of Mogh (DS9)|Sons of Mogh]]|
 Bar Association = [[Bar Association (DS9)|Bar Association]]|
 Accession = [[Accession (DS9)|Accession]]|
 Rules of Engagement = [[Rules of Engagement (DS9)|Rules of Engagement]]|
 Hard Time = [[Hard Time (DS9)|Hard Time]]|
 Shattered Mirror = [[Shattered Mirror (DS9)|Shattered Mirror]]|
 The Muse = [[The Muse (DS9)|The Muse]]|
 For the Cause = [[For the Cause (DS9)|For the Cause]]|
 To the Death = [[To the Death (DS9)|To the Death]]|
 The Quickening = [[The Quickening (DS9)|The Quickening]]|
 Body Parts = [[Body Parts (DS9)|Body Parts]]|
 Broken Link = [[Broken Link (DS9)|Broken Link]]|
<!--Season 5-->
 Apocalypse Rising = [[Apocalypse Rising (DS9)|Apocalypse Rising]]|
 The Ship = [[The Ship (DS9)|The Ship]]|
 Looking for par'Mach in All the Wrong Places = [[Looking for par'Mach in All the Wrong Places (DS9)|Looking for par'Mach in All the Wrong Places]]|
 ...Nor the Battle to the Strong = [[...Nor the Battle to the Strong (DS9)|...Nor the Battle to the Strong]]|
 The Assignment = [[The Assignment (DS9)|The Assignment]]|
 Trials and Tribble-ations = [[Trials and Tribble-ations (DS9)|Trials and Tribble-ations]]|
 Let He Who Is Without Sin... = [[Let He Who Is Without Sin... (DS9)|Let He Who Is Without Sin...]]|
 Things Past = [[Things Past (DS9)|Things Past]]|
 The Ascent = [[The Ascent (DS9)|The Ascent]]|
 Rapture = [[Rapture (DS9)|Rapture]]|
 The Darkness and the Light = [[The Darkness and the Light (DS9)|The Darkness and the Light]]|
 The Begotten = [[The Begotten (DS9)|The Begotten]]|
 For the Uniform = [[For the Uniform (DS9)|For the Uniform]]|
 In Purgatory's Shadow = [[In Purgatory's Shadow (DS9)|In Purgatory's Shadow]]|
 By Inferno's Light = [[By Inferno's Light (DS9)|By Inferno's Light]]|
 Doctor Bashir, I Presume = [[Doctor Bashir, I Presume (DS9)|Doctor Bashir, I Presume]]|
 A Simple Investigation = [[A Simple Investigation (DS9)|A Simple Investigation]]|
 Business as Usual = [[Business as Usual (DS9)|Business as Usual]]|
 Ties of Blood and Water = [[Ties of Blood and Water (DS9)|Ties of Blood and Water]]|
 Ferengi Love Songs = [[Ferengi Love Songs (DS9)|Ferengi Love Songs]]|
 Soldiers of the Empire = [[Soldiers of the Empire (DS9)|Soldiers of the Empire]]|
 Children of Time = [[Children of Time (DS9)|Children of Time]]|
 Blaze of Glory = [[Blaze of Glory (DS9)|Blaze of Glory]]|
 Empok Nor = [[Empok Nor (DS9)|Empok Nor]]|
 In the Cards = [[In the Cards (DS9)|In the Cards]]|
 Call to Arms = [[Call to Arms (DS9)|Call to Arms]]|
<!-- Season 6 -->
  A Time to Stand = [[A Time to Stand (DS9)|A Time to Stand]]|
 Rocks and Shoals = [[Rocks and Shoals (DS9)|Rocks and Shoals]]|
 Sons and Daughters = [[Sons and Daughters (DS9)|Sons and Daughters]]|
 Behind the Lines = [[Behind the Lines (DS9)|Behind the Lines]]|
 Favor the Bold = [[Favor the Bold (DS9)|Favor the Bold]]|
 Sacrifice of Angels = [[Sacrifice of Angels (DS9)|Sacrifice of Angels]]|
 You Are Cordially Invited = [[You Are Cordially Invited (DS9)|You Are Cordially Invited]]|
 Resurrection = [[Resurrection (DS9)|Resurrection]]|
 Statistical Probabilities = [[Statistical Probabilities (DS9)|Statistical Probabilities]]|
 The Magnificent Ferengi = [[The Magnificent Ferengi (DS9)|The Magnificent Ferengi]]|
 Waltz = [[Waltz (DS9)|Waltz]]|
 Who Mourns for Morn? = [[Who Mourns for Morn? (DS9)|Who Mourns for Morn?]]|
 Far Beyond the Stars = [[Far Beyond the Stars (DS9)|Far Beyond the Stars]]|
 One Little Ship = [[One Little Ship (DS9)|One Little Ship]]|
 Honor Among Thieves = [[Honor Among Thieves (DS9)|Honor Among Thieves]]|
 Change of Heart = [[Change of Heart (DS9)|Change of Heart]]|
 Wrongs Darker Than Death or Night = [[Wrongs Darker Than Death or Night (DS9)|Wrongs Darker Than Death or Night]]|
 Inquisition = [[Inquisition (DS9)|Inquisition]]|
 In the Pale Moonlight = [[In the Pale Moonlight (DS9)|In the Pale Moonlight]]|
 His Way = [[His Way (DS9)|His Way]]|
 The Reckoning = [[The Reckoning (DS9)|The Reckoning]]|
 Valiant = [[Valiant (DS9)|Valiant]]|
 Profit and Lace = [[Profit and Lace (DS9)|Profit and Lace]]|
 Time's Orphan = [[Time's Orphan (DS9)|Time's Orphan]]|
 The Sound of Her Voice = [[The Sound of Her Voice (DS9)|The Sound of Her Voice]]|
 Tears of the Prophets = [[Tears of the Prophets (DS9)|Tears of the Prophets]]|
<!-- Season 7 -->
 Image in the Sand = [[Image in the Sand (DS9)|Image in the Sand]]|
 Shadows and Symbols = [[Shadows and Symbols (DS9)|Shadows and Symbols]]|
 Afterimage = [[Afterimage (DS9)|Afterimage]]|
 Take Me Out to the Holosuite = [[Take Me Out to the Holosuite (DS9)|Take Me Out to the Holosuite]]|
 Chrysalis = [[Chrysalis (DS9)|Chrysalis]]|
 Treachery, Faith and the Great River = [[Treachery, Faith and the Great River (DS9)|Treachery, Faith and the Great River]]|
 Once More Unto the Breach = [[Once More Unto the Breach (DS9)|Once More Unto the Breach]]|
 The Siege of AR-558 = [[The Siege of AR-558 (DS9)|The Siege of AR-558]]|
 Covenant = [[Covenant (DS9)|Covenant]]|
 It's Only a Paper Moon = [[It's Only a Paper Moon (DS9)|It's Only a Paper Moon]]|
 Prodigal Daughter = [[Prodigal Daughter (DS9)|Prodigal Daughter]]|
 The Emperor's New Cloak = [[The Emperor's New Cloak (DS9)|The Emperor's New Cloak]]|
 Field of Fire = [[Field of Fire (DS9)|Field of Fire]]|
 Chimera = [[Chimera (DS9)|Chimera]]|
 Badda-Bing, Badda-Bang = [[Badda-Bing, Badda-Bang (DS9)|Badda-Bing, Badda-Bang]]|
 Inter Arma Enim Silent Leges = [[Inter Arma Enim Silent Leges (DS9)|Inter Arma Enim Silent Leges]]|
 Penumbra = [[Penumbra (DS9)|Penumbra]]|
 'Til Death Do Us Part = [['Til Death Do Us Part (DS9)|'Til Death Do Us Part]]|
 Strange Bedfellows = [[Strange Bedfellows (DS9)|Strange Bedfellows]]|
 The Changing Face of Evil = [[The Changing Face of Evil (DS9)|The Changing Face of Evil]]|
 When It Rains... = [[When It Rains... (DS9)|When It Rains...]]|
 Tacking Into the Wind = [[Tacking Into the Wind (DS9)|Tacking Into the Wind]]|
 Extreme Measures = [[Extreme Measures (DS9)|Extreme Measures]]|
 The Dogs of War = [[The Dogs of War (DS9)|The Dogs of War]]|
 What You Leave Behind = [[What You Leave Behind (DS9)|What You Leave Behind]]}}<noinclude>
[[Category:星际旅行模板]]

{{NoteTA|G1=StarTrek}}
</noinclude>