{| align=right  id=toc style="width:150px"
|- style="background:#ccccff"
|colspan="12" align="center" bgcolor="#ccccff"|'''[[干支]]'''
|- style="text-align:center;" style="font-size:85%;line-height:1em;height:2.5em"
|[[甲子]]
|[[乙丑]]
|[[丙寅]]
|[[丁卯]]
|[[戊辰]]
|[[己巳]]
|[[庚午]]
|[[辛未]]
|[[壬申]]
|[[癸酉]]
|[[甲戌]]
|[[乙亥]]
|- style="background:#ccccff; text-align:center;" style="font-size:85%;line-height:1em;height:2.5em"
|[[丙子]]
|[[丁丑]]
|[[戊寅]]
|[[己卯]]
|[[庚辰]]
|[[辛巳]]
|[[壬午]]
|[[癸未]]
|[[甲申]]
|[[乙酉]]
|[[丙戌]]
|[[丁亥]]
|- style="text-align:center;" style="font-size:85%;line-height:1em;height:2.5em"
|[[戊子]]
|[[己丑]]
|[[庚寅]]
|[[辛卯]]
|[[壬辰]]
|[[癸巳]]
|[[甲午]]
|[[乙未]]
|[[丙申]]
|[[丁酉]]
|[[戊戌]]
|[[己亥]]
|- style="background:#ccccff; text-align:center;" style="font-size:85%;line-height:1em;height:2.5em"
|[[庚子]]
|[[辛丑]]
|[[壬寅]]
|[[癸卯]]
|[[甲辰]]
|[[乙巳]]
|[[丙午]]
|[[丁未]]
|[[戊申]]
|[[己酉]]
|[[庚戌]]
|[[辛亥]]
|- style="text-align:center;" style="font-size:85%;line-height:1em;height:2.5em"
|[[壬子]]
|[[癸丑]]
|[[甲寅]]
|[[乙卯]]
|[[丙辰]]
|[[丁巳]]
|[[戊午]]
|[[己未]]
|[[庚申]]
|[[辛酉]]
|[[壬戌]]
|[[癸亥]]
|-
|}<noinclude>
[[Category:时间模板]]
[[Category:文化模板]]
</noinclude>