[[File:Soccerball shade.svg|13px|入球|link=]] <!--
-->{{#if: {{{1<includeonly>|</includeonly>}}}| <span style="font-size:10px; vertical-align:middle">{{{1}}}'{{#if: {{{2|}}}|{{#switch: {{{2|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{2}}}）}}}}</span>}}<!--
-->{{#if: {{{3<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{3}}}'{{#if: {{{4|}}}|{{#switch: {{{4|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{4}}}）}}}}</span>}}<!--
-->{{#if: {{{5<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{5}}}'{{#if: {{{6|}}}|{{#switch: {{{6|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{6}}}）}}}}</span>}}<!--
-->{{#if: {{{7<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{7}}}'{{#if: {{{8|}}}|{{#switch: {{{8|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{8}}}）}}}}</span>}}<!--
-->{{#if: {{{9<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{9}}}'{{#if: {{{10|}}}|{{#switch: {{{10|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{10}}}）}}}}</span>}}<!--
-->{{#if: {{{11<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{11}}}'{{#if: {{{12|}}}|{{#switch: {{{12|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{12}}}）}}}}</span>}}<!--
-->{{#if: {{{13<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{13}}}'{{#if: {{{14|}}}|{{#switch: {{{14|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{14}}}）}}}}</span>}}<!--
-->{{#if: {{{15<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{15}}}'{{#if: {{{16|}}}|{{#switch: {{{16|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{16}}}）}}}}</span>}}<!--
-->{{#if: {{{17<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{17}}}'{{#if: {{{18|}}}|{{#switch: {{{18|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[烏龍球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{18}}}）}}}}</span>}}<!--
-->{{#if: {{{19<includeonly>|</includeonly>}}}|, <span style="font-size:10px; vertical-align:middle">{{{19}}}'{{#if: {{{20|}}}|{{#switch: {{{20|}}}| o.g. =（[[乌龙球]]）|pen. =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）|og =（[[乌龙球]]）|p =（[[罚点球|-{zh-tw:十二碼;zh-hans:点球;zh-hk:十二碼;}-]]）| #default =（{{{20}}}）}}}}</span>}}<noinclude>
{{doc}}
[[Category:足球模板]]
</noinclude>