{{#switch:{{#if:{{{centimeter|{{{centimeters|{{{centimetre|{{{centimetres|{{{cm|}}}}}}}}}}}}}}}|1|0}}{{#if:{{{meter|{{{meters|{{{metre|{{{metres|{{{m|}}}}}}}}}}}}}}}|1|0}}{{#if:{{{foot|{{{feet|{{{ft|}}}}}}}}}|1|0}}{{#if:{{{inch|{{{inches|{{{in|}}}}}}}}}|1|0}}{{#if:{{{chi|}}}|1|0}}{{#if:{{{cun|}}}|1|0}}
|100000=-{zh-hans:{{convert|{{{centimeter|{{{centimeters|{{{centimetre|{{{centimetres|{{{cm|}}}}}}}}}}}}}}}|cm|ftin|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};zh-hant:{{convert|{{{centimeter|{{{centimeters|{{{centimetre|{{{centimetres|{{{cm|}}}}}}}}}}}}}}}|cm|ftin|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};zh-cn:{{convert|{{{centimeter|{{{centimeters|{{{centimetre|{{{centimetres|{{{cm|}}}}}}}}}}}}}}}|cm|chicun|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};}-
|010000=-{zh-hans:{{convert|{{{meter|{{{meters|{{{metre|{{{metres|{{{m}}}}}}}}}}}}}}}|m|ftin|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};zh-hant:{{convert|{{{meter|{{{meters|{{{metre|{{{metres|{{{m}}}}}}}}}}}}}}}|m|ftin|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};zh-cn:{{convert|{{{meter|{{{meters|{{{metre|{{{metres|{{{m}}}}}}}}}}}}}}}|m|chicun|frac={{#ifeq:{{{precision}}}|0|1|{{{frac|2}}}}}|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{{precision|1}}} }};}-
|001100={{convert|{{{foot|{{{feet|{{{ft|}}}}}}}}}|ft|{{{inch|{{{inches|{{{in|}}}}}}}}}|in|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|001000={{convert|{{{foot|{{{feet|{{{ft|}}}}}}}}}|ft|0|in|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|000100={{convert|0|ft|{{{inch|{{{inches|{{{in|}}}}}}}}}|in|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|000011={{convert|{{{chi|}}}|chi|{{{cun|}}}|cun|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|000010={{convert|{{{chi|}}}|chi|0|cun|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|000001={{convert|0|chi|{{{cun|}}}|cun|m|abbr={{#switch:{{{abbr}}}|yes=on|mos=def|#default=off}}|lk={{#ifeq:{{{wiki|}}}|yes|on|off}}|{{#if:{{{precision|}}}|{{{precision}}}|2}} }}
|000000=
|#default={{Error|错误：请仅指定公制、仅指定英制或仅指定市制单位}}
}}<noinclude>
{{Documentation}}
<!-- Add categories and interwikis to the /doc subpage, not here! -->
</noinclude>