{{Infobox settlement
| name                    = {{{name|{{PAGENAME}}}}}
| official_name           = {{{official_name|}}}
| native_name             = {{#if:{{{other_lang_name|}}}|{{#if:{{{other_lang|}}}|{{{other_lang|}}}：}}{{{other_lang_name|}}}}}{{#if:{{{other_lang2_name|}}}|<br>{{#if:{{{other_lang2|}}}|{{{other_lang2|}}}：}}{{{other_lang2_name|}}}}}{{#if:{{{other_lang3_name|}}}|<br>{{#if:{{{other_lang3|}}}|{{{other_lang3|}}}：}}{{{other_lang3_name|}}}}}
| other_name              = {{{shortname|}}}
| settlement_type         = {{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|3}}|自治州|[[自治州]]|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地区|[[地区行政公署|地区]]|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地區|[[地区行政公署|地区]]|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|1}}|盟|[[盟 (行政區劃)|盟]]|[[地级市]]}}}}}}}}
| image_skyline           = {{{image_city|}}}
| image_size              = {{{image_size|{{{imagesize|}}}}}}
| image_caption           = {{{image_caption|}}}
| image_flag              = {{{image_flag|}}}
| flag_size               = {{{flag_size|}}}
| flag_alt                = {{{flag_alt|}}}
| flag_border             = {{{flag_border|}}}
| flag_link               = {{{flag_link|}}}
| flag_type               = {{{flag_type|}}}
| image_seal              = {{{image_seal|}}}
| seal_size               = {{{seal_size|}}}
| seal_alt                = {{{seal_alt|}}}
| seal_link               = {{{seal_link|}}}
| seal_type               = {{{seal_type|}}}
| image_shield            = {{{image_shield|}}}
| shield_size             = {{{shield_size|}}}
| shield_alt              = {{{shield_alt|}}}
| shield_link             = {{{shield_link|}}}
| shield_type             = {{{shield_type|}}}
| image_blank_emblem      = {{{image_emblem|}}}
| blank_emblem_type       = {{{emblem_type|}}}
| blank_emblem_size       = {{{emblem_size|}}}
| blank_emblem_alt        = {{{emblem_alt|}}}
| blank_emblem_link       = {{{emblem_link|}}}
| nickname                = {{{nickname|}}}
| image_map               = {{{image_map|}}}
| map_caption             = {{{map_caption|圖中高亮顯示的是{{{name|{{PAGENAME}}}}}}}}
| image_map1              = {{{image_map1|}}}
| map_caption1            = {{{map_caption1|}}}
| coordinates             = {{{coordinates|{{{coordinate|}}}}}}{{#if:{{{latd|}}}{{{latm|}}}{{{lats|}}}{{{latNS|}}}{{{longd|}}}{{{longm|}}}{{{longs|}}}{{{longEW|}}}|{{coord|{{{latd}}}|{{{latm}}}|{{{lats|0}}}|{{{latNS}}}|{{{longd}}}|{{{longm}}}|{{{longs|0}}}|{{{longEW}}}}}}}
| subdivision_type        = [[世界政區索引|国家]]
| subdivision_name        = {{PRC}}
| subdivision_type1       = {{#if:{{{subdivision_name1|}}}|[[中华人民共和国行政区划#省级行政区|{{#ifeq:{{str rightmost|{{Delink|{{{subdivision_name1|}}}}}|3}}|自治区|自治區|{{#ifeq:{{str rightmost|{{Delink|{{{subdivision_name1|}}}}}|3}}|自治區|自治區|{{str rightmost|{{Delink|{{{subdivision_name1|}}}}}|1}}}}}}]]}}
| subdivision_name1       = {{{subdivision_name1|}}}
| subdivision_type2       = [[自治州]]
| subdivision_name2       = {{#ifeq:{{PAGENAME}}|塔城地区|[[伊犁哈萨克自治州]]|{{#ifeq:{{PAGENAME}}|阿勒泰地区|[[伊犁哈萨克自治州]]|{{#ifeq:{{PAGENAME}}|伊犁地区|[[伊犁哈萨克自治州]]|}}}}}}
| established_title       = 設立
| established_date        = {{{established_date|}}}
| extinct_title           = 撤銷
| extinct_date            = {{{dissolved_date|}}}
| named_for               = {{{nameorigin|}}}
| seat_type               = 政府駐地
| seat                    = {{{location|}}}
| seat1_type              = 城市中心
| seat1                   = {{{city_center|}}}
| parts_type              = [[县级行政区|下级行政区]]
| parts_style             = coll
| parts                   = {{{divisions|}}}
| leader_title            = {{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|3}}|自治州|州委書記|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地区|地委書記|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地區|地委書記|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|1}}|盟|盟委書記|[[市委書記]]}}}}}}}}
| leader_name             = {{{leader_name|}}}
| leader_title1           = {{nowrap|人大常委會主任}}
| leader_name1            = {{{leader_name1|}}}
| leader_title2           = {{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|3}}|自治州|州長|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地区|地區專員|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地區|地區專員|{{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|1}}|盟|盟長|市長}}}}}}}}
| leader_name2            = {{{leader_name2|}}}
| leader_title3           = 政協主席
| leader_name3            = {{{leader_name3|}}}
| area_total_km2          = {{{area_total|}}}
| area_land_km2           = {{解析數字|{{{area_land|}}}}}
| area_water_km2          = {{解析數字|{{{area_water|}}}}}
| area_urban_km2          = {{解析數字|{{{area_urban|}}}}}
| area_metro_footnotes    = {{#if:{{{area_metropolitan_as_of|}}}|（{{{area_metropolitan_as_of}}}）}}
| area_metro_km2          = {{解析數字|{{{area_metropolitan|}}}}}
| area_rank               = {{#if:{{{area_total_rank|}}}|{{{area_total_rank|}}}（佔全{{{subdivision_name1|}}}{{{area_ratio|}}}%）}}
| area_blank1_title       = [[中华人民共和国城市建成区面积列表|建成区]]{{#if:{{{area_builtup_as_of|}}}|<span style="font-weight:normal">（{{{area_builtup_as_of|}}}）</span>}}
| area_blank1_km2         = {{解析數字|{{{area_builtup|}}}}}
| area_blank2_title       = [[城市群|都会区]]建成区{{#if:{{{area_metrobuilt_as_of|}}}|<span style="font-weight:normal">（{{{area_metrobuilt_as_of|}}}）</span>}}
| area_blank2_km2         = {{解析數字|{{{area_metrobuilt|}}}}}
| length_km               = {{解析數字|{{{length_NS|}}}}}
| width_km                = {{解析數字|{{{width_EW|}}}}}
| elevation_m             = {{解析數字|{{{elevation|}}}}}
| elevation_max_m         = {{解析數字|{{{elevation_max|}}}}}
| elevation_min_m         = {{解析數字|{{{elevation_min|}}}}}
| population_as_of        = {{{population_as_of|}}}
| population_total        = {{#if:{{{population_total|}}}|{{{population_total|}}}{{#if:{{{population_unit|}}}|{{{population_unit|}}}|萬人}}}}
| population_rank         = {{#if:{{{population_total_rank|}}}|{{{population_total_rank|}}}{{#if:{{{population_ratio|}}}|（佔全{{{subdivision_name1|}}}{{{population_ratio|}}}%}}）}}
| population_density_km2  = {{{population_density|}}}
| population_density_rank        = {{{population_density_rank|}}}
| population_urban_footnotes     = {{#if:{{{population_urban_as_of|}}}|（{{{population_urban_as_of|}}}）}}
| population_urban               = {{#if:{{{population_urban|}}}|{{{population_urban|}}}{{#if:{{{population_unit|}}}|{{{population_unit|}}}|萬人}}}}
| population_density_urban_km2   = {{{density_urban|}}}
| population_metro_footnotes     = {{#if:{{{population_metropolitan_as_of|}}}|（{{{population_metropolitan_as_of|}}}）}}
| population_metro               = {{#if:{{{population_metropolitan|}}}|{{{population_metropolitan|}}}{{#if:{{{population_unit|}}}|{{{population_unit|}}}|萬人}}}}
| population_density_metro_km2   = {{{density_metropolitan|}}}
| population_blank1_title        = [[中华人民共和国特大城市列表|城镇]]{{#if:{{{population_nonfarm_as_of|}}}|{{nobold|（{{{population_nonfarm_as_of|}}}）}}}}
| population_blank1              = {{#if:{{{population_nonfarm|}}}|{{{population_nonfarm|}}}{{#if:{{{population_unit|}}}|{{{population_unit|}}}|萬人}}}}
| population_blank2_title        = [[中華人民共和國城市城區人口排名|城區常住]]{{#if:{{{population_realurban_as_of|}}}|{{nobold|（{{{population_realurban_as_of|}}}）}}}}
| population_blank2              = {{#if:{{{population_realurban|}}}|{{{population_realurban|}}}{{#if:{{{population_unit|}}}|{{{population_unit|}}}|萬人}}}}
| demographics_type1      = {{#if:{{{Nationalities|}}}|民族}}
| demographics1_title1    = [[中國民族列表|主要民族]]
| demographics1_info1     = {{{Nationalities|}}}
| demographics_type2      = {{#if:{{{language|}}}{{{dialect|}}}|語言}}
| demographics2_title1    = 官方語言
| demographics2_info1     = {{{language|}}}
| demographics2_title2    = [[母语]]（[[中国语言列表|方言]]）
| demographics2_info2     = {{{dialect|}}}
| timezone1               = [[北京时间]]
| utc_offset1             = +8
| timezone2               = {{#ifeq:{{str left|{{Delink|{{{subdivision_name1|}}}}}|2}}|新疆|[[新疆時間]]}}
| utc_offset2             = {{#ifeq:{{str left|{{Delink|{{{subdivision_name1|}}}}}|2}}|新疆|+6}}
| postal_code_type        = [[中华人民共和国境内地区邮政编码列表|郵政編碼]]
| postal_code             = {{{postcode|}}}
| area_code_type          = [[中华人民共和国电话区号|電話區號]]
| area_code               = {{{areacode|}}}
| iso_code                = {{#if:{{{ISO3166|}}}|[[ISO 3166-2:CN|{{{ISO3166|}}}]]}}
| registration_plate_type = [[中华人民共和国民用机动车号牌|車輛號牌]]
| registration_plate      = {{{carlicense|}}}
| blank_name_sec1         = [[气候]]
| blank_info_sec1         = {{{climate|}}}
| blank1_name_sec1        = • [[温度|年均温]]{{#if:{{{temperature_as_of|}}}|（<span style="font-weight:normal">{{{temperature_as_of|}}}</span>）}}
| blank1_info_sec1        = {{#if:{{{temperature_mean|}}}|{{{temperature_mean|}}}&nbsp;℃}}
| blank2_name_sec1        = • [[降水量|年降水]]
| blank2_info_sec1        = {{#if:{{{precipitation|}}}|{{{precipitation|}}}毫米}}
| blank3_name_sec1        = • [[日照時數|年日照]]
| blank3_info_sec1        = {{#if:{{{sunshine_hours|}}}|{{{sunshine_hours|}}}小時}}
| blank4_name_sec1        = [[中华人民共和国行政区划代码|行政区划代码]]
| blank4_info_sec1        = {{{admini_division_code|{{wikidata|property|P442}}}}}
| blank5_name_sec1        = 舊稱
| blank5_info_sec1        = {{{usedname|}}}
| blank6_name_sec1        = 城市定位
| blank6_info_sec1        = {{{position|}}}
| blank7_name_sec1        = 城市稱號
| blank7_info_sec1        = {{{honor|}}}
| blank_name_sec2         = 城市口號
| blank_info_sec2         = {{{slogan|}}}
| blank1_name_sec2        = 城市精神
| blank1_info_sec2        = {{{spirit|}}}
| blank2_name_sec2        = [[国内生产总值|-{zh-cn:国内生产总值;zh-tw:國內生產毛額;zh-hk:本地生產總值;}-]]{{#if:{{{GDP_as_of|}}}|<span style="font-weight:normal">（{{{GDP_as_of|}}}）</span>}}
| blank2_info_sec2        = {{#if:{{{GDP|}}}|[[人民币|¥]]{{{GDP|}}}{{#if:{{{GDP_rank|}}}|（{{{GDP_rank}}}{{#if:{{{GDP_ratio|}}}|，佔全{{{subdivision_name1|}}}{{{GDP_ratio|}}}%}}）}}{{#if:{{{GDP_us|}}}|<br>{{{GDP_us|}}}[[美元]]（[[人民币汇率|汇率]]）}}{{#if:{{{GDP_PPP_us|}}}|<br>{{{GDP_PPP_us|}}}[[国际元]]（[[购买力平价|平价]]）}}}}
| blank3_name_sec2        = • [[人均国内生产总值|人均]]
| blank3_info_sec2        = {{#if:{{{GDPPC|}}}|¥{{{GDPPC|}}}{{#if:{{{GDPPC_rank|}}}|（{{{GDPPC_rank}}}）}}{{#if:{{{GDPPC_us|}}}|<br>{{{GDPPC_us|}}}[[美元]]（汇率）}}{{#if:{{{GDPPC_PPP_us|}}}|<br>{{{GDPPC_PPP_us|}}}[[國際元]]（平价）}}}}
| blank4_name_sec2        = • 市区
| blank4_info_sec2        = {{#if:{{{Urban_GDP|}}}|¥{{{Urban_GDP|}}}}}
| blank5_name_sec2        = • [[城市群|都会区]]
| blank5_info_sec2        = {{#if:{{{Metro_GDP|}}}|¥{{{Metro_GDP|}}}{{#if:{{{GDP_metro_us|}}}|<br>{{{GDP_metro_us|}}}[[美元]]（[[人民币汇率|汇率]]）}}{{#if:{{{GDP_metro_PPP_us|}}}|<br>{{{GDP_metro_PPP_us|}}}[[国际元]]（[[购买力平价|平价]]）}}}}
| blank6_name_sec2        = • 都會區人均
| blank6_info_sec2        = {{#if:{{{Metro_GDPPC|}}}|¥{{{Metro_GDPPC|}}}}}
| blank7_name_sec2        = [[人类发展指数|HDI]]{{#if:{{{HDI_as_of|}}}|<span style="font-weight:normal">（{{{HDI_as_of|}}}）</span>}}
| blank7_info_sec2        = {{{HDI|}}}
| website                 = {{{website|}}}
| footnotes               = {{#if:{{{dissolved_date|}}}|（本表所列数据截至{{{dissolved_date|}}}）}}{{#if:{{{tree|}}}{{{flower|}}}{{{song|}}}{{{animal_name|}}}|
    {{Infobox region symbols
    | embedded = yes
    | region   = {{#ifeq:{{str rightmost|{{{name|{{PAGENAME}}}}}|2}}|地区|地区|{{str rightmost|{{{name|{{PAGENAME}}}}}|1}}}}
    | tree     = {{{tree|}}}
    | flower   = {{{flower|}}}
    | song     = {{{song|}}}
    | animal   = {{{animal_name|}}}{{#if:{{{animal_title|}}}|（{{{animal_title|}}}）}}
    }}
}}{{{footnotes|}}}
}}<noinclude>{{doc}}</noinclude>