{{Infobox
| bodyclass   = geography vcard
| abovestyle  = text-align:center;font-size:110%; padding:5px; line-height:130%;
| belowstyle  = text-align: center; border-top: solid 1px #ccd2d9;
| headerstyle = background:lightsteelblue;
| subheaderstyle = background-color:#cddeff; font-weight:bold;
| above       = <span class="fn org">{{{county|{{{name<includeonly>|{{PAGENAME}}</includeonly>}}}}}}{{#if:{{{county2|{{{name2|}}}}}}|<br>{{{county2|{{{name2|}}}}}}}}</span>
| subheader       = {{#invoke:Wikidata|getValue|P31|{{{class|{{{Types<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}}}}
| image       = {{#if:{{{image_city|{{{Photo|}}}}}}|{{#invoke:InfoboxImage|InfoboxImage|image={{{image_city|{{{Photo|}}}}}}|size={{{imagesize|{{{Photo size|270}}}}}}px}}<br />{{#if:{{{image_caption|{{{Photoname|}}}}}}|<small>{{{image_caption|{{{Photoname}}}}}}</small>}}}}
| pushpin_map = China
| latd = {{{lat_deg|{{{latd|}}}}}}| latm = {{{lat_min|{{{latm|}}}}}}| lats = {{{lat_sec|{{{lats|}}}}}}| latNS = N
| longd= {{{lon_deg|{{{longd|}}}}}}| longm= {{{lon_min|{{{longm|}}}}}}| longs= {{{lon_sec|{{{longs|}}}}}}| longEW= E
| coordinates_type       = {{#if:{{{coordinates_type|}}}|{{{coordinates_type}}}|region:CN_type:city}}
| label1   = 简称
| class1   = nickname
| data1    = {{{shortname|{{{nickname<includeonly>|</includeonly>}}}}}}
| label2   = 别称
| class2   = nickname
| data2    = {{{Othername<includeonly>|</includeonly>}}}
| label3   = 旧称
| class3   = nickname
| data3    = {{{usedname|{{{Oldname<includeonly>|</includeonly>}}}}}}
| label4   = 地名出处
| data4    = {{{nameorigin<includeonly>|</includeonly>}}}
| data5    = {{#if:{{{image_map|{{{map<includeonly>|</includeonly>}}}}}}|{{#invoke:InfoboxImage|InfoboxImage|image={{{image_map|{{{map}}}}}}|size={{{mapsize|220px}}}}}<br>{{#if:{{{map_caption|}}}|{{{map_caption}}}|{{{name|{{{county}}}}}}的地理位置}}}}
| data6    = {{#if:{{{mapofstate<includeonly>|</includeonly>}}}|{{#invoke:InfoboxImage|InfoboxImage|image={{{mapofstate}}} |size=250px}}<br>{{{state}}}的地理位置}}
| data7    = {{#if:{{{customimage<includeonly>|</includeonly>}}}|{{{customimage|}}} }}<!--此行适合放置{{Location map}}等内容。-->
| header10 = 概览
| label11  = [[国家]]
| class11  = region
| data11   = {{{国家|{{PRC}}}}}
| label12  = {{#if:{{wikidata|property|P131|{{{subdivision_name1|{{{Belong<includeonly>|</includeonly>}}}}}}}} |{{nowrap|隶属行政区}}}}
| class12  = region
| data12   = {{#invoke:Wikidata|getValue|P131|{{{subdivision_name1|{{{Belong<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}} |{{{Belong|}}}{{{subdivision_name1|}}}{{{subdivision_name2|}}}}}
| label13  = [[县级行政区|区划类别]]
| data13   = {{#invoke:Wikidata|getValue|P31|{{{class|{{{Types<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}}}}
| label14  = {{#if:{{wikidata|property|P442|{{{admini_division_code|{{{admincode<includeonly>|</includeonly>}}}}}}}}|[[中华人民共和国行政区划代码|区划代码]]}}
| data14   = {{#if:{{wikidata|property|P442|{{{admini_division_code|{{{admincode<includeonly>|</includeonly>}}}}}}}}|{{str replace|{{wikidata|property|P442|{{{admini_division_code|{{{admincode|}}}}}}}}| |}}}}
| label15  = {{{established_title|建置时间}}}
| data15   = {{{established_date|{{{founded<includeonly>|</includeonly>}}}}}}
| label16  = {{{dissolved_title|撤销时间}}}
| data16   = {{{dissolved_date|{{{dissolved<includeonly>|</includeonly>}}}}}}
| label17  = 毗邻
| data17   = {{{neighbor<includeonly>|</includeonly>}}}
| label18  = '''政府驻地'''
| class18  = locality
| data18   = {{#invoke:Wikidata|getValue|P36|{{{location|{{{seat<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}}}}
| label19  = 现任{{{leader_title|{{{officerTitle|区长}}}}}}
| data19   = {{{leader_name|{{{officer<includeonly>|</includeonly>}}}}}}
| label20  = 现任{{{leader_title1|{{{officerTitle2|区长}}}}}}
| data20   = {{{leader_name1|{{{officer2<includeonly>|</includeonly>}}}}}}
| label21  = 现任{{{leader_title2|{{{officerTitle3|区长}}}}}}
| data21   = {{{leader_name2|{{{officer3<includeonly>|</includeonly>}}}}}}
| label22  = 现任{{{leader_title3|{{{officerTitle4|区长}}}}}}
| data22   = {{{leader_name3|{{{officer4<includeonly>|</includeonly>}}}}}}
| label23  = 现任{{{leader_title4|{{{officerTitle5|区长}}}}}}
| data23   = {{{leader_name4|{{{officer5<includeonly>|</includeonly>}}}}}}
| label24  = {{#if:{{{subdistrict|}}}{{{township|}}}{{{town|}}}{{{division<includeonly>|</includeonly>}}}|[[乡级行政区]]数}}
| data24   = {{#if:{{{subdistrict|}}}{{{township|}}}{{{town|}}}{{{division<includeonly>|</includeonly>}}}|{{{division|{{#expr:{{{town|0}}}+{{{township|0}}}+{{{ethnic_township|0}}}+{{{subdistrict|0}}}+{{{sum|0}}}+{{{hall|0}}}}}}}}}}
| label25  = {{#if:{{{town<includeonly>|</includeonly>}}}| - [[行政建制镇|镇]]数}}
| label25style = font-weight:normal
| data25   = {{{town<includeonly>|</includeonly>}}}
| label26  = {{#if:{{{township<includeonly>|</includeonly>}}}| - [[乡级行政区|乡]]数}}
| label26style = font-weight:normal
| data26   = {{{township<includeonly>|</includeonly>}}}
| label27  = {{#if:{{{ethnic_township<includeonly>|</includeonly>}}}| - [[民族乡]]数}}
| label27style = font-weight:normal
| data27   = {{{ethnic_township<includeonly>|</includeonly>}}}
| label28  = {{#if:{{{subdistrict<includeonly>|</includeonly>}}}| - [[街道办事处|街道]]数}}
| label28style = font-weight:normal
| data28   = {{{subdistrict<includeonly>|</includeonly>}}}
| label29  = {{#if:{{{hall<includeonly>|</includeonly>}}}| - [[县辖区 (中华人民共和国)|县辖区]]数}}
| label29style = font-weight:normal
| data29   = {{{hall<includeonly>|</includeonly>}}}
| label31  = 城市精神
| data31   = {{{spirit<includeonly>|</includeonly>}}}
| label32  = 城市定位
| data32   = {{{position<includeonly>|</includeonly>}}}
| label33  = [[方言]]
| data33   = {{{dialect<includeonly>|</includeonly>}}}
| label34  = [[民族|民族比例]]
| data34   = {{{nation<includeonly>|</includeonly>}}}

| header40 = {{#if:{{{area<includeonly>|</includeonly>}}}{{{area_total|}}}{{{climate|}}}{{{temperature_mean|}}}{{{coordinate|}}}|地理}}
| label41  = [[地理坐标系|经纬度]]
| data41   = {{{coordinate<includeonly>|</includeonly>}}}
| label42  = {{#if:{{{latd|}}}|[[地理坐标系|中心坐标]]}}
| data42   = {{#if:{{{latd|}}}|{{coord|{{{latd}}}|{{{latm}}}|{{{lats|0}}}|{{{latNS}}}|{{{longd}}}|{{{longm}}}|{{{longs|0}}}|{{{longEW}}}}} }}
| label43  = 总面积
| data43   = {{#invoke:Wikidata|getValue|P2046|{{{area_total<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}{{#if:{{{area_total<includeonly>|</includeonly>}}}|[[平方千米]]}}
| label44  = {{#if:{{{area_urban_district<includeonly>|</includeonly>}}}|{{nowrap| - 市区}}}}
| label44style = font-weight:normal
| data44   = {{{area_urban_district<includeonly>|</includeonly>}}}{{#if:{{{area_urban_district<includeonly>|</includeonly>}}}|平方千米}}
| label45  = {{#if:{{{area_urban<includeonly>|</includeonly>}}}|{{nowrap| - 城区}}}}
| label45style = font-weight:normal
| data45   = {{{area_urban<includeonly>|</includeonly>}}}{{#if:{{{area_urban<includeonly>|</includeonly>}}}|平方千米}}
| label46  = {{#if:{{{area_builtup<includeonly>|</includeonly>}}}|{{nowrap| - 建成区{{#if:{{{area_builtup_as_of|}}}|<sup>（{{{area_builtup_as_of|}}}）</sup>}}}}}}
| label46style = font-weight:normal
| data46   = {{#if:{{{area_builtup<includeonly>|</includeonly>}}}|{{{area_builtup}}}平方千米}}
| label47  = {{#if:{{{area_land|{{{area land<includeonly>|</includeonly>}}}}}}| - 陆地<sup>（含水域）<sup>}}
| label47style = font-weight:normal
| data47   = {{{area_land|{{{area land<includeonly>|</includeonly>}}}}}}{{#if:{{{area_land<includeonly>|</includeonly>}}}|平方千米}}
| label48  = {{#if:{{{area_water|{{{area water<includeonly>|</includeonly>}}}}}}| - 水域}}
| label48style = font-weight:normal
| data48   = {{{area_water|{{{area water<includeonly>|</includeonly>}}}}}}{{#if:{{{area_water<includeonly>|</includeonly>}}}|平方千米}}
| label49  = {{#if:{{{area_sea|{{{area sea<includeonly>|</includeonly>}}}}}}| - 海域}}
| label49style = font-weight:normal
| data49  = {{{area_sea|{{{area sea<includeonly>|</includeonly>}}}}}}{{#if:{{{area_sea<includeonly>|</includeonly>}}}|平方千米}}
| label50  = 海拔
| data50   = {{{elevation<includeonly>|</includeonly>}}}
| label51  = 最長河流
| data51   = {{{L river<includeonly>|</includeonly>}}}
| label52  = 最大湖泊
| data52   = {{{L Lakes<includeonly>|</includeonly>}}}
| label53  = 海岸线
| data53   = {{{coastline<includeonly>|</includeonly>}}}
| label54  = 气候类型
| data54   = {{{climate<includeonly>|</includeonly>}}}
| label55  = 年平均气温
| data55   = {{{temperature_mean<includeonly>|</includeonly>}}}
| label56  = 年降水量
| data56   = {{{precipitation<includeonly>|</includeonly>}}}
| label57  = 年日照时数
| data57   = {{{sunshine hrs<includeonly>|</includeonly>}}}

| header60 = {{#if:{{{pop<includeonly>|</includeonly>}}}{{{population_total|}}}{{{Housepop|}}}{{{density|}}}{{{GDP|}}}{{{GDPPC|}}}|人口及經濟}}
| label61  = {{nowrap|总人口{{#if:{{{census yr|{{{population_as_of|}}}}}}|<sup>{{nobold|（{{{census yr|{{{population_as_of|}}}}}}）}}</sup>}}}}
| data61   = {{#invoke:Wikidata|getValue|P1082|{{{pop|{{{population_total<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}}}}{{#if:{{{population_total<includeonly>|</includeonly>}}}|万人}}
| label62  = {{#if:{{{Housepop<includeonly>|</includeonly>}}}| - 户籍人口}}
| label62style = font-weight:normal
| data62   = {{{Housepop<includeonly>|</includeonly>}}}
| label63  = {{#if:{{{Repop<includeonly>|</includeonly>}}}| - 常住人口}}
| label63style = font-weight:normal
| data63   = {{{Repop<includeonly>|</includeonly>}}}
| label64  = {{#if:{{{TR<includeonly>|</includeonly>}}}| - 暂住人口}}
| label64style = font-weight:normal
| data64   = {{{TR<includeonly>|</includeonly>}}}
| label65  = {{#if:{{{pop_urban|{{{population_urban<includeonly>|</includeonly>}}}}}}| - 城区人口}}
| label65style = font-weight:normal
| data65   = {{{pop_urban|{{{population_urban<includeonly>|</includeonly>}}}}}}{{#if:{{{population_urban_as_of|}}}|<sup>（{{{population_urban_as_of|}}}）</sup>}}
| label66  = {{nowrap|人口密度}}
| data66   = {{{density|{{{population_density<includeonly>|</includeonly>}}}}}}
| label67  = {{#if:{{{density_urban<includeonly>|</includeonly>}}}|{{nowrap| - 城区人口密度}}}}
| label67style = font-weight:normal
| data67   = {{{density_urban<includeonly>|</includeonly>}}}
| label68  = {{#if:{{{GDP<includeonly>|</includeonly>}}}|[[国内生产总值|GDP]]{{#if:{{{GDP_as_of|{{{GDP as of|}}}}}}|<sup>{{nobold|（{{{GDP_as_of|{{{GDP as of|}}}}}}）}}</sup>}}}}
| data68   = {{{GDP<includeonly>|</includeonly>}}}{{#if:{{{GDP<includeonly>|</includeonly>}}}|元[[人民币]]}}
| label69  = {{#if:{{{GDPPC<includeonly>|</includeonly>}}}|人均GDP}}
| data69   = {{{GDPPC<includeonly>|</includeonly>}}}{{#if:{{{GDPPC<includeonly>|</includeonly>}}}|元[[人民币]]}}

| header80 = 其它
| label81  = [[时区]]
| data81   = {{{time_zone<includeonly>|</includeonly>[[UTC+08:00|UTC+8]]（[[北京时间]]）}}}
| label82  = [[市树]]
| data82   = {{{city_tree<includeonly>|</includeonly>}}}
| label83  = [[市树|县树]]
| data83   = {{{county_tree<includeonly>|</includeonly>}}}
| label84  = [[市花]]
| data84   = {{{city_flower<includeonly>|</includeonly>}}}
| label85  = [[市花|县花]]
| data85   = {{{county_flower<includeonly>|</includeonly>}}}
| label86  = 市歌
| data86   = {{{city_anthem<includeonly>|</includeonly>}}}
| label87  = 县歌
| data87   = {{{county_anthem<includeonly>|</includeonly>}}}
| label88  = [[中华人民共和国境内地区邮政编码列表|邮政编码]]
| data88   = {{#invoke:Wikidata|getValue|P281|{{{post code|{{{postcode<includeonly>|FETCH_WIKIDATA</includeonly>}}}}}}}}
| label89  = [[中华人民共和国电话区号|电话区号]]
| data89   = {{tel|86|{{{phone code<includeonly>|</includeonly>}}}}}
| label90  = [[中华人民共和国民用机动车号牌|车牌首号]]
| data90   = {{wikidata|property|P395|{{{carlicense<includeonly>|</includeonly>}}}}}

| below    = {{#if: {{{web|}}}{{{website|}}}|'''網站：'''}}{{{website|}}}{{#if: {{{web|}}}|{{URL|{{{web|}}}|{{{web_title|}}}}}}}<!--
-->{{#if: {{{footnotes|}}}|<br /><small style="text-align: left; background-color: #eee">{{{footnotes}}}</small> }}
}}<noinclude>
{{Documentation}}
</noinclude>