{{infobox3cols
| title    = {{{name|<includeonly>{{PAGENAMEBASE}}</includeonly>}}}
| image    = {{#if:{{{logo|}}}{{{image|}}}|{{nowrap|{{{logo|}}}{{{image|}}}}}}}
| caption  = {{{caption|}}}

| labelstyle = white-space: nowrap; vertical-align: baseline; text-align: left
| label1   = 類別
| data1    = {{{type|}}}

| header2  = {{#if:{{{designer|}}}{{{design_date|}}}{{{manufacturer|}}}{{{production_date|}}}|產品歷史}}
| rowclass2 = navbox-title

| label3   = 設計者
| data3    = {{{designer|}}}
| label4   = 設計时间
| data4    = {{{design_date|}}}
| label5   = 製造商
| data5    = {{{manufacturer|}}}
| label6   = 製造时间
| data6    = {{{production_date|}}}
| label7   = 前身
| data7    = {{{superseded|}}}
| label8   = 取代
| data8    = {{{superseded_by|}}} {{#if:{{{superseded_by_date|}}}|({{{superseded_by_date|}}})}}

| header9  = {{#if:{{{weight|}}}{{{length|}}}{{{width|}}}{{{height|}}}{{{diameter|}}}{{{num_pins|}}}|一般规格}}
| rowclass9 = navbox-title

| label10  = 重量
| data10   = {{{weight|}}}
| label11  = 長度
| data11   = {{{length|}}}
| label12  = 直径
| data12   = {{{diameter|}}}
| label13  = 宽度
| data13   = {{{width|}}}
| label14  = 高度
| data14   = {{{height|}}}
| label15  = 热插拔
| data15   = {{{hotplug|}}}
| label16  = Daisy chain
| data16   = {{{daisy_chain|}}}
| label17  = 外接
| data17   = {{{external|}}}
| label18  = 音频信号
| data18   = {{{audio_signal|}}}
| label19  = 视频信号
| data19   = {{{video_signal|}}}
| label20  = 纜線
| data20   = {{{cable|}}}
| label21  = [[通带]]
| data21   = {{{passband|}}}
| label22  = 引脚
| data22   = {{{num_pins|}}}
| label23  = 连接器
| data23   = {{{physical_connector|}}}

| header24 = {{#if:{{{electrical|}}}{{{earth|}}}{{{maximum_voltage|}}}{{{maximum_current|}}}|电力}}
| rowclass24 = navbox-title

| label25  = 信号
| data25   = {{{electrical|}}}
| label26  = 接地
| data26   = {{{earth|}}}
| label27  = 最大電壓
| data27   = {{{maximum_voltage|}}}
| label28  = 最大電流
| data28   = {{{maximum_current|}}}

| header29 = {{#if:{{{data_signal|}}}{{{data_bit_width|}}}{{{data_bandwidth|}}}{{{data_devices|}}}{{{data_style|}}}|数据}}
| rowclass29 = navbox-title

| label30  = 数据信号
| data30   = {{{data_signal|}}}
| label31  = 宽度
| data31   = {{{data_bit_width|}}}
| label32  = 比特率
| data32   = {{{data_bandwidth|}}}
| label33  = 最多设备数
| data33   = {{{data_devices|}}}
| label34  = 协议
| data34   = {{{data_style|}}}

| header35 = {{#if:{{{pinout_image|}}}{{{pin1|}}}{{{pin1_name|}}}{{{shell|}}}{{{hooks|}}}{{{pin_custom1|}}}{{{pin_custom1_name|}}}|引脚输出}}
| rowclass35 = navbox-title

| data36   = {{{pinout_image|}}}
| data37   = {{{pinout_caption|}}}
| data38   = {{{pinout_image2|}}}
| data39   = {{{pinout_caption2|}}}

| label40  = 引脚
| data40a  = {{#if:{{{pinout_col1_name|}}}|'''{{{pinout_col1_name|}}}'''}}
| data40b   = {{#if:{{{pinout_col2_name|}}}|'''{{{pinout_col2_name|}}}'''}}

| label41  = 引脚1
| data41a  = {{{pin1_name|}}}
| data41b  = {{{pin1|}}}
| label42  = 引脚2
| data42a  = {{{pin2_name|}}}
| data42b  = {{{pin2|}}}
| label43  = 引脚3
| data43a  = {{{pin3_name|}}}
| data43b  = {{{pin3|}}}
| label44  = 引脚4
| data44a  = {{{pin4_name|}}}
| data44b  = {{{pin4|}}}
| label45  = 引脚5
| data45a  = {{{pin5_name|}}}
| data45b  = {{{pin5|}}}
| label46  = 引脚6
| data46a  = {{{pin6_name|}}}
| data46b  = {{{pin6|}}}
| label47  = 引脚7
| data47a  = {{{pin7_name|}}}
| data47b  = {{{pin7|}}}
| label48  = 引脚8
| data48a  = {{{pin8_name|}}}
| data48b  = {{{pin8|}}}
| label49  = 引脚9
| data49a  = {{{pin9_name|}}}
| data49b  = {{{pin9|}}}
| label50  = 引脚10
| data50a  = {{{pin10_name|}}}
| data50b  = {{{pin10|}}}

| label51  = 引脚11
| data51a  = {{{pin11_name|}}}
| data51b  = {{{pin11|}}}
| label52  = 引脚12
| data52a  = {{{pin12_name|}}}
| data52b  = {{{pin12|}}}
| label53  = 引脚13
| data53a  = {{{pin13_name|}}}
| data53b  = {{{pin13|}}}
| label54  = 引脚14
| data54a  = {{{pin14_name|}}}
| data54b  = {{{pin14|}}}
| label55  = 引脚15
| data55a  = {{{pin15_name|}}}
| data55b  = {{{pin15|}}}
| label56  = 引脚16
| data56a  = {{{pin16_name|}}}
| data56b  = {{{pin16|}}}
| label57  = 引脚17
| data57a  = {{{pin17_name|}}}
| data57b  = {{{pin17|}}}
| label58  = 引脚18
| data58a  = {{{pin18_name|}}}
| data58b  = {{{pin18|}}}
| label59  = 引脚19
| data59a  = {{{pin19_name|}}}
| data59b  = {{{pin19|}}}

| label60  = 引脚20
| data60a  = {{{pin20_name|}}}
| data60b  = {{{pin20|}}}
| label61  = 引脚21
| data61a  = {{{pin21_name|}}}
| data61b  = {{{pin21|}}}
| label62  = 引脚22
| data62a  = {{{pin22_name|}}}
| data62b  = {{{pin22|}}}
| label63  = 引脚23
| data63a  = {{{pin23_name|}}}
| data63b  = {{{pin23|}}}
| label64  = 引脚24
| data64a  = {{{pin24_name|}}}
| data64b  = {{{pin24|}}}
| label65  = 引脚25
| data65a  = {{{pin25_name|}}}
| data65b  = {{{pin25|}}}
| label66  = 引脚26
| data66a  = {{{pin26_name|}}}
| data66b  = {{{pin26|}}}
| label67  = 引脚27
| data67a  = {{{pin27_name|}}}
| data67b  = {{{pin27|}}}
| label68  = 引脚28
| data68a  = {{{pin28_name|}}}
| data68b  = {{{pin28|}}}
| label69  = 引脚29
| data69a  = {{{pin29_name|}}}
| data69b  = {{{pin29|}}}

| label70  = 引脚30
| data70a  = {{{pin30_name|}}}
| data70b  = {{{pin30|}}}
| label71  = 引脚31
| data71a  = {{{pin31_name|}}}
| data71b  = {{{pin31|}}}
| label72  = 引脚32
| data72a  = {{{pin32_name|}}}
| data72b  = {{{pin32|}}}
| label73  = 引脚33
| data73a  = {{{pin33_name|}}}
| data73b  = {{{pin33|}}}
| label74  = 引脚34
| data74a  = {{{pin34_name|}}}
| data74b  = {{{pin34|}}}
| label75  = 引脚35
| data75a  = {{{pin35_name|}}}
| data75b  = {{{pin35|}}}
| label76  = 引脚36
| data76a  = {{{pin36_name|}}}
| data76b  = {{{pin36|}}}
| label77  = 引脚37
| data77a  = {{{pin37_name|}}}
| data77b  = {{{pin37|}}}
| label78  = 引脚38
| data78a  = {{{pin38_name|}}}
| data78b  = {{{pin38|}}}
| label79  = 引脚39
| data79a  = {{{pin39_name|}}}
| data79b  = {{{pin39|}}}
| label80  = 引脚40
| data80a  = {{{pin40_name|}}}
| data80b  = {{{pin40|}}}

| label81  = {{{pin_custom1_name|}}}
| data81a  = {{{pin_name_custom1|}}}
| data81b  = {{{pin_custom1|}}}
| label82  = {{{pin_custom2_name|}}}
| data82a  = {{{pin_name_custom2|}}}
| data82b  = {{{pin_custom2|}}}
| label83  = {{{pin_custom3_name|}}}
| data83a  = {{{pin_name_custom3|}}}
| data83b  = {{{pin_custom3|}}}
| label84  = {{{pin_custom4_name|}}}
| data84a  = {{{pin_name_custom4|}}}
| data84b  = {{{pin_custom4|}}}
| label85  = {{{pin_custom5_name|}}}
| data85a  = {{{pin_name_custom5|}}}
| data85b  = {{{pin_custom5|}}}
| label86  = {{{pin_custom6_name|}}}
| data86a  = {{{pin_name_custom6|}}}
| data86b  = {{{pin_custom6|}}}
| label87  = {{{pin_custom7_name|}}}
| data87a  = {{{pin_name_custom7|}}}
| data87b  = {{{pin_custom7|}}}
| label88  = {{{pin_custom8_name|}}}
| data88a  = {{{pin_name_custom8|}}}
| data88b  = {{{pin_custom8|}}}

| below    = {{{pinout_notes|}}}

}}<noinclude>{{documentation}}<!-- please add category and language links to the /doc sub-page, not here --></noinclude>