<noinclude>{{Ambox|text='''本模板正在逐步淘汰。'''如果您到此寻找有关航天器的信息框，请使用以下替代方案：
* {{tl|Infobox spaceflight}}用于单个航天器
* {{tl|Infobox spacecraft class}}用于制造了多个航天器的型号
}}</noinclude>{{Infobox
| bodyclass= vcard
| title = {{{Name|<includeonly>{{{name|{{PAGENAME}} }}}</includeonly>}}}
| titleclass = fn org
| image = {{{Image|{{{image|}}} }}}
| caption = {{{Caption|{{{caption|}}} }}}
| labelstyle = white-space:nowrap;
| label1 = 所属组织
| data1 = {{{Organization|{{{Organisation|}}} }}}
| label2 = 主制造商
| data2 = {{{Major_Contractors|{{{Contractors|{{{Manufacturer|}}}}}} }}}
| label3 = 卫星平台
| data3 = {{{Bus|{{{Model|}}}}}}
| label4 = 任务类型
| data4 = {{{Mission_Type|{{{MissionType|}}} }}}
| label5 = 掠过对象
| data5 = {{{Flyby_Of|}}}
| label6 = 掠过时间
| data6 = {{{Flyby_Date|}}}
| label7 = 现目的地
| data7 = {{{Current_Destination|}}}
| label8 = 环绕对象
| data8 = {{{Satellite_Of|{{{SatelliteOf|}}}}}}
| label9 = 入轨时间
| data9 = {{{Orbital_Insertion_Date|}}}
| label10 = 绕轨圈数
| data10 = {{{Orbits|}}}
| label11 = 发射时间
| data11 = {{{Launch|{{{launch_date|{{{LaunchDate|{{{Launch Date|}}}}}}}}}}}}
| label12 = 发射手段
| data12 = {{{Launch_Vehicle|{{{LaunchVehicle|}}}}}}
| label13 = 运载火箭
| data13 = {{{Carrier_Rocket|{{{launch_vehicle|{{{Launcher|}}}}}}}}} {{{Flight Number|}}}
| label14 = 发射地点
| data14 = {{{Launch_Site|{{{launch_site|}}}}}}
| label15 = 任务时长
| data15 = {{{Mission_Duration|{{{MissionDuration|{{{Lifetime|}}}}}}}}}
| label16 = 任务重点
| data16 = {{{MissionHighlight|}}}
| label17 = 轨道衰减
| data17 = {{{Decay|}}}
| label18 = [[国际卫星标识符|COSPAR ID]]
| data18 = {{#if: {{{COSPAR_ID|}}} | {{#ifeq:{{#property:P247}}|{{{COSPAR_ID}}}|{{Cospar|{{#property:P247}}}}|{{{COSPAR_ID}}}}} | {{{NSSDC_ID|{{{国际卫星标识符|{{{國際衛星標誌符|{{Cospar|{{#property:P247}}}}}}}}}} }}} }}
| label19 = [[衛星目錄序號|SATCAT {{abbr|no.|number}}]]
| data19 = {{#if: {{{SATCAT|}}} | {{{SATCAT}}} | {{wd|property|edit@end|P377}} }}
| label20 = 官方网站
| data20 = {{{Webpage|{{{Web|}}}}}}
| label21 = 质量
| data21 = {{{Mass|{{{mass|{{#if:{{{Orbit Mass|}}}|{{#if:{{{Launch Mass|}}}|{{{Launch Mass}}}（发射时）<br/>{{{Orbit Mass}}}（在轨时）|{{{Orbit Mass}}}}}|{{{Launch Mass|}}}}}}}}}}}
| label22 = 尺寸
| data22 = {{{Dimensions|}}}
| label23 = 功耗
| data23 = {{{Power|{{{Expendable Energy|}}}}}}
| label24 = 动力
| data24 = {{{Batteries|}}}
| header25 = {{#if:{{{Orbit_regime|{{{orbit_type|}}}}}}{{{Longitude|{{{Former location|}}}{{{Current location|}}}}}}{{{Semimajor_Axis|}}}{{{Eccentricity|}}}{{{Inclination|{{{orbit_inclination|}}}}}}{{{Orbital_Period|}}}{{{Apoapsis|}}}{{{Apogee|}}}{{{Periapsis|}}}{{{Perigee|}}}{{{Repeat_Interval|{{{orbit_repeat|}}}}}}{{{orbit_reference|}}}{{{orbit_altitude|}}}{{{Swath|}}}{{{orbit_crossing|}}}{{{orbit_swath|}}}| [[軌道根數|轨道参数]]}}
| label26 = [[参考坐标系]]
| data26 = {{{orbit_reference|}}}
| label27 = [[轨道类型]]
| data27 = {{{Orbit_regime|{{{orbit_type|}}}}}}
| label28 = [[半长轴]]
| data28 = {{{Semimajor_Axis|{{{SemiMajor|}}} }}}
| label29 = [[轨道离心率|离心率]]
| data29 = {{{Eccentricity|}}}
| label30 = [[轨道倾角|倾角]]
| data30 = {{{Inclination|{{{orbit_inclination|}}}}}}
| label31 = [[轨道高度|高度]]
| data31 = {{{orbit_altitude|}}}
| label32 = [[拱點|远拱点]]
| data32 = {{{Apoapsis|{{{Apogee|{{{Apo|}}}}}}}}}
| label33 = [[拱點|近拱点]]
| data33 = {{{Periapsis|{{{Perigee|{{{Peri|}}}}}}}}}
| label34 = [[轨道周期|周期]]
| data34 = {{{Orbital_Period|{{{Period|}}}}}}
| label35 = 静止经度
| data35 = {{{Longitude|{{#if:{{{Former location|}}}|{{#if:{{{Current location|}}}|{{{Former location|}}}<br />{{{Current location|}}}|{{{Former location|}}}}}|{{{Current location|}}}}}}}}
| label36 = 回归日数
| data36 = {{{Repeat_Interval|{{{orbit_repeat|}}}}}}
| label37 = 日环绕数
| data37 = {{{Orbits Daily|}}}
| label38 = 回归精度
| data38 = {{{Repetivity|}}}
| label39 = [[观测宽度]]
| data39 = {{{orbit_swath|{{{Swath|}}}}}}
| label40 = 赤道交错时间
| data40 = {{{orbit_crossing|}}}
| header41 = {{#if:{{{Planet|}}}{{{Planet_Landing|}}}{{{Planet_Coords|}}}{{{Planet_Depart|}}}|{{{Planet|}}}表面着陆|{{#if:{{{LunarLandingDate|}}}{{{LunarLandingCoords|}}}{{{LunarLiftoffDate|}}}|月面着陆}}}}
| label42 = 着陆日期
| data42 = {{{Planet_Landing|{{{LunarLandingDate|}}}}}}
| label43 = 着陆地点
| data43 = {{{Planet_Coords|{{{LunarLandingCoords|}}}}}}
| label44 = 离陆时间
| data44 = {{{Planet_Depart|{{{LunarLiftoffDate|}}}}}}
| header45 = {{#if:{{{Instruments|}}}{{{Main_Instruments|}}}{{{Resolution|}}}{{{Spectral_Band|}}}{{{Data_Rate|}}}{{{SSR|}}}| 携带仪器}}
| data46 = {{{Instruments|}}}
| label47 = 主要仪器
| data47 = {{{Main_Instruments|}}}
| label48 = 空间分辨率
| data48 = {{{Resolution|}}}
| label49 = 光谱带
| data49= {{{Spectral_Band|}}}
| label50 = 数据速率
| data50 = {{{Data_Rate|}}}
| label51 = 固态记录装置
| data51 = {{{SSR|}}}
| label52 = 图像分辨率
| data52 = {{{IMG_Resolution|}}}
| header53 = {{#if:{{{Transponders|}}}{{{Transponder Capacity|}}}{{{Coverage|}}}{{{Twta output power|{{{Twta|}}}}}}{{{Bandwidth|}}}{{{EIRP|}}}|应答机}}
| label54 = 转发器类型
| data54 = {{{Transponders|}}}
| label55 = 转发器数量
| data55 = {{{Transponder Capacity|}}}
| label56 = 覆盖范围
| data56 = {{{Coverage|}}}
| label57 = 行波管放大器输出功率
| data57 = {{{Twta output power|{{{Twta|}}}}}}
| label58 = 带宽
| data58 = {{{Bandwidth|}}}
| label59 = [[等效全向辐射功率]]
| data59 = {{{EIRP|}}}
| header60 = {{#if:{{{Refs|}}}|备注：}} {{{Refs|}}}
| below = {{{Below|}}}
}}<noinclude>{{documentation}}</noinclude>