{{Infobox
|name=Infobox 日本的市 (廢除) 
|titlestyle=font-size:120%;
|imagestyle=text-align:center;
|headerstyle=background-color:#ffcc99;
|labelstyle=white-space:nowrap;
|belowstyle=font-size:90%; text-align:left;
|bodystyle=margin:0 0 1em 1em; width:23em; float:right; clear:right;
|title={{{自治體名}}}
|image={{{圖像|}}}
|caption={{#if:{{{圖像|}}}{{{圖像說明|}}}|{{{圖像說明}}}}}
|header1=名稱
|label2=日文原名
|data2={{lang|ja|{{{日文原名|}}}}}
|label3=平假名
|data3={{{平假名|}}}
|label4=羅馬拼音
|data4={{{羅馬字拼音|{{{羅馬拼音|}}}}}}
|header5=廢除資料
|label6=理由
|data6={{{廢除理由|}}}{{#if:{{{廢除時處置|}}}|<br />{{{廢除時處置}}}}}
|label7=時間
|data7={{{廢除時間|}}}
|label8=現所屬
|data8={{{現在市|}}}
|header10=廢除時地理位置
|label11=國家
|data11={{JPN}}
|label12=[[都道府縣]]
|data12={{#if:{{{都道府縣|}}}|[[{{{都道府縣}}}]]}}{{#if:{{{支廳|}}}| [[{{ #if: {{{支廳連結|}}} | {{{支廳連結}}}{{!}}}}{{{支廳}}}]] }}
|label13=[[全國地方公共團體編號|政府編號]]
|data13={{{編號|}}}
|label14=鄰近行政區
|data14={{{自治體|}}}
|data15={{#if:{{{地圖|}}}|{{{地圖}}}<br />{{{自治體名}}}在[[日本]]{{{都道府縣}}}的位置}}
|header20=廢除時相關數據
|label21=面積
|data21={{#if:{{{面積|}}}|{{{面積}}}km²{{#switch:{{{邊界未定|}}}|有=<span style="font-size:80%;">（部份邊界未確定）</span> | }}}}
|label22=人口
|data22={{#if:{{{人口|}}}|{{{人口}}}<small>（{{{統計時間}}}數據）</small>}}
|label23=[[人口密度]]
|data23={{#if:{{{人口密度|}}}|{{{人口密度}}}人/[[平方公里|km²]]}}
|header25=象徵
|label26=市章
|data26={{{市章|}}}
|label27=市樹
|data27={{{樹|}}}
|label28=市花
|data28={{{花|}}}
|label29=市鳥
|data29={{{鳥|}}}
|label30=市歌
|data30={{{歌|}}}
|label34={{{其他象徵物|}}}
|data34={{{其他象徵|}}}
|header35=原{{{自治體名}}}{{{政府機關名|役所}}}<br /><small>（以下資料現在可能已無法使用）</small>
|label36=市長
|data36={{#if:{{{市長|}}}|{{{市長}}}{{#if:{{{卸任日期|}}}|<small>（任期至：{{{卸任日期}}}）</small>}}}}
|label37=市議員數
|data37={{{議員數|}}}
|label40=地址
|data40={{#if:{{{所在地|}}}|{{#if:{{{郵遞區號|}}}|〒{{{郵遞區號}}}　}}{{{都道府縣}}}<br />{{{所在地}}}}}
|label41=座標
|data41={{#if:{{{經度|}}}{{{緯度|}}}|{{{經度|}}}<br />{{{緯度|}}}}}
|label45=網站
|data45={{#if:{{{外部連結|}}}|<small>[{{{外部連結|}}} 原{{{自治體名}}}網站]</small>}}
|below={{{註記|}}}
}}<includeonly>{{DEFAULTSORT:{{{羅馬字拼音}}}}} [[Category:日本已廢除的市]] {{ #switch: {{{都道府縣}}} | 東京府 = | 樺太廳 = [[Category:樺太廳行政區劃]] | [[Category:{{{都道府縣}}}行政區劃 (廢除)]] }}</includeonly><noinclude>{{Documentation}}</noinclude>