<includeonly>{{infobox person/core
| child = {{{child|}}}
| abovestyle = {{{abovestyle|}}}
| honorific_prefix = {{{honorific prefix|{{{honorific_prefix|{{{前缀尊称|{{{前綴尊稱|}}}}}}}}}}}}
| name = {{{name|{{{subject_name|{{{名字|{{{姓名|{{PAGENAMEBASE}}}}}}}}}}}}}}
| honorific_suffix = {{{honorific suffix|{{{honorific_suffix|{{{后缀尊称|{{{後綴尊稱|}}}}}}}}}}}}
| image = {{{image|{{{imagename|{{{image_name|{{{image name|{{{Img|{{{圖片|{{{图片|{{{圖像|{{{图像|}}}}}}}}}}}}}}}}}}}}}}}}}}}
| image_size = {{{width|{{{imagesize|{{{image_size|{{{image size|{{{Img_size|{{{圖片尺寸|{{{图片尺寸|{{{圖像大小|{{{图像大小|{{{图像宽度|{{{圖像寬度|}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
| image_upright = {{{image_upright|}}}
| alt = {{{alt|{{{图像替代|{{{圖像替代|}}}}}}}}}
| caption = {{{caption|{{{imagecaption|{{{image_caption|{{{Img_capt|{{{圖片簡介|{{{图片简介|{{{圖像說明|{{{图像说明|}}}}}}}}}}}}}}}}}}}}}}}}
| native_name = {{{native_name|{{{foreignname|{{{原文名|{{{外文名|{{{foreign_names|{{{foreign_name|}}}}}}}}}}}}}}}}}}
| native_name_lang = {{{native_name_lang|{{{fnamelang|{{{语系|{{{語系|{{{外文|}}}}}}}}}}}}}}}
| pronunciation = {{{pronunciation|{{{发音|{{{發音|{{{读音|{{{讀音|}}}}}}}}}}}}}}}
| romaji = {{{romaji|{{{romanizedname|{{{romanized_name|{{{羅馬拼音|{{{罗马拼音|}}}}}}}}}}}}}}}
| English_name = {{{English_name|{{{english_name|{{{englishname|{{{英文名|{{{english_names|}}}}}}}}}}}}}}}
| Zi = {{{Zi|{{{zi|{{{字|}}}}}}}}}
| Hao = {{{Hao|{{{hao|{{{号|{{{號|}}}}}}}}}}}}
| real_name = {{{realname|{{{real_name|{{{full name|{{{原名|{{{本名|}}}}}}}}}}}}}}}
| gender = {{{gender|{{{Sex|{{{sex|{{{性别|{{{性別|}}}}}}}}}}}}}}}
| birth_name = {{{birth name|{{{birth_name|{{{Birth_name|{{{birthname|{{{出生名|}}}}}}}}}}}}}}}
| birth_date = {{{birth date|{{{birth_date|{{{birthdate|{{{date_of_birth|{{{date of birth|{{{Born|{{{出生日期|}}}}}}}}}}}}}}}}}}}}}
| birth_place = {{{birth place|{{{birth_place|{{{birthplace|{{{location|{{{place_of_birth|{{{place of birth|{{{出生地|{{{出生地點|{{{出生地点|}}}}}}}}}}}}}}}}}}}}}}}}}}}
| baptised = {{{baptised|{{{受洗|}}}}}}
| disappeared_date = {{{disappeared_date|{{{失踪日期|{{{失蹤日期|}}}}}}}}}
| disappeared_place = {{{disappeared_place|{{{失踪地|{{{失蹤地|{{{失踪地点|{{{失蹤地點|}}}}}}}}}}}}}}}
| disappeared_status = {{{disappeared_status|{{{失踪情况|{{{失蹤情況|}}}}}}}}}
| death_date = {{{death date|{{{death_date|{{{deathdate|{{{date_of_death|{{{date of death|{{{end date|{{{Died|{{{死亡日期|{{{逝世日期|}}}}}}}}}}}}}}}}}}}}}}}}}}}
| death_place = {{{death place|{{{death_place|{{{deathplace|{{{place_of_death|{{{place of death|{{{endplace|{{{死亡地|{{{逝世地点|{{{逝世地點|}}}}}}}}}}}}}}}}}}}}}}}}}}}
| death_cause = {{{death cause|{{{death_cause|{{{死因|}}}}}}}}}
| body_discovered = {{{body discovered|{{{body_discovered|{{{遗体发现地|{{{遺體發現地|}}}}}}}}}}}}
| resting_place = {{{resting place|{{{resting_place|{{{restingplace|{{{墓地|}}}}}}}}}}}}
| resting_place_coordinates = {{{resting place coordinates|{{{resting_place_coordinates|{{{restingplacecoordinates|{{{墓地坐标|{{{墓地坐標|{{{墓地座標|}}}}}}}}}}}}}}}}}}
| monuments = {{{monuments|{{{纪念碑|{{{纪念馆|{{{纪念建筑|{{{紀念碑|{{{紀念館|{{{紀念建築|}}}}}}}}}}}}}}}}}}}}}
| residence = {{{residence|{{{居住地|}}}}}}
| nationality = {{{nationality|{{{country|{{{国籍|{{{國籍|}}}}}}}}}}}}
| permanent_residency = {{{permanent_residency|{{{permanent residency|{{{永久居留权|{{{永久居留權|}}}}}}}}}}}}
| other_names = {{{other names|{{{other_names|{{{other_name|{{{othername|{{{alias|{{{又名|{{{别名|{{{別名|}}}}}}}}}}}}}}}}}}}}}}}}
| ancestor = {{{ancestor|{{{register|{{{籍贯|{{{籍貫|}}}}}}}}}}}}
| ethnicity = {{{ethnicity|{{{people|{{{nation|{{{种族|{{{種族|{{{民族|}}}}}}}}}}}}}}}}}}
| language  = {{{languages|{{{language|{{{语言|{{{語言|}}}}}}}}}}}}
| citizenship = {{{citizenship|{{{公民权|{{{公民權|}}}}}}}}}
| education = {{{education|{{{教育程度|}}}}}}
| alma_mater = {{{almamater|{{{alma_mater|{{{alma mater|{{{母校|}}}}}}}}}}}}
| occupation = {{{job|{{{occupation|{{{Occupation|{{{職業|{{{职业|}}}}}}}}}}}}}}}
| years_active = {{{period|{{{year|{{{yearactive|{{{year_active|{{{yearsactive|{{{years_active|{{{Years_active|{{{years active|{{{活跃时期|{{{活躍時期|{{{活動時期|{{{活动时期|{{{活躍年代|{{{活跃年代|}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
| era = {{{era|{{{Era|{{{年代|}}}}}}}}}
| employer = {{{employer|{{{雇主|{{{僱主|}}}}}}}}}
| organization = {{{organization|{{{organizations|{{{组织|{{{組織|}}}}}}}}}}}}
| agent = {{{agent|{{{机构|{{{機構|}}}}}}}}}
| known_for = {{{known for|{{{known_for|{{{known|{{{知名原因|}}}}}}}}}}}}
| research ={{{research|{{{研究领域|{{{研究領域|}}}}}}}}}
| works = {{{works|}}}
| credits = {{{credits|}}}
| label_name = {{{label_name|{{{品牌|}}}}}}
| notable_works = {{{notable works|{{{notable_works|{{{知名作品|}}}}}}}}}
| style = {{{style|{{{风格|{{{風格|}}}}}}}}}
| home_town = {{{home town|{{{home_town|{{{hometown|{{{家乡|{{{家鄉|}}}}}}}}}}}}}}}
| salary = {{{salary|{{{薪水|{{{薪金|}}}}}}}}}
| net_worth = {{{net worth|{{{net_worth|{{{networth|{{{净资产|{{{淨資產|{{{净值|{{{淨值|}}}}}}}}}}}}}}}}}}}}}
| height = {{{height|{{{身高|}}}}}}
| weight = {{{weight|{{{体重|{{{體重|}}}}}}}}}
| hair_color = {{#if:{{{haircolour|{{{hair_colour|{{{发色|{{{髮色|}}}}}} }}}}}}|{{{haircolour|{{{hair_colour|{{{发色|{{{髮色|}}}}}} }}}}}}|{{{haircolor|{{{hair_color|{{{发色|{{{髮色|}}}}}} }}}}}}|{{{发色|{{{髮色|}}}}}}}}
| eye_color = {{#if:{{{eyecolour|{{{eye_colour|{{{瞳色|}}}}}}}}}|{{{eyecolour|{{{eye_colour|{{{瞳色|}}}}}}}}}|{{{eyecolor|{{{eye_color|{{{瞳色|}}}}}}}}}|{{{瞳色|}}}}}
| measurements = {{{body|{{{measurements|{{{三围|{{{三圍|}}}}}}}}}}}}
| television = {{{television|{{{电视节目|{{{電視節目|}}}}}}}}}
| title = {{{title|{{{头衔|{{{頭銜|}}}}}}}}}
| term = {{{term|{{{头衔时期|{{{頭銜時期|}}}}}}}}}
| predecessor = {{{predecessor|{{{前任|}}}}}}
| successor = {{{successor|{{{继任|{{{繼任|}}}}}}}}}
| party = {{{party|{{{政党|{{{政黨|}}}}}}}}}
| movement = {{{movement|{{{政治运动|{{{政治運動|}}}}}}}}}
| opponents = {{{opponents|{{{竞争者|{{{競爭者|}}}}}}}}}
| boards = {{{boards|{{{董事会|{{{董事會|}}}}}}}}}
| religion = {{{religion|{{{宗教|{{{宗教信仰|{{{信仰|}}}}}}}}}}}}
| denomination = {{{denomination|{{{宗派|}}}}}}
| criminal_charge = {{{criminal charge|{{{criminal_charge|{{{刑事起诉|{{{刑事起訴|}}}}}}}}}}}}
| criminal_penalty = {{{criminal penalty|{{{criminal_penalty|{{{刑事处罚|{{{刑事處罰|}}}}}}}}}}}}
| criminal_status = {{{criminal status|{{{criminal_status|{{{刑事状况|{{{刑事狀況|}}}}}}}}}}}}
| spouse = {{{spouse|{{{配偶|}}}}}}
| partner = {{{partner|{{{domesticpartner|{{{伴侣|{{{伴侶|}}}}}}}}}}}}
| children = {{{children|{{{儿女|{{{兒女|{{{子女|}}}}}}}}}}}}
| parents = {{{parents|{{{父母|}}}}}}
| relatives = {{{relations|{{{relatives|{{{亲属|{{{親屬|}}}}}}}}}}}}
| family = {{{family|{{{家族成员|{{{家族成員|}}}}}}}}}
| callsign = {{{callsign|{{{呼号|{{{呼號|}}}}}}}}}
| awards = {{{awards|{{{獎項|{{{奖项|{{{获奖|{{{獲獎|}}}}}}}}}}}}}}}
| honors = {{#if:{{{honours|{{{荣誉|{{{榮譽|{{{殊荣|{{{殊榮|}}}}}}}}}}}}}}}|{{{honours|{{{荣誉|{{{榮譽|{{{殊荣|{{{殊榮|}}}}}}}}}}}}}}}|{{{honors|{{{荣誉|{{{榮譽|{{{殊荣|{{{殊榮|}}}}}}}}}}}}}}}|{{{荣誉|{{{榮譽|{{{殊荣|{{{殊榮|}}}}}}}}}}}}}}
| website = {{{website|{{{homepage|{{{URL|{{{官方網站|{{{官方网站|{{{网站|{{{網站|}}}}}}}}}}}}}}}}}}}}}
| educate = {{{educate|}}}
| job2 = {{{job2|}}}
| past = {{{past|{{{经历|{{{經歷|}}}}}}}}}
| work = {{{work|}}}
| award = {{{award|}}}
| module = {{{misc|{{{module|{{{misc1|{{{module1|}}}}}}}}}}}}
| module2 = {{{misc2|{{{module2|}}}}}}
| module3 = {{{misc3|{{{module3|}}}}}}
| module4 = {{{misc4|{{{module4|}}}}}}
| module5 = {{{misc5|{{{module5|}}}}}}
| module6 = {{{misc6|{{{module6|}}}}}}
| influences = {{{influences|{{{受影响于|{{{受影響於|}}}}}}}}}
| influenced = {{{influenced|{{{影响于|{{{影響於|}}}}}}}}}
| signature = {{{signature|{{{签名|{{{簽名|}}}}}}}}}
| signature_size = {{{signature size|{{{signature_size|{{{签名大小|{{{簽名大小|}}}}}}}}}}}}
| signature_alt = {{{signature alt|{{{signature_alt|{{{签名替代|{{{簽名替代|}}}}}}}}}}}}
| footnotes = {{{footnotes|{{{备注|{{{備註|{{{脚注|{{{腳註|}}}}}}}}}}}}}}}
}}{{#ifeq:{{{child|}}}|yes||{{Wikidata image|1={{{image|{{{imagename|{{{image_name|{{{image name|{{{Img|{{{圖片|{{{图片|{{{圖像|{{{图像|}}}}}}}}}}}}}}}}}}}}}}}}}}}|2={{{nocat_wdimage|}}}}}}}</includeonly><noinclude>
{{documentation}}<!---Please add metadata to the <includeonly> section at the bottom of the /doc subpage--->
</noinclude>