{{Infobox| child       = {{lc:{{{embed|{{{嵌入}}}}}}}}
| title       = {{#ifeq:{{lc:{{{embed|{{{嵌入}}}}}}}}|yes|'''職業摔角生涯'''}}
| decat       = yes <!-- remove from template:infobox tracking categories -->
| bodyclass   = vcard plainlist
| above       = {{{name|<includeonly>{{PAGENAMEBASE}}</includeonly>}}}
| aboveclass  = fn
| image       = {{#invoke:InfoboxImage|InfoboxImage|image={{{image|}}}|size={{{image_size|}}}|sizedefault=frameless|alt={{{alt|}}}|suppressplaceholder=yes}}
| caption     = {{{caption|{{{img_capt|}}}}}}
| headerstyle = background-color: #ddd
| class1      = nickname
| label1      = 本名
| data1       = {{{birth_name|{{{birthname|}}}}}}
| label2      = 出生
| data2       = {{br separated entries|{{{birth_date|}}}|{{{birth_place|}}}}}
| label3      = 逝世
| data3       = {{br separated entries|{{{death_date|}}}|{{{death_place|}}}}}
| label4      = 死因
| data4       = {{{death_cause|}}}
| label5      = 國籍
| data5       = {{{nationality|}}}
| label6      = 居住地
| data6       = {{{residence|{{{resides|}}}}}}
| label7      = 母校
| data7       = {{{alma_mater|{{{alma mater|}}}}}}
| label8      = 配偶
| data8       = {{{spouse|}}}
| label9      = 兒女
| data9       = {{{children|}}}
| label10     = 家族成員
| data10      = {{{family|}}}
| label11     = 網站
| data11      = {{{website|}}}
| header12    = {{#if:{{{ring_names|}}}{{{names|}}}{{{nickname|}}}{{{height|}}}{{{weight|}}}{{{billed|}}}{{{group|}}}{{{exp|}}}{{{trainer|}}}{{{debut|}}}{{{retired|}}}{{{titles|}}}|[[職業摔角|職業摔角生涯]]}}
| label13     = <span class="nowrap">擂台名</span>
| data13      = {{{ring_names|{{{names|}}}}}}
| label14     = 暱稱
| data14      = {{{nickname|}}}
| label15     = 身高
| data15      = {{#if:{{{height|}}}|{{infobox person/height|{{{height}}}}}}}
| label16     = 體重
| data16      = {{#if:{{{weight|}}}|{{infobox person/weight|{{{weight}}}}}}}
| label17     = 測量位置
| data17      = {{{billed|}}}
| label18     = 所屬團體
| data18      = {{{group|}}}
| label19     = 運動經歷
| data19      = {{{exp|}}}
| label20     = 教練
| data20      = {{{trainer|}}}
| label21     = 出道日期
| data21      = {{{debut|}}}
| label22     = 退役日期
| data22      = {{{retired|}}}
| label23     = 主要頭銜
| data23      = {{{titles|}}}
| data24      = {{{misc|{{{module|{{{misc1|{{{module1|}}}}}}}}}}}}
| data25      = {{{misc2|{{{module2|}}}}}}
| data26      = {{{misc3|{{{module3|}}}}}}
| data27      = {{{misc4|{{{module4|}}}}}}
| data28      = {{{misc5|{{{module5|}}}}}}
}}<noinclude>{{Documentation}}</noinclude>