<noinclude>本模板和{{tl|Lang2iso}}将2个字符的[[ISO 639]]语言代码和对应中文名进行转换（如“zh”和“中文”）。本转换表的内容是基于[[ISO 639-1代碼表]]。如果提供的语言名不存在，则默认为“</noinclude>{{{{{subst|}}}#switch: {{{1}}} | aa=阿法爾語 | ab=阿布哈茲語 | ae=阿维斯陀語 | af=南非荷蘭語 | ak=阿坎語 | am=阿比西尼亞官語 | an=阿拉貢語 | ar=阿拉伯語 | as=阿薩姆語 | av=阿瓦爾語 | ay=艾馬拉語 | az=阿塞拜疆語 | ba=巴什基爾語 | be=白俄羅斯語 | bg=保加利亞語 | bh=比哈爾語 | bi=比斯拉馬語 | bm=班巴拉語 | bn=孟加拉語 | bo=藏文 | br=布列塔尼語 | bs=波斯尼亞語 | ca=加泰隆尼亞語 | ce=車臣語 | ch=查莫羅語 | co=科西嘉語 | cr=克里語 | cs=捷克語 | cu=教會斯拉夫語 | cv=楚瓦什語| cy=威爾士語 | da=丹麥語 | de=德語 | deva=Devanāgarī | dv=迪維希語 | dz=宗喀巴 | ee=埃維語 | el=希臘語 | en=英語 | eo=世界語 | es=西班牙語 | et=愛沙尼亞語 | eu=巴斯克語 | fa=波斯語 | ff=富拉語 | fi=芬蘭語 | fj=斐濟語 | fo=法羅語 | fr=法語 | fy=弗里西亞語 | ga=愛爾蘭語 | gd=蘇格蘭蓋爾語 | gl=加利西亞語 | gn=瓜拉尼語 | gu=古吉拉特語 | gv=馬恩島語 | ha=豪薩語 | hans=簡體中文 | hant=繁體中文 | he=希伯來語 | hi=梵文 | ho=Hiri Motu | hr=克羅地亞語 | ht=Haitian | hu=匈牙利語 | hy=亞美尼亞語 | hz=希里莫圖語 | ia=國際語A | id=印尼語 | ie=國際語E| ig=伊博語 | ii=四川彝語 | ik=依努庇克語 | io=伊多語 | is=冰島語 | it=意大利語 | iu=伊努伊特語 | ja=日語 | jv=爪哇語 | ka=格魯吉亞語 | kg=剛果語 | ki=基庫尤語 | kj=寬亞瑪語 | kk=哈薩克語 | kl=格陵蘭語 | km=高棉語 | kn=卡納達語 | ko=朝鮮語 | kr=卡努里語 | ks=克什米爾語 | ku=庫爾德語 | kv=科米語 | kw=康沃爾語 | ky=吉爾吉斯語 | la=拉丁文 | lb=盧森堡語 | lg=干達語 | li=林堡語 | ln=林加拉語 | lo=老撾語 | lt=立陶宛語 | lu=盧巴-加丹加語 | lv=拉脫維亞語 | mg=馬達加斯加語 | mh=馬紹爾語 | mi=毛利語 | mk=馬其頓語 | ml=馬拉亞拉姆語 | mn=蒙古文 | mni=Manipuri | mo=摩爾達維亞語 | mr=馬拉提語 | ms=馬來語 | mt=馬耳他語 | my=缅甸語 | na=瑙魯語 | nb=書面挪威語 | nd=北恩德貝勒語 | ne=尼泊爾語 | ng=恩敦加語 | nl=荷蘭語 | nn=新挪威語 | no=挪威語 | nr=南恩德貝勒語 | nv=納瓦霍語 | ny=尼揚賈語 | oc=奧克西唐語 | oj=奧吉布瓦語 | om=奧洛莫語 | or=奧利亞語 | os=奧塞梯語 | pa=旁遮普語 | pi=巴利語 | pl=波蘭語 | pra=Prakrit | ps=普什圖語 | pt=葡萄牙語| qu=凱楚亞語| rm=利托-羅曼語 | rn=基隆迪語| ro=羅馬尼亞語 | ru=俄語 | rw=基尼阿萬達語| sa=梵語| sc=撒丁島語 | sd=信德語| se=北薩米語 | sg=桑戈語 | sh=塞爾維亞-克羅地亞語 | si=僧加羅語 | sk=斯洛伐克語 | sl=斯洛文尼亞語 | sm=薩摩亞語 | sn=紹納語 | so=索馬里語 | sq=阿爾巴尼亞語 | sr=塞爾維亞語 | ss=斯瓦特語 | st=南索托語 | su=巽他語 | sv=瑞典語 | sw=斯瓦希里語 | ta=泰米爾語 | te=泰盧固語 | tg=塔吉克語 | th=泰國語 | ti=提格里尼亞語 | tk=土庫曼語 | tl=塔加洛語| tlh=Klingon | tn=塞茨瓦納語 | to=湯加語 | tr=突厥語 | ts=宗加語 | tt=韃靼語 | tw=特威語 | ty=塔希提語 | ug=維吾爾語| uk=烏克蘭語 | ur=烏爾都語| uz=烏茲別克語 | ve=文達語| vi=越南語 | vo=沃拉普克語| wa=沃倫語| wo=沃洛夫語 | xh=科薩語| yi=意第緒語 | yo=約魯巴語 | za=壯族語 | zh=中文 | zh-classical=文言文 | zu=祖鲁語 | 未定義語言 }}<noinclude>”。 

==例子==

* <nowiki>{{Iso2lang|de}}</nowiki> 返回“{{Iso2lang|de}}”
* <nowiki>{{Iso2lang|el}}</nowiki> 返回“{{Iso2lang|el}}”
* <nowiki>{{Iso2lang|es}}</nowiki> 返回“{{Iso2lang|es}}”

==另見==
*[[Template:Lang2iso]]
[[Category:语言模板]]
[[en:Template:Iso2lang]]
</noinclude>