{{Documentation subpage}}
{{High-use|3169}}
{{缺乏中文說明}}
<!-- PLEASE ADD CATEGORIES AND INTERWIKIS AT THE BOTTOM OF THIS PAGE -->

{{tl|{{PAGENAME}}}} highlights that a link points to a [[PDF]] document (on some systems PDF files may take time to download and display within the browser, and their use on many websites is not compliant with the [[:en:Web Content Accessibility Guidelines]]).

== Usage ==
The following lines:

<!-- <nowiki>[http://www.example.org/Link.pdf Link] {{PDFlink}}</nowiki>
     No longer works in Internet Explorer with new site-wide CSS-based icon.  Please use the other forms  -->
 <nowiki>{{PDFlink|[http://www.example.org/Link.pdf Link]}}</nowiki>
 <nowiki>{{PDFlink|[http://www.example.org/Link.pdf Link]|32&amp;nbsp;KB}}</nowiki> <!-- only use when the bot fails to update -->
<!-- <nowiki>{{PDFlink|[http://www.example.org/Link.pdf Link]|32&amp;nbsp;[[Kibibyte|KiB]]}}</nowiki>
     Deprecated.  See [[:en:MOS:NUM#Binary prefixes]] -->
 <nowiki>{{PDFlink|[http://www.example.org/fileserver/239349 Link]|1.4&nbsp;MB}}</nowiki>

yield:

:{{PDFlink|[http://www.example.org/Link.pdf Link]}}
:{{PDFlink|[http://www.example.org/Link.pdf Link]|32&nbsp;KB}}
:{{PDFlink|[http://www.example.org/fileserver/239349 Link]|1.4&nbsp;MB}}

'''Note:''' It was previously possible to add the icon with <code><nowiki>{{PDFlink}}</nowiki></code> by itself, but the functionality has changed, making this no longer work in [[Internet Explorer]].  You must surround it with the template as shown above to work correctly in Internet Explorer.{{clarify|reason=What version(s), on what platform(s)?}}  See [[#Use in citation templates]], below, for how to do this now without boogering IE.

'''Units''': Per [[:en:WP:Manual of Style (dates and numbers)]], use KB and MB (kilobytes and megabytes), not KiB and MiB (kibibytes and mibibytes), as very few readers have ever even heard of the latter units.

== Icon ==
The icon is added using CSS and is found in [[MediaWiki:Common.css]], the relevant portion that applies the icon is:
<syntaxhighlight lang="css">
/* Change the external link icon to an Adobe icon anywhere the PDFlink class
   is used (notably Template:PDFlink). This works in IE, unlike the above. */
#content span.PDFlink a,
#mw_content span.PDFlink a {
    background: url("http://upload.wikimedia.org/wikipedia/commons/2/23/Icons-mini-file_acrobat.gif") center right no-repeat;
    padding-right: 18px;
}
</syntaxhighlight>

== Limitations and easy workarounds ==
===The problematic "=" character===
When this template is used with [[m:Help:Templates#Restrictions on parameter values|unnamed parameters]], links containing the "<code>=</code>" (equals sign) character will cause the link to not display at all.  Workarounds available are:
*Use explicitly numbered parameters, {{para|1}} and {{para|2}}, for the URL and the file size, respectively
or
*Use <code><nowiki>{{=}}</nowiki></code> as a replacement for <code>=</code>
or
*Replace the <code>=</code> character with its [[:en:Numeric character reference|numeric character entity reference]], <code>&amp;#61;</code>


;Bad example:
 <nowiki>{{PDFlink|[http://example.org/bla?a=xy|Link.pdf Link to a PDF]|32&amp;nbsp;KB}}</nowiki>
:{{PDFlink|[http://example.org/bla?a=xy/Link.pdf Link to a PDF]|32&nbsp;KB}}


;Good examples:
 <nowiki>{{PDFlink|[http://example.org/bla?a</nowiki><span style="color: red;">'''&amp;#61;'''</span>xy<span style="color: red;">'''&amp;#124;'''</span>Link.pdf Link to a PDF]|32&amp;nbsp;KB}}
:{{PDFlink|[http://example.org/bla?a&#61;xy&#124;Link.pdf Link to a PDF]|32&nbsp;KB}}

 <nowiki>{{PDFlink|</nowiki>'''<span style="color: red;">1=</span>'''<nowiki>[http://example.org/bla?a=xy</nowiki><span style="color: red;">'''<nowiki>{{!}}</nowiki>'''</span>Link.pdf Link to a PDF]|'''<span style="color: red;">2=</span>'''32&amp;nbsp;KB}}
:{{PDFlink|1=[http://example.org/bla?a=xy{{!}}Link.pdf Link to a PDF]|2=32&nbsp;KB}}

===Use in citation templates===
This template is not instantly compatible with citation templates such as {{tl|cite book}} and {{tl|cite web}}, which put URLs in their own parameter, without markup.  Two kinds of usage need two different workarounds, both using the invisible but existent "no-width space" numeric character entity reference, <code>&amp;#8203;</code>.


;URLs ending in ".pdf" or ".PDF":

The workaround is to not use an actual URL (and no [square brackets]) in the {{tl|PDFlink}} first parameter, but just the <code>&amp;#8203;</code> entity:

 <nowiki> |title=Some Article
 |url=http://www.example.org/fileserver/Link.pdf
 |format={{PDFlink|&amp;#8203;|1.4&nbsp;MB}}</nowiki>

renders as something like:

:[http://www.example.org/fileserver/Link.pdf Some Article] ({{PDFlink|&#8203;|1.4&nbsp;MB}})

in the spaces that the parameters fill. (Exact spacing, punctuation, etc., depends on the specific citation template used). This prevents the appearance of a PDF icon auto-generated by MediaWiki being followed by one generated by {{tl|PDFlink}}.

Doing this, however:
 <nowiki> |title=Some Article
 |url=http://www.example.org/fileserver/Link.pdf
 |format={{PDFlink|[http://www.example.org/fileserver/Link.pdf &amp;#8203;]|1.4&nbsp;MB}}</nowiki>

would result in:

:[http://www.example.org/fileserver/Link.pdf Some Article] ({{PDFlink|[http://www.example.org/fileserver/Link.pdf &#8203;]|1.4&nbsp;MB}})

This trick needs to be done with the character entity, because leaving the first parameter blank will simply get the page categorized in a cleanup category for pages that misuse this template, and a bot will "fix" the page's use of the template (i.e., it will cause problems).


;URLs not ending in ".pdf" or ".PDF":

The workaround is to repeat the URL used in {{para|url}} in {{tnull|PDFlink}} inside {{para|format}} as a square-backeted link, and use <code>&amp;#8203;</code> as the link text (note that numbered parameters are often required because of "<code>=</code>" characters in such URLs):

 <nowiki> |title=Some Article
 |url=http://www.example.org/fileserver&file=2234234
 |format={{PDFlink|1=[http://www.example.org/fileserver&file=2234234 &amp;#8203;]|2=1.4&nbsp;MB}}</nowiki>

yields:

:[http://www.example.org/fileserver&file=2234234 Some Article] ({{PDFlink|1=[http://www.example.org/fileserver&file=2234234 &#8203;]|2=1.4&nbsp;MB}})

I.e., it produces a PDF icon that links to the same target as the URL given in the citation template's {{para|url}} parameter, without creating new link text, and meanwhile MediaWiki did not know this was a PDF file and so did not autogenerate a duplicative icon.

<includeonly>
<!-- ADD CATEGORIES BELOW THIS LINE -->
[[Category:輔助模板|{{PAGENAME}}]]

<!-- ADD INTERWIKIS BELOW THIS LINE -->
[[af:Sjabloon:Pdf]]
[[ar:قالب:وصلة بي دي إف]]
[[da:Skabelon:PDFlink]]
[[en:Template:PDFlink]]
[[eo:Ŝablono:PDFligilo]]
[[es:Plantilla:Enlace PDF]]
[[ext:Prantilla:PDF]]
[[fa:الگو:پی&zwnj;دی&zwnj;اف]]
[[fr:Modèle:pdf]]
[[he:תבנית:PDF]]
[[hr:Predložak:Pdf]]
[[hu:Sablon:PDFlink]]
[[ia:Patrono:PDFlink]]
[[id:Templat:PDFlink]]
[[it:Template:Pdf]]
[[ja:Template:PDFlink]]
[[jv:Cithakan:PDFlink]]
[[ko:틀:PDF 링크]]
[[lmo:Mudel:Pdf]]
[[mg:Endrika:Pdf]]
[[mk:Шаблон:PDF-врска]]
[[ms:Templat:PDFlink]]
[[nl:Sjabloon:Pdf]]
[[no:Mal:PDFlink]]
[[oc:Modèl:Pdf]]
[[pt:Predefinição:PDFlink]]
[[roa-tara:Template:Pdf]]
[[sh:Šablon:PDF]]
[[simple:Template:PDFlink]]
[[sk:Šablóna:PDFLink]]
[[sl:Predloga:PDF-povezava]]
[[sv:Mall:PDF]]
[[th:แม่แบบ:PDFlink]]
[[tr:Şablon:PDFlink]]
[[ur:سانچہ:PDFlink]]
</includeonly>