{{#switch:{{{1}}}
| The Cage = {{link-en|囚笼 (星际旅行)|The Cage (Star Trek)|囚笼}}
| Where No Man Has Gone Before = {{link-en|前人未至之境（TOS）|Where No Man Has Gone Before|前人未至之境}}
| The Corbomite Maneuver = 
| Mudd's Women = 
| The Enemy Within = 
| The Man Trap = {{link-en|男性陷阱|The Man Trap}}
| The Naked Time = 
| Charlie X = 
| Balance of Terror = [[恐怖平衡]]
| What Are Little Girls Made Of? = {{link-en|小女孩是什么做的？|What Are Little Girls Made Of?}}
| Dagger of the Mind = 
| Miri = 
| The Conscience of the King = 
| The Galileo Seven = 
| Court Martial = [[:en:Court Martial (Star Trek)|Court Martial]]
| The Menagerie = 
| The Menagerie, Part I = 
| The Menagerie, Part II = 
| Shore Leave = {{link-en|上岸假期 (星际旅行)|Shore Leave (Star Trek)|上岸假期}}
| The Squire of Gothos = 
| Arena = 
| The Alternative Factor = 
| Tomorrow is Yesterday = 
| The Return of the Archons = 
| A Taste of Armageddon = 
| Space Seed = {{link-en|太空种子|Space Seed}}
| This Side of Paradise = 
| The Devil in the Dark = {{link-en|黑夜魔鬼|Devil in the Dark}}
| Devil in the Dark = {{link-en|黑夜魔鬼|Devil in the Dark}}
| Errand of Mercy = 
| The City on the Edge of Forever = 
| Operation -- Annihilate! = 
<!-- Season 2 -->
| Catspaw = 
| Metamorphosis = 
| Friday's Child = 
| Who Mourns for Adonais? = {{link-en|谁悼我主？|Who Mourns for Adonais?}}
| Amok Time = 
| The Doomsday Machine = 
| Wolf in the Fold = 
| The Changeling = 
| The Apple = 
| Mirror, Mirror = [[镜子，镜子]]
| The Deadly Years = 
| I, Mudd = 
| The Trouble with Tribbles = 
| Bread and Circuses = 
| Journey to Babel = 
| A Private Little War = 
| The Gamesters of Triskelion = 
| Obsession = {{link-en|执著 (星际旅行)|Obsession (Star Trek)|执著}}
| The Immunity Syndrome = 
| A Piece of the Action = 
| By Any Other Name = 
| Return to Tomorrow = 
| Patterns of Force = 
| The Ultimate Computer = 
| The Omega Glory = 
| Assignment: Earth = 
<!-- Season 3 -->
| Spectre of the Gun = 
| Elaan of Troyius = 
| The Paradise Syndrome = {{link-en|天堂综合征|The Paradise Syndrome}}
| The Enterprise Incident = 
| And the Children Shall Lead = 
| Spock's Brain = 
| Is There in Truth No Beauty? = 
| The Empath = 
| The Tholian Web = {{tsl|en|The Tholian Web|索利安之网}}
| For the World is Hollow and I Have Touched the Sky = 
| Day of the Dove = 
| Plato's Stepchildren = 
| Wink of an Eye = 
| That Which Survives = 
| Let That Be Your Last Battlefield = 
| Whom Gods Destroy = 
| The Mark of Gideon = 
| The Lights of Zetar = 
| The Cloud Minders = 
| The Way to Eden = 
| Requiem for Methuselah = 
| The Savage Curtain = 
| All Our Yesterdays = 
| Turnabout Intruder = 
}}<noinclude>[[Category:星际旅行模板]]</noinclude><noinclude>{{NoteTA|G1=StarTrek}}</noinclude>