{{#switch:{{{1}}}
| The Cage = 囚笼
| Where No Man Has Gone Before = 前人所未至的领域
| The Corbomite Maneuver = 
| Mudd's Women = 
| The Enemy Within = 
| The Man Trap = 
| The Naked Time = 
| Charlie X = 
| Balance of Terror = 
| What Are Little Girls Made Of? = 
| Dagger of the Mind = 
| Miri = 
| The Conscience of the King = 
| The Galileo Seven = 
| Court Martial = 
| The Menagerie = 
| The Menagerie, Part I = 
| The Menagerie, Part II = 
| Shore Leave = 
| The Squire of Gothos = 
| Arena = 
| The Alternative Factor = 
| Tomorrow is Yesterday = 
| The Return of the Archons = 
| A Taste of Armageddon = 
| Space Seed = 
| This Side of Paradise = 
| The Devil in the Dark = 
| Errand of Mercy = 
| The City on the Edge of Forever = 
| Operation -- Annihilate! = 
<!-- Season 2 -->
| Catspaw = 
| Metamorphosis = 
| Friday's Child = 
| Who Mourns for Adonais? = 
| Amok Time = 
| The Doomsday Machine = 
| Wolf in the Fold = 
| The Changeling = 
| The Apple = 
| Mirror, Mirror = 
| The Deadly Years = 
| I, Mudd = 
| The Trouble with Tribbles = 
| Bread and Circuses = 
| Journey to Babel = 
| A Private Little War = 
| The Gamesters of Triskelion = 
| Obsession = 
| The Immunity Syndrome = 
| A Piece of the Action = 
| By Any Other Name = 
| Return to Tomorrow = 
| Patterns of Force = 
| The Ultimate Computer = 
| The Omega Glory = 
| Assignment: Earth = 
<!-- Season 3 -->
| Spectre of the Gun = 
| Elaan of Troyius = 
| The Paradise Syndrome = 
| The Enterprise Incident = 
| And the Children Shall Lead = 
| Spock's Brain = 
| Is There in Truth No Beauty? = 
| The Empath = 
| The Tholian Web = 
| For the World is Hollow and I Have Touched the Sky = 
| Day of the Dove = 
| Plato's Stepchildren = 
| Wink of an Eye = 
| That Which Survives = 
| Let That Be Your Last Battlefield = 
| Whom Gods Destroy = 
| The Mark of Gideon = 
| The Lights of Zetar = 
| The Cloud Minders = 
| The Way to Eden = 
| Requiem for Methuselah = 
| The Savage Curtain = 
| All Our Yesterdays = 
| Turnabout Intruder = 
}}