{{Userbox
  |border-c=black
  |border-s=1
  |id=原
  |id-c=red
  |id-fc=white
  |id-s=14
  |info=這個用戶喜歡看台灣'''[[原住民族電視台|原視]]'''。
  |info-c=yellow
  |info-fc=green
  |info-s=10
}}<includeonly>[[Category:喜歡觀賞台灣原住民電視台的維基人]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>