{{Userbox-2
|border-c=#000
|border-s=1
|id1-c=yellow
|id1-fc=
|id1-s=14
|id1=人權
|id2-c=white
|id2=[[File:HumanRightsLogo.svg|40px]]
|info-c=white
|info-fc=darkblue
|info-s=10
|info=這個用戶維護'''[[人权]]'''。
|usercategory=維護人權的維基人
}}<noinclude>
[[Category:主張用戶框模板]]
</noinclude>