{{Userbox
|border-c=black
|border-s=1
|id=Zzz...
|id-c=white
|id-fc=black
|id-s=12
|info=這個用戶'''太懶了'''，還沒開始好好編輯用戶頁面。
|info-c=black
|info-fc=white
|info-s=10
|usercategory=太懶而未編好用戶頁的維基人
|nocat={{{nocat|}}}
}}<noinclude>
[[Category:生活用戶框模板]]
</noinclude>