{{Userbox
  |border-c=black
  |border-s=1
  |id=CTV
  |id-c=#ef702e
  |id-fc=#1559aa
  |id-s=14
  |info=這個用戶喜歡觀賞台灣'''[[中國電視公司|中視]]'''。
  |info-c=yellow
  |info-fc=green
  |info-s=10
}}<includeonly>[[Category:喜歡觀賞台灣中視的維基人]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>