{{Userbox
  |border-c=black
  |border-s=1
  |id=[[File:TV_Asahi_Logo.svg|90px]]
  |id-c=White
  |id-fc=#ff69b4
  |id-s=10
  |info=這個用戶喜歡觀賞'''[[朝日電視台]]'''
  |info-c=#FF007F	
  |info-fc=White
  |info-s=9
}}<includeonly>[[Category:喜歡觀賞朝日電視台的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>