{{Userbox
  |boarder-c=#000
  |id-s=13
  |id=人质
  |id-c=#000000
  |id-fc=#FFFFFF
  |info=這個用户曾被綁匪拐帶成為人质。
}}<includeonly>
[[Category:曾被綁匪拐帶成為人質的維基人|{{PAGENAME}}]]
</includeonly><noinclude>{{Clear}}[[Wikipedia:用戶框/幽默]]</noinclude>