{{Userbox
  |border-c=black
  |border-s=1
  |id=SET
  |id-c=yellow
  |id-fc=aqua
  |id-s=12
  |info=這個用戶喜歡觀賞'''[[三立电视]]'''
  |info-c=lime
  |info-fc=blue
  |info-s=9
}}<includeonly>[[Category:喜歡觀賞三立電視的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>