{{Userbox
  |id=[[File:倉頡輸入法五字拆碼.svg|40px]]
  |id-c=#57a2fd
  |id-s=11
  |info=該用戶使用'''{{{name|{{{1|個人設計的}}}}}}[[倉頡輸入法]]'''對[[中文維基百科]]作出[[:Category:仓颉使用者|貢獻]]。
  |info-c=#82ccff
  |border-c=#024ca7
}}<includeonly>[[Category:倉頡使用者|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:软件用户框模板|M:仓颉]]
</noinclude>