{{Userbox
  |id=<!--[[File:NCIT.png|48px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->勤益科大
  |id-c=white
  |info=這個用戶是'''[[國立勤益科技大學]]'''的學生、校友或教職人員。
  |info-c=#E0E8FF
  |info-s=10
  |border-c=#aaaa00
}}<includeonly>[[Category:勤益科技大學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣大專院校用戶框模板]]
[[Category:國立勤益科技大學維基人|*]]
</noinclude>