{{Userbox
  |id={{{1}}}
  |id-c=white
  |id-fc=navy
  |id-s=12
  |info=這個用戶常使用'''[[{{{1}}}]]'''當作交通工具。
  |info-c=#d5d5dd
  |border-c=#aaaabb
  |info-s=10
  |info-fc=navy
  |border-s=1
}}<noinclude>
{{Clear}}
[[Wikipedia:用户框/交通工具]]
[[Category:交通工具用户框模板]]
</noinclude><includeonly>[[Category:使用交通工具的維基人]]</includeonly>