{{Userbox
  |border-c=black
  |border-s=1
  |id={{lang|ja|フジ}}</br>{{lang|ja|テレビ}}
  |id-c=#FFFFFF	
  |id-fc=#000000
  |id-s=10
  |info=這個用戶喜歡觀賞'''[[富士電視台]]'''
  |info-c=#87CEFA			
  |info-fc=White
  |info-s=9
}}<includeonly>[[Category:喜歡觀賞富士電視台的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>