{{Userbox
  |border-c=black
  |border-s=1
  |id={{lang|ja|BLEACH}} 
  |id-c=MediumTurquoise 
  |id-fc=red 
  |id-s=12
  |info=這個用戶來自'''[[BLEACH|屍魂界]]'''。 
  |info-c=orange
  |info-fc=black
  |info-s=10
}}<includeonly>[[Category:喜欢BLEACH的维基人]]</includeonly><noinclude>{{Clear}}[[Wikipedia:用户框/动漫]]</noinclude>