{{Userbox-2
|border-c=#00FF80
|border-s=1
|id1-c=#00FFFF
|id1-s=30
|id1=[[生肖|驴]]
|id2-c=#00FFFF
|id2=[[File:Donkey.jpg|45px]]
|info-c=#00FF80
|info-s=10
|info=这个用户的生肖属'''[[驴]]'''。
}}
<includeonly>[[Category:属驴的维基人|{{PAGENAME}}]]</includeonly>
<noinclude>
<p style="clear: both; padding-top: 2em">
這個模板會把你加入到以下的分類：
*[[:Category:属驴的维基人]]
</p>
[[Category:星座生肖用戶框模板|生]]
</noinclude>