{{Userbox
  |id=朝陽<!--[[File:Cyut_high_resolution.png|46px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=#FFFFFF
  |info=這名用戶是'''[[朝陽科技大學]]'''的學生、校友或教職人員。
  |info-c=#CFE9FB
  |info-s=10
  |border-c=#6BB6E9
}}<includeonly>[[Category:朝陽科技大學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣大專院校用戶框模板]]
</noinclude>