{{Userbox
  |id=人工<br>語言
  |id-c=#808080
  |id-s=13
  |info=這個用戶是個'''[[人工語言]]'''創造者。
  |info-c=#F0F0F0
  |info-s=9
  |info-fc=black
  |border-c=#808080
}}<includeonly>[[Category:创造人工语言的维基人]]
</includeonly>