{{Userbox
  |id={{sans-serif|Pīnyīn}}
  |id-c=#57a2fd
  |id-s=11
  |info=该用户使用'''[[汉语拼音输入法|拼音输入法]]'''對[[中文維基百科]]作出[[:Category:拼音使用者|貢獻]]。
  |info-c=#82ccff
  |border-c=#024ca7
  |usercategory=拼音使用者 
  |nocat={{{nocat|}}}
}}<noinclude>[[Category:软件用户框模板|M:拼音]]
</noinclude>