{{Userbox
  |id=健行科大<!--[[File:Cyu.gif|48px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=white
  |info=這個用戶是'''[[健行科技大學]]'''的學生、校友或教職人員。
  |info-c=#f1ebd3
  |info-s=10
  |border-c=#6699ff
}}<includeonly>[[Category:健行科技大學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣大專院校用戶框模板]]
</noinclude>