{{Userbox
  |id=鳳山高中<!--[[File:Fssh_logo.gif|48px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=white
  |info=這個用戶是'''[[國立鳳山高級中學]]'''的學生、校友或教職人員。
  |info-c=#E0E8FF
  |info-s=10
  |border-c=#6699ff
}}<includeonly>[[Category:國立鳳山高級中學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣高中高職用戶框模板]]
</noinclude>