{{Userbox
  |id=<!--[[File:IvyLeague_100.png|50px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=white
  |info=这个用戶是'''[[常春藤盟校]]'''之一的校友、学生或老师。
  |info-c=#C3FDB8
  |info-s=9
  |info-fc=#aaaa00
  |border-c=#aaaa00
}}<includeonly>[[Category:常春藤盟校維基人|{{PAGENAME}}]]</includeonly><noinclude>{{Clear}}
[[Wikipedia:用户框/教育程度]]</noinclude>