{{Userbox
  |id=<!--[[File:RHUL_logo.jpg|45px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=white
  |info=这个用戶是'''[[皇家哈洛威学院]]'''的校友、学生或老师。
  |info-c=orange
  |info-s=9
  |info-fc=black
  |border-c=black
}}<includeonly>[[Category:皇家哈洛威学院的维基人|{{PAGENAME}}]]</includeonly><noinclude>{{Clear}}[[Wikipedia:用户框/教育程度]]</noinclude>