{{Userbox
  |id=[[File:三民主義統一中國.png|50px]]
  |id-c=
  |info=這個用戶支持'''[[三民主義統一中國]]'''。
  |info-c=yellow
  |info-s=10
  |border-c=blue
  |usercategory=支持三民主義統一中國的維基人
}} 
<noinclude>
[[Category:中国大陆用户框模板]]
[[Category:台灣政治主張用戶框模板]]
</noinclude>