{{Userbox
  |id=花地玛堂
  |id-c=white
  |info=这个用户居住在[[花地玛堂区]]。
  |info-c=#6EF7A7
  |info-s=10
  |border-c=#6EF7A7
}}<includeonly>[[Category:澳門維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:澳門用戶框模板]]</noinclude>