{{Userbox
  |border-c=black
  |border-s=1
  |id=會考
  |id-c=white
  |id-fc=black
  |id-s=
  |info=這用戶擁有[[香港中學會考]]證書
  |info-c=#aaaaaa
  |info-fc=black
  |info-s=10
}}<includeonly>[[Category:準備會考的維基人]]</includeonly>