{{Userbox
|id=王码</br>五笔
|id-c=#57a2fd
|id-s=12
|info-s=9
|info=该用户使用'''[[五笔字型输入法|五笔输入法]]'''對[[中文維基百科]]作出[[:Category:五笔使用者|貢獻]]。
|info-c=#82ccff
|border-c=#024ca7
}}<includeonly>[[Category:五笔使用者|{{PAGENAME}}]]</includeonly><noinclude>
{{模板文档}}
</noinclude>