{{Userbox
  |border-c=black
  |border-s=1
  |id=中天
  |id-c=white
  |id-fc=blue
  |id-s=12
  |info=這個用戶喜歡看'''[[中天电视]]'''
  |info-c=aqua
  |info-fc=Red
  |info-s=9
}}<includeonly>[[Category:喜歡觀賞中天電視的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>