{{Userbox
  |id=成功大學
  |id-c=white
  |info=這個用戶是'''[[國立成功大學]]'''的學生、校友或教職人員。
  |info-c=#FFCCCC
  |info-s=10
  |border-c=#880000 
}}<includeonly>[[Category:國立成功大學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣大專院校用戶框模板]][[Category:國立成功大學]]
</noinclude>