{{Userbox
  |id=高師附中
  |id-c=#999999
  |info=這名用戶是'''[[國立高雄師範大學附屬高級中學]]'''的學生、校友或教職人員。
  |info-c=#E0E8FF
  |info-s=10
  |border-c=#6699ff
}}<includeonly>[[Category:國立高雄師範大學附屬高級中學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣高中高職用戶框模板]]
</noinclude>