{{Userbox
  |id=[[File:South_Building.JPG|80px|開平]]
  |id-c=#CCFF00
  |info=這個用戶是'''[[:Category:开平市维基人|開平人]]'''。
  |info-c=white
  |info-s=9
  |border-c=#000000
  |usercategory=开平市维基人
}}
<noinclude>
[[Category:廣東省維基人用戶框模板]]
</noinclude>