{{Userbox
  |id=臺師大<!--[[File:NTNUlogo.gif|48px]]。注意合理使用之规定：“绝对不能将“合理使用”之图片，放入个人的用户页面进行展示。”-->
  |id-c=#30D5C8
  |info=這個用戶是'''[[:Category:國立臺灣師範大學維基人|國立臺灣師範大學]]'''的學生、校友或教職人員。<br>
  |info-c=#E0E8FF
  |info-s=10
  |border-c=#6699ff
}}<includeonly>[[Category:國立臺灣師範大學維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:台灣大專院校用戶框模板]]
</noinclude>