{{Userbox
  |id=新澳門
  |id-c=white
  |id-fc=green
  |info=這個用戶支持'''[[新澳門學社]]'''。
  |info-c=white
  |info-s=9
  |border-c=green
}}<includeonly>[[Category:支持新澳門學社的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:澳門用戶框模板]]
</noinclude>