{{Userbox
  |id=[[File:Video-x-generic.svg|40px]]
  |id-c=#5577BB
  |info=這個用戶愛看'''[[電影]]'''。
  |info-c=#A1D3EE
  |info-s=10
  |border-c=#000000
}}<includeonly>[[Category:熱愛電影的維基人|{{PAGENAME}}]]</includeonly>
<noinclude>
[[Category:關注與興趣用戶框模板|Movie]]
</noinclude>