{{Userbox
  |id=[[File:Fahrenheit2007.jpg|45px]]
  |id-c=deepskyblue
  |id-fc=navy
  |id-s=10
  |info=这个用户喜欢'''[[飛輪海]]'''。
  |info-c=skyblue
  |info-s=10
  |info-fc=black
  |border-c=black
  |border-s=1
}}
<noinclude>[[Category:维基百科相关用户框]]</noinclude>
[[Category:喜歡飛輪海的維基人|{{PAGENAME}}]]