{{Userbox
 |id=
 |id-c=White
 |id-fc=white
 |id-s=12
 |info=這個用戶喜歡收聽'''[[香港商業電台]]的節目'''。
 |info-c=white
 |info-s=9
 |border-c=blue
}}<noinclude>{{Clear}}[[Category:媒體用戶框模板|廣]][[Wikipedia:用戶框/媒體]]</noinclude>
[[Category:喜歡收聽香港商業電台的維基人]]