{{Userbox
  |border-c=black
  |border-s=1
  |id=[[File:Eastern_Broadcasting_Co_Limited_logo.svg|40px]]
  |id-c=aqua
  |id-fc=yellow
  |id-s=12
  |info=這個用戶喜歡看'''[[东森电视]]'''
  |info-c=#87ceeb
  |info-fc=#009933
  |info-s=9
}}<includeonly>[[Category:喜歡觀賞東森電視的維基人|{{PAGENAME}}]]</includeonly><noinclude>
[[Category:媒體用戶框模板|視]]
</noinclude><noinclude>{{Clear}}[[Wikipedia:用戶框/媒體]]</noinclude>