{{#switch:{{{1}}}
<!--Voyager-->
<!-- Season 1 -->
| Caretaker = -{zh-hans:守护者;zh-hant:守護者的意圖}-
| Parallax = -{zh-hans:视差;zh-hant:重返地球}-
| Time and Again = 回到未来
| Phage = 噬菌之谜| 
| The Cloud = -{zh-hans:星云;zh-hant:星雲風暴}-
| Eye of the Needle = 针眼
| Ex Post Facto = 拨云见日
| Emanations = 来世之旅
| Prime Factors = 空欢喜
| State of Flux = 内忧外患
| Heroes and Demons = 英雄与怪物
| Cathexis = 全神贯注
| Faces = 双面贝拉娜| 
| Jetrel = -{zh-hans:杰特尔博士;zh-hant:梅特恩炸彈}-
| Learning Curve = -{zh-hans:曲线学习;zh-hant:學習曲綫}-
<!-- Season 2 -->
| The 37's = -{zh-hans:37年人;zh-hant:宇宙裏的地球人}-
| Initiations = -{zh-hans:成人礼;zh-hant:成人式的風波}-
| Projections = 投影疑云
| Elogium = -{zh-hans:繁殖行为;zh-hant:新生代}-
| Non Sequitur = 非推论所得-{zh-hans:非推论所得;zh-hant:疑雲重重}-
| Twisted = 变形
| Parturition = 患难见真情
| Persistence of Vision = 内心幻觉
| Tattoo = -{zh-hans:刺青的故事;zh-hant:父子情深}-
| Cold Fire = -{zh-hans:冷焰;zh-hant:希望之旅}-
| Maneuvers = -{zh-hans:阴谋;zh-hant:庫勒的陰謀}-
| Resistance = -{zh-hans:反抗;zh-hant:反抗軍}-
| Prototype = -{zh-hans:原型;zh-hant:標準原型}-
| Alliances = -{zh-hans:联盟;zh-hant:最佳盟友}-
| Threshold = -{zh-hans:极限;zh-hant:超越極速}-
| Meld = -{zh-hans:融合;zh-hant:合而為一}-
| Dreadnought = -{zh-hans:无畏号;zh-hant:無畏艦}-
| Death Wish = -{zh-hans:赐我一死;zh-hant:但求一死}-
| Lifesigns = -{zh-hans:生命记号;zh-hant:惺惺相惜}-
| Investigations = -{zh-hans:调查;zh-hant:内顧之憂}-
| Deadlock = -{zh-hans:绝处重生;zh-hant:絕地重生}-
| Innocence = 返老还童
| The Thaw = 恶梦初醒
| Tuvix = -{zh-hans:杜利克斯;zh-hant:共生体}-
| Resolutions = -{zh-hans:抉择;zh-hant:雪中送炭}-
| Basics = 大敌当前
<!-- Season 3 -->
| Flashback = 往日时光
| The Chute = -{zh-hans:患难与共;zh-hant:患難相扶}-
| The Swarm = -{zh-hans:蝗虫;zh-hant:回春妙手}-
| False Profits = 不义之财
| Remember = -{zh-hans:遗赠;zh-hant:欺世盜名}-
| Sacred Ground = 圣灵之怒
| Future's End = 回到过去
| Warlord = 暴政必亡
| The Q and the Grey = -{zh-hans:Ｑ的由来;zh-hant:宇宙邪靈}-
| Macrocosm = -{zh-hans:巨型病毒;zh-hant:病毒入侵}-
| Fair Trade = -{zh-hans:公平交易;zh-hant:誠實為上}-
| Alter Ego = -{zh-hans:意乱情迷;zh-hant:情迷意亂}-
| Coda = 濒死体验
| Blood Fever = -{zh-hans:血热病;zh-hant:愛欲之潮}-
| Unity = -{zh-hans:联合;zh-hant:博格方塊}-
| Darkling = -{zh-hans:阴暗面;zh-hant:魔由心生}-
| Rise = -{zh-hans:浮生;zh-hant:天降橫禍}-
| Favorite Son = -{zh-hans:幸运儿;zh-hant:身世疑雲}-
| Before and After = -{zh-hans:从前与未来;zh-hant:過去未來}-
| Real Life = -{zh-hans:家庭体验;zh-hant:模範家庭}-
| Distant Origin = -{zh-hans:起源问题;zh-hant:恐龍世代}-
| Displaced = 消失的船员
| Worst Case Scenario = -{zh-hans:最糟场景;zh-hant:變生肘腋}-
| Scorpion = -{zh-hans:与蝎谋皮;zh-hant:蠍與狐}-
<!--Season 4-->
| The Gift = -{zh-hans:天赋;zh-hant:禮物}-
| Day of Honor = -{zh-hans:荣耀之日;zh-hant:榮譽之日}-
| Nemesis = -{zh-hans:复仇者;zh-hant:憎恨之火}-
| Revulsion = -{zh-hans:歧视;zh-hant:投影情節}-
| The Raven = -{zh-hans:渡鸦;zh-hant:渡鴉振翮}-
| Scientific Method = -{zh-hans:所谓科学;zh-hant:基因突變}-
| Year of Hell = -{zh-hans:黑暗一年;zh-hant:黑暗時代}-
| Random Thoughts = -{zh-hans:突发想法;zh-hant:浮想聯翩}-
| Concerning Flight = 乘风翱翔
| Mortal Coil = 迷途森林
| Waking Moments = 南柯一梦
| Message in a Bottle = 瓶中信
| Hunters = -{zh-hans:猎杀者;zh-hant:獵人}-
| Prey = 猎物
| Retrospect = -{zh-hans:反思;zh-hant:潛藏的記憶}-
| The Killing Game = 杀戮游戏
| Vis à Vis = -{zh-hans:变脸;zh-hant:偷龍轉鳳}-
| The Omega Directive = -{zh-hans:欧米加指令;zh-hant:奧米加指令}-
| Unforgettable = -{zh-hans:忘却的记忆;zh-hant:逝去的記憶}-
| Living Witness = 目击证人
| Demon = -{zh-hans:恶魔;zh-hant:惡魔之星}-
| One = -{zh-hans:孤身一人;zh-hant:孤獨之旅}-
| Hope and Fear = 希望与恐惧
<!--Season 5-->
| Night = -{zh-hans:黑夜;zh-hant:危機潛伏}-
| Drone = 博格个体
| Extreme Risk = 极度危险
| In the Flesh = -{zh-hans:血肉之躯;zh-hant:星艦總部}-
| Once Upon a Time = 母女情深
| Timeless = -{zh-hans:超越时间;zh-hant:超越時空}-
| Infinite Regress = 无限沉沦
| Nothing Human = 仁心济世
| Thirty Days = 三十天
| Counterpoint = 虚实以对
| Latent Image = -{zh-hans:被隐藏的记忆;zh-hant:兩難之間}-
| Bride of Chaotica! = -{zh-hans:混沌新娘;zh-hant:普頓大冒險}-
| Gravity = -{zh-hans:引力;zh-hant:重力缺口}-
| Bliss = 天赐之福
| Dark Frontier = -{zh-hans:暗黑前线;zh-hant:黑暗前鋒}-
| The Disease = 爱的瘟疫
| Course: Oblivion = -{zh-hans:忘却的过去;zh-hant:真假難辨}-
| The Fight = 混乱空间
| Think Tank = -{zh-hans:智囊团;zh-hant:智庫}-
| Juggernaut = 核心劳工
| Someone to Watch Over Me = -{zh-hans:谁在守候我;zh-hant:伴我一生}-
| 11:59 = -{zh-hans:11：59;zh-hant:十一點五十九分}-
| Relativity = -{zh-hans:相对时间;zh-hant:相對的世界}-
| Warhead = 人工智能
| Equinox = -{zh-hans:分道扬镳;zh-hant:兩難之間}-
<!--Season 6-->
| Survival Instinct = 生存直觉
| Barge of the Dead = -{zh-hans:死亡之舟;zh-hant:亡船}-
| Tinker, Tenor, Doctor, Spy = 间谍医生
| Alice = 虚拟情人
| Riddles = 谜团
| Dragon's Teeth = -{zh-hans:恶龙之齿;zh-hant:龍之齒}-
| One Small Step = 勇者无惧
| The Voyager Conspiracy = 航海家号上的阴谋
| Pathfinder = 探寻计划
| Fair Haven = 避风港
| Blink of an Eye = 转眼之间
| Virtuoso = 万世巨星
| Memorial = 纪念碑
| Tsunkatse = 极速格斗
| Collective = 何处是我家
| Spirit Folk = 来世精灵
| Ashes to Ashes = 逝者已矣
| Child's Play = 陌生家园
| Good Shepherd = 用心良苦
| Live Fast and Prosper = 真假难辨
| Muse = 灵感女神
| Fury = 愤怒复仇者
| Life Line = 生命线
| The Haunting of Deck Twelve = 鬼影憧憧
| Unimatrix Zero = 揭竿起义
<!--Season 7-->
| Imperfection = -{zh-hans:并非完美;zh-hant:七的眼淚}-
| Drive = -{zh-hans:驾驶;zh-hant:湯姆的真情告白}-
| Repression = -{zh-hans:潜意识;zh-hant:潛意識危機}-
| Critical Care = 十万火急
| Inside Man = -{zh-hans:幕后主使;zh-hant:返鄉計劃}-
| Body and Soul = -{zh-hans:全心全意;zh-hant:醫生和七的邂逅}-
| Nightingale = -{zh-hans:南丁格尔;zh-hant:南丁格爾號}-
| Flesh and Blood = 真实世界
| Shattered = -{zh-hans:时空碎片;zh-hant:時空大混亂}-
| Lineage = 血统
| Repentance = 今是昨非
| Prophecy = 预言
| The Void = 死寂世界
| Workforce = 上班女郎
| Human Error = 爱恨情仇
| Q2 = Q2
| Author, Author = 一代文豪
| Friendship One = 友谊一号
| Natural Law = 自然法则
| Homestead = -{zh-hans:家园;zh-hant:歸鄉}-
| Renaissance Man = 抉择
| Endgame = 星云彼端
}}